import { $Reader } from "@package/java/io";
import { $IntStream } from "@package/java/util/stream";
import { $Terminal } from "@package/org/jline/terminal";
import { $CharSequence, $Iterable_, $Enum } from "@package/java/lang";
import { $List, $List_ } from "@package/java/util";
import { $Pattern } from "@package/java/util/regex";

declare module "@package/org/jline/utils" {
    export class $AttributedStyle {
        inverse(): $AttributedStyle;
        hidden(): $AttributedStyle;
        bold(): $AttributedStyle;
        italic(): $AttributedStyle;
        getMask(): number;
        background(arg0: number, arg1: number, arg2: number): $AttributedStyle;
        background(arg0: number): $AttributedStyle;
        foreground(arg0: number): $AttributedStyle;
        foreground(arg0: number, arg1: number, arg2: number): $AttributedStyle;
        getStyle(): number;
        underline(): $AttributedStyle;
        toAnsi(): string;
        blink(): $AttributedStyle;
        italicDefault(): $AttributedStyle;
        blinkDefault(): $AttributedStyle;
        inverseDefault(): $AttributedStyle;
        crossedOutOff(): $AttributedStyle;
        foregroundDefault(): $AttributedStyle;
        foregroundOff(): $AttributedStyle;
        backgroundOff(): $AttributedStyle;
        boldDefault(): $AttributedStyle;
        underlineDefault(): $AttributedStyle;
        underlineOff(): $AttributedStyle;
        concealDefault(): $AttributedStyle;
        crossedOutDefault(): $AttributedStyle;
        faintDefault(): $AttributedStyle;
        foregroundRgb(arg0: number): $AttributedStyle;
        backgroundRgb(arg0: number): $AttributedStyle;
        backgroundDefault(): $AttributedStyle;
        hiddenDefault(): $AttributedStyle;
        concealOff(): $AttributedStyle;
        blinkOff(): $AttributedStyle;
        inverseNeg(): $AttributedStyle;
        inverseOff(): $AttributedStyle;
        boldOff(): $AttributedStyle;
        faint(): $AttributedStyle;
        faintOff(): $AttributedStyle;
        italicOff(): $AttributedStyle;
        conceal(): $AttributedStyle;
        crossedOut(): $AttributedStyle;
        hiddenOff(): $AttributedStyle;
        static BOLD_OFF: $AttributedStyle;
        static WHITE: number;
        static HIDDEN_OFF: $AttributedStyle;
        static BLUE: number;
        static HIDDEN: $AttributedStyle;
        static GREEN: number;
        static INVERSE: $AttributedStyle;
        static RED: number;
        static BLACK: number;
        static MAGENTA: number;
        static BOLD: $AttributedStyle;
        static YELLOW: number;
        static CYAN: number;
        static DEFAULT: $AttributedStyle;
        static BRIGHT: number;
        static INVERSE_OFF: $AttributedStyle;
        constructor();
        constructor(arg0: $AttributedStyle);
        constructor(arg0: number, arg1: number);
        get mask(): number;
        get style(): number;
    }
    export class $InfoCmp$Capability extends $Enum<$InfoCmp$Capability> {
        static values(): $InfoCmp$Capability[];
        static valueOf(arg0: string): $InfoCmp$Capability;
        getNames(): string[];
        static byName(arg0: string): $InfoCmp$Capability;
        static key_f37: $InfoCmp$Capability;
        static key_f38: $InfoCmp$Capability;
        static key_f35: $InfoCmp$Capability;
        static key_f36: $InfoCmp$Capability;
        static change_res_vert: $InfoCmp$Capability;
        static set_tb_margin: $InfoCmp$Capability;
        static key_btab: $InfoCmp$Capability;
        static mouse_info: $InfoCmp$Capability;
        static key_f39: $InfoCmp$Capability;
        static key_f30: $InfoCmp$Capability;
        static superscript_characters: $InfoCmp$Capability;
        static key_f33: $InfoCmp$Capability;
        static key_f34: $InfoCmp$Capability;
        static key_f31: $InfoCmp$Capability;
        static key_f32: $InfoCmp$Capability;
        static wait_tone: $InfoCmp$Capability;
        static enter_pc_charset_mode: $InfoCmp$Capability;
        static define_bit_image_region: $InfoCmp$Capability;
        static bit_image_type: $InfoCmp$Capability;
        static move_insert_mode: $InfoCmp$Capability;
        static key_shome: $InfoCmp$Capability;
        static initialize_color: $InfoCmp$Capability;
        static clear_all_tabs: $InfoCmp$Capability;
        static cursor_to_ll: $InfoCmp$Capability;
        static key_sundo: $InfoCmp$Capability;
        static virtual_terminal: $InfoCmp$Capability;
        static key_f26: $InfoCmp$Capability;
        static key_f27: $InfoCmp$Capability;
        static enter_protected_mode: $InfoCmp$Capability;
        static key_f24: $InfoCmp$Capability;
        static key_f25: $InfoCmp$Capability;
        static stop_char_set_def: $InfoCmp$Capability;
        static key_up: $InfoCmp$Capability;
        static key_f28: $InfoCmp$Capability;
        static key_f29: $InfoCmp$Capability;
        static cr_cancels_micro_mode: $InfoCmp$Capability;
        static key_f22: $InfoCmp$Capability;
        static key_sright: $InfoCmp$Capability;
        static exit_standout_mode: $InfoCmp$Capability;
        static key_f23: $InfoCmp$Capability;
        static key_f20: $InfoCmp$Capability;
        static clear_screen: $InfoCmp$Capability;
        static key_f21: $InfoCmp$Capability;
        static label_on: $InfoCmp$Capability;
        static set_a_foreground: $InfoCmp$Capability;
        static eat_newline_glitch: $InfoCmp$Capability;
        static restore_cursor: $InfoCmp$Capability;
        static remove_clock: $InfoCmp$Capability;
        static key_sreplace: $InfoCmp$Capability;
        static key_left: $InfoCmp$Capability;
        static bit_image_newline: $InfoCmp$Capability;
        static key_f15: $InfoCmp$Capability;
        static set1_des_seq: $InfoCmp$Capability;
        static key_f16: $InfoCmp$Capability;
        static key_f13: $InfoCmp$Capability;
        static key_eos: $InfoCmp$Capability;
        static key_f14: $InfoCmp$Capability;
        static key_f19: $InfoCmp$Capability;
        static key_message: $InfoCmp$Capability;
        static micro_right: $InfoCmp$Capability;
        static key_f17: $InfoCmp$Capability;
        static key_f18: $InfoCmp$Capability;
        static exit_insert_mode: $InfoCmp$Capability;
        static key_eol: $InfoCmp$Capability;
        static repeat_char: $InfoCmp$Capability;
        static non_rev_rmcup: $InfoCmp$Capability;
        static key_f11: $InfoCmp$Capability;
        static key_f12: $InfoCmp$Capability;
        static key_f10: $InfoCmp$Capability;
        static key_seol: $InfoCmp$Capability;
        static key_select: $InfoCmp$Capability;
        static enter_standout_mode: $InfoCmp$Capability;
        static key_sr: $InfoCmp$Capability;
        static change_res_horz: $InfoCmp$Capability;
        static key_move: $InfoCmp$Capability;
        static micro_left: $InfoCmp$Capability;
        static insert_line: $InfoCmp$Capability;
        static key_sf: $InfoCmp$Capability;
        static set_tab: $InfoCmp$Capability;
        static max_attributes: $InfoCmp$Capability;
        static buffer_capacity: $InfoCmp$Capability;
        static bit_image_carriage_return: $InfoCmp$Capability;
        static enter_superscript_mode: $InfoCmp$Capability;
        static parm_rindex: $InfoCmp$Capability;
        static exit_doublewide_mode: $InfoCmp$Capability;
        static reset_3string: $InfoCmp$Capability;
        static max_micro_address: $InfoCmp$Capability;
        static key_copy: $InfoCmp$Capability;
        static set_attributes: $InfoCmp$Capability;
        static label_height: $InfoCmp$Capability;
        static hue_lightness_saturation: $InfoCmp$Capability;
        static set_left_margin: $InfoCmp$Capability;
        static cursor_right: $InfoCmp$Capability;
        static erase_chars: $InfoCmp$Capability;
        static exit_upward_mode: $InfoCmp$Capability;
        static key_ppage: $InfoCmp$Capability;
        static ceol_standout_glitch: $InfoCmp$Capability;
        static ena_acs: $InfoCmp$Capability;
        static subscript_characters: $InfoCmp$Capability;
        static key_f62: $InfoCmp$Capability;
        static key_f63: $InfoCmp$Capability;
        static key_f60: $InfoCmp$Capability;
        static key_f61: $InfoCmp$Capability;
        static keypad_xmit: $InfoCmp$Capability;
        static carriage_return: $InfoCmp$Capability;
        static enter_horizontal_hl_mode: $InfoCmp$Capability;
        static enter_scancode_mode: $InfoCmp$Capability;
        static key_send: $InfoCmp$Capability;
        static enter_subscript_mode: $InfoCmp$Capability;
        static parm_delete_line: $InfoCmp$Capability;
        static micro_row_address: $InfoCmp$Capability;
        static set_color_pair: $InfoCmp$Capability;
        static key_f59: $InfoCmp$Capability;
        static key_f57: $InfoCmp$Capability;
        static key_f58: $InfoCmp$Capability;
        static prtr_silent: $InfoCmp$Capability;
        static key_f51: $InfoCmp$Capability;
        static key_f52: $InfoCmp$Capability;
        static key_f50: $InfoCmp$Capability;
        static parm_index: $InfoCmp$Capability;
        static tilde_glitch: $InfoCmp$Capability;
        static key_f55: $InfoCmp$Capability;
        static key_f56: $InfoCmp$Capability;
        static key_f53: $InfoCmp$Capability;
        static exit_underline_mode: $InfoCmp$Capability;
        static key_f54: $InfoCmp$Capability;
        static key_sbeg: $InfoCmp$Capability;
        static bit_image_repeat: $InfoCmp$Capability;
        static enter_normal_quality: $InfoCmp$Capability;
        static flash_hook: $InfoCmp$Capability;
        static key_sprint: $InfoCmp$Capability;
        static non_dest_scroll_region: $InfoCmp$Capability;
        static padding_baud_rate: $InfoCmp$Capability;
        static lines: $InfoCmp$Capability;
        static key_f48: $InfoCmp$Capability;
        static key_f49: $InfoCmp$Capability;
        static key_f46: $InfoCmp$Capability;
        static key_f47: $InfoCmp$Capability;
        static key_f40: $InfoCmp$Capability;
        static key_f41: $InfoCmp$Capability;
        static key_f44: $InfoCmp$Capability;
        static semi_auto_right_margin: $InfoCmp$Capability;
        static key_f45: $InfoCmp$Capability;
        static key_f42: $InfoCmp$Capability;
        static label_width: $InfoCmp$Capability;
        static key_f43: $InfoCmp$Capability;
        static scroll_forward: $InfoCmp$Capability;
        static generic_type: $InfoCmp$Capability;
        static key_help: $InfoCmp$Capability;
        static hard_copy: $InfoCmp$Capability;
        static cursor_address: $InfoCmp$Capability;
        static key_sleft: $InfoCmp$Capability;
        static select_char_set: $InfoCmp$Capability;
        static enter_underline_mode: $InfoCmp$Capability;
        static wide_char_size: $InfoCmp$Capability;
        static key_smove: $InfoCmp$Capability;
        static key_screate: $InfoCmp$Capability;
        static no_color_video: $InfoCmp$Capability;
        static key_next: $InfoCmp$Capability;
        static init_2string: $InfoCmp$Capability;
        static reset_1string: $InfoCmp$Capability;
        static no_pad_char: $InfoCmp$Capability;
        static enter_left_hl_mode: $InfoCmp$Capability;
        static orig_colors: $InfoCmp$Capability;
        static hard_cursor: $InfoCmp$Capability;
        static key_close: $InfoCmp$Capability;
        static meta_off: $InfoCmp$Capability;
        static set_page_length: $InfoCmp$Capability;
        static exit_scancode_mode: $InfoCmp$Capability;
        static key_create: $InfoCmp$Capability;
        static bell: $InfoCmp$Capability;
        static has_status_line: $InfoCmp$Capability;
        static key_sdl: $InfoCmp$Capability;
        static key_eic: $InfoCmp$Capability;
        static key_sdc: $InfoCmp$Capability;
        static cursor_left: $InfoCmp$Capability;
        static enter_am_mode: $InfoCmp$Capability;
        static key_scommand: $InfoCmp$Capability;
        static enter_draft_quality: $InfoCmp$Capability;
        static flash_screen: $InfoCmp$Capability;
        static parm_down_micro: $InfoCmp$Capability;
        static char_padding: $InfoCmp$Capability;
        static to_status_line: $InfoCmp$Capability;
        static tone: $InfoCmp$Capability;
        static auto_right_margin: $InfoCmp$Capability;
        static exit_attribute_mode: $InfoCmp$Capability;
        static key_suspend: $InfoCmp$Capability;
        static micro_up: $InfoCmp$Capability;
        static lab_f4: $InfoCmp$Capability;
        static reset_2string: $InfoCmp$Capability;
        static cursor_up: $InfoCmp$Capability;
        static lab_f5: $InfoCmp$Capability;
        static lab_f6: $InfoCmp$Capability;
        static init_3string: $InfoCmp$Capability;
        static lab_f7: $InfoCmp$Capability;
        static lab_f8: $InfoCmp$Capability;
        static lab_f9: $InfoCmp$Capability;
        static lines_of_memory: $InfoCmp$Capability;
        static enter_alt_charset_mode: $InfoCmp$Capability;
        static insert_null_glitch: $InfoCmp$Capability;
        static key_clear: $InfoCmp$Capability;
        static key_scopy: $InfoCmp$Capability;
        static key_print: $InfoCmp$Capability;
        static dial_phone: $InfoCmp$Capability;
        static key_mark: $InfoCmp$Capability;
        static enter_vertical_hl_mode: $InfoCmp$Capability;
        static exit_xon_mode: $InfoCmp$Capability;
        static key_previous: $InfoCmp$Capability;
        static set_bottom_margin_parm: $InfoCmp$Capability;
        static cursor_down: $InfoCmp$Capability;
        static key_sic: $InfoCmp$Capability;
        static orig_pair: $InfoCmp$Capability;
        static init_prog: $InfoCmp$Capability;
        static key_a3: $InfoCmp$Capability;
        static key_a1: $InfoCmp$Capability;
        static hangup: $InfoCmp$Capability;
        static key_end: $InfoCmp$Capability;
        static key_scancel: $InfoCmp$Capability;
        static key_catab: $InfoCmp$Capability;
        static from_status_line: $InfoCmp$Capability;
        static dis_status_line: $InfoCmp$Capability;
        static enter_reverse_mode: $InfoCmp$Capability;
        static lab_f0: $InfoCmp$Capability;
        static lab_f1: $InfoCmp$Capability;
        static key_b2: $InfoCmp$Capability;
        static lab_f2: $InfoCmp$Capability;
        static lab_f3: $InfoCmp$Capability;
        static exit_shadow_mode: $InfoCmp$Capability;
        static goto_window: $InfoCmp$Capability;
        static key_shelp: $InfoCmp$Capability;
        static cursor_visible: $InfoCmp$Capability;
        static create_window: $InfoCmp$Capability;
        static dest_tabs_magic_smso: $InfoCmp$Capability;
        static exit_leftward_mode: $InfoCmp$Capability;
        static color_names: $InfoCmp$Capability;
        static xoff_character: $InfoCmp$Capability;
        static enter_micro_mode: $InfoCmp$Capability;
        static exit_superscript_mode: $InfoCmp$Capability;
        static key_beg: $InfoCmp$Capability;
        static parm_ich: $InfoCmp$Capability;
        static auto_left_margin: $InfoCmp$Capability;
        static enter_shadow_mode: $InfoCmp$Capability;
        static enter_ca_mode: $InfoCmp$Capability;
        static key_enter: $InfoCmp$Capability;
        static parm_up_cursor: $InfoCmp$Capability;
        static prtr_off: $InfoCmp$Capability;
        static key_snext: $InfoCmp$Capability;
        static col_addr_glitch: $InfoCmp$Capability;
        static buttons: $InfoCmp$Capability;
        static keypad_local: $InfoCmp$Capability;
        static enter_right_hl_mode: $InfoCmp$Capability;
        static key_soptions: $InfoCmp$Capability;
        static init_tabs: $InfoCmp$Capability;
        static init_1string: $InfoCmp$Capability;
        static key_right: $InfoCmp$Capability;
        static key_open: $InfoCmp$Capability;
        static exit_alt_charset_mode: $InfoCmp$Capability;
        static micro_down: $InfoCmp$Capability;
        static pulse: $InfoCmp$Capability;
        static zero_motion: $InfoCmp$Capability;
        static lpi_changes_res: $InfoCmp$Capability;
        static key_stab: $InfoCmp$Capability;
        static set0_des_seq: $InfoCmp$Capability;
        static display_clock: $InfoCmp$Capability;
        static key_dc: $InfoCmp$Capability;
        static key_redo: $InfoCmp$Capability;
        static enter_bold_mode: $InfoCmp$Capability;
        static parm_right_micro: $InfoCmp$Capability;
        static parm_up_micro: $InfoCmp$Capability;
        static erase_overstrike: $InfoCmp$Capability;
        static cursor_invisible: $InfoCmp$Capability;
        static start_char_set_def: $InfoCmp$Capability;
        static needs_xon_xoff: $InfoCmp$Capability;
        static code_set_init: $InfoCmp$Capability;
        static set_lr_margin: $InfoCmp$Capability;
        static set_a_attributes: $InfoCmp$Capability;
        static enter_upward_mode: $InfoCmp$Capability;
        static enter_blink_mode: $InfoCmp$Capability;
        static label_format: $InfoCmp$Capability;
        static width_status_line: $InfoCmp$Capability;
        static clear_margins: $InfoCmp$Capability;
        static enter_near_letter_quality: $InfoCmp$Capability;
        static key_f8: $InfoCmp$Capability;
        static num_labels: $InfoCmp$Capability;
        static key_f9: $InfoCmp$Capability;
        static key_f6: $InfoCmp$Capability;
        static key_f7: $InfoCmp$Capability;
        static key_f4: $InfoCmp$Capability;
        static key_f5: $InfoCmp$Capability;
        static key_f2: $InfoCmp$Capability;
        static key_f3: $InfoCmp$Capability;
        static enter_top_hl_mode: $InfoCmp$Capability;
        static key_f0: $InfoCmp$Capability;
        static key_f1: $InfoCmp$Capability;
        static micro_line_size: $InfoCmp$Capability;
        static enter_xon_mode: $InfoCmp$Capability;
        static key_dl: $InfoCmp$Capability;
        static enter_insert_mode: $InfoCmp$Capability;
        static row_addr_glitch: $InfoCmp$Capability;
        static output_res_line: $InfoCmp$Capability;
        static key_options: $InfoCmp$Capability;
        static key_find: $InfoCmp$Capability;
        static cursor_home: $InfoCmp$Capability;
        static transparent_underline: $InfoCmp$Capability;
        static bit_image_entwining: $InfoCmp$Capability;
        static print_screen: $InfoCmp$Capability;
        static back_tab: $InfoCmp$Capability;
        static key_c3: $InfoCmp$Capability;
        static set_left_margin_parm: $InfoCmp$Capability;
        static pad_char: $InfoCmp$Capability;
        static key_c1: $InfoCmp$Capability;
        static req_for_input: $InfoCmp$Capability;
        static memory_above: $InfoCmp$Capability;
        static xon_xoff: $InfoCmp$Capability;
        static order_of_pins: $InfoCmp$Capability;
        static key_replace: $InfoCmp$Capability;
        static reset_file: $InfoCmp$Capability;
        static exit_italics_mode: $InfoCmp$Capability;
        static down_half_line: $InfoCmp$Capability;
        static clr_bol: $InfoCmp$Capability;
        static label_off: $InfoCmp$Capability;
        static set_a_background: $InfoCmp$Capability;
        static set_right_margin_parm: $InfoCmp$Capability;
        static get_mouse: $InfoCmp$Capability;
        static key_save: $InfoCmp$Capability;
        static parm_dch: $InfoCmp$Capability;
        static max_micro_jump: $InfoCmp$Capability;
        static set2_des_seq: $InfoCmp$Capability;
        static cursor_mem_address: $InfoCmp$Capability;
        static key_sprevious: $InfoCmp$Capability;
        static delete_character: $InfoCmp$Capability;
        static exit_micro_mode: $InfoCmp$Capability;
        static quick_dial: $InfoCmp$Capability;
        static output_res_char: $InfoCmp$Capability;
        static pc_term_options: $InfoCmp$Capability;
        static save_cursor: $InfoCmp$Capability;
        static pkey_plab: $InfoCmp$Capability;
        static parm_insert_line: $InfoCmp$Capability;
        static key_ic: $InfoCmp$Capability;
        static meta_on: $InfoCmp$Capability;
        static magic_cookie_glitch: $InfoCmp$Capability;
        static command_character: $InfoCmp$Capability;
        static maximum_windows: $InfoCmp$Capability;
        static set_foreground: $InfoCmp$Capability;
        static status_line_esc_ok: $InfoCmp$Capability;
        static move_standout_mode: $InfoCmp$Capability;
        static key_smessage: $InfoCmp$Capability;
        static pkey_local: $InfoCmp$Capability;
        static alt_scancode_esc: $InfoCmp$Capability;
        static define_char: $InfoCmp$Capability;
        static key_restart: $InfoCmp$Capability;
        static key_refresh: $InfoCmp$Capability;
        static enter_delete_mode: $InfoCmp$Capability;
        static key_resume: $InfoCmp$Capability;
        static enter_leftward_mode: $InfoCmp$Capability;
        static dot_vert_spacing: $InfoCmp$Capability;
        static exit_delete_mode: $InfoCmp$Capability;
        static pkey_xmit: $InfoCmp$Capability;
        static stop_bit_image: $InfoCmp$Capability;
        static fixed_pause: $InfoCmp$Capability;
        static cursor_normal: $InfoCmp$Capability;
        static set_window: $InfoCmp$Capability;
        static set_top_margin_parm: $InfoCmp$Capability;
        static key_sredo: $InfoCmp$Capability;
        static scroll_reverse: $InfoCmp$Capability;
        static cpi_changes_res: $InfoCmp$Capability;
        static scancode_escape: $InfoCmp$Capability;
        static insert_padding: $InfoCmp$Capability;
        static set_color_band: $InfoCmp$Capability;
        static underline_char: $InfoCmp$Capability;
        static change_line_pitch: $InfoCmp$Capability;
        static set_bottom_margin: $InfoCmp$Capability;
        static exit_am_mode: $InfoCmp$Capability;
        static key_ssuspend: $InfoCmp$Capability;
        static delete_line: $InfoCmp$Capability;
        static key_undo: $InfoCmp$Capability;
        static end_bit_image_region: $InfoCmp$Capability;
        static change_scroll_region: $InfoCmp$Capability;
        static char_set_names: $InfoCmp$Capability;
        static these_cause_cr: $InfoCmp$Capability;
        static key_sfind: $InfoCmp$Capability;
        static key_exit: $InfoCmp$Capability;
        static row_address: $InfoCmp$Capability;
        static clr_eol: $InfoCmp$Capability;
        static display_pc_char: $InfoCmp$Capability;
        static exit_pc_charset_mode: $InfoCmp$Capability;
        static clr_eos: $InfoCmp$Capability;
        static exit_ca_mode: $InfoCmp$Capability;
        static key_ll: $InfoCmp$Capability;
        static number_of_pins: $InfoCmp$Capability;
        static columns: $InfoCmp$Capability;
        static dot_horz_spacing: $InfoCmp$Capability;
        static has_meta_key: $InfoCmp$Capability;
        static plab_norm: $InfoCmp$Capability;
        static key_cancel: $InfoCmp$Capability;
        static key_down: $InfoCmp$Capability;
        static key_mouse: $InfoCmp$Capability;
        static set_clock: $InfoCmp$Capability;
        static key_il: $InfoCmp$Capability;
        static user1: $InfoCmp$Capability;
        static prtr_non: $InfoCmp$Capability;
        static user2: $InfoCmp$Capability;
        static set_background: $InfoCmp$Capability;
        static user0: $InfoCmp$Capability;
        static key_reference: $InfoCmp$Capability;
        static key_home: $InfoCmp$Capability;
        static user9: $InfoCmp$Capability;
        static user7: $InfoCmp$Capability;
        static lab_f10: $InfoCmp$Capability;
        static user8: $InfoCmp$Capability;
        static user5: $InfoCmp$Capability;
        static user6: $InfoCmp$Capability;
        static user3: $InfoCmp$Capability;
        static user4: $InfoCmp$Capability;
        static xon_character: $InfoCmp$Capability;
        static key_srsume: $InfoCmp$Capability;
        static key_command: $InfoCmp$Capability;
        static output_res_vert_inch: $InfoCmp$Capability;
        static print_rate: $InfoCmp$Capability;
        static set_pglen_inch: $InfoCmp$Capability;
        static key_ssave: $InfoCmp$Capability;
        static key_backspace: $InfoCmp$Capability;
        static acs_chars: $InfoCmp$Capability;
        static micro_column_address: $InfoCmp$Capability;
        static output_res_horz_inch: $InfoCmp$Capability;
        static parm_left_micro: $InfoCmp$Capability;
        static device_type: $InfoCmp$Capability;
        static insert_character: $InfoCmp$Capability;
        static parm_left_cursor: $InfoCmp$Capability;
        static newline: $InfoCmp$Capability;
        static has_print_wheel: $InfoCmp$Capability;
        static set_right_margin: $InfoCmp$Capability;
        static tab: $InfoCmp$Capability;
        static change_char_pitch: $InfoCmp$Capability;
        static can_change: $InfoCmp$Capability;
        static prtr_on: $InfoCmp$Capability;
        static start_bit_image: $InfoCmp$Capability;
        static key_npage: $InfoCmp$Capability;
        static req_mouse_pos: $InfoCmp$Capability;
        static max_colors: $InfoCmp$Capability;
        static enter_secure_mode: $InfoCmp$Capability;
        static initialize_pair: $InfoCmp$Capability;
        static set3_des_seq: $InfoCmp$Capability;
        static key_sexit: $InfoCmp$Capability;
        static back_color_erase: $InfoCmp$Capability;
        static init_file: $InfoCmp$Capability;
        static pkey_key: $InfoCmp$Capability;
        static micro_col_size: $InfoCmp$Capability;
        static key_ctab: $InfoCmp$Capability;
        static parm_right_cursor: $InfoCmp$Capability;
        static up_half_line: $InfoCmp$Capability;
        static memory_below: $InfoCmp$Capability;
        static max_pairs: $InfoCmp$Capability;
        static column_address: $InfoCmp$Capability;
        static no_esc_ctlc: $InfoCmp$Capability;
        static form_feed: $InfoCmp$Capability;
        static enter_doublewide_mode: $InfoCmp$Capability;
        static over_strike: $InfoCmp$Capability;
        static enter_dim_mode: $InfoCmp$Capability;
        static parm_down_cursor: $InfoCmp$Capability;
        static set_top_margin: $InfoCmp$Capability;
        static exit_subscript_mode: $InfoCmp$Capability;
        static enter_low_hl_mode: $InfoCmp$Capability;
        static enter_italics_mode: $InfoCmp$Capability;
        get names(): string[];
    }
    /**
     * Values that may be interpreted as {@link $InfoCmp$Capability}.
     */
    export type $InfoCmp$Capability_ = "auto_left_margin" | "auto_right_margin" | "back_color_erase" | "can_change" | "ceol_standout_glitch" | "col_addr_glitch" | "cpi_changes_res" | "cr_cancels_micro_mode" | "dest_tabs_magic_smso" | "eat_newline_glitch" | "erase_overstrike" | "generic_type" | "hard_copy" | "hard_cursor" | "has_meta_key" | "has_print_wheel" | "has_status_line" | "hue_lightness_saturation" | "insert_null_glitch" | "lpi_changes_res" | "memory_above" | "memory_below" | "move_insert_mode" | "move_standout_mode" | "needs_xon_xoff" | "no_esc_ctlc" | "no_pad_char" | "non_dest_scroll_region" | "non_rev_rmcup" | "over_strike" | "prtr_silent" | "row_addr_glitch" | "semi_auto_right_margin" | "status_line_esc_ok" | "tilde_glitch" | "transparent_underline" | "xon_xoff" | "columns" | "init_tabs" | "label_height" | "label_width" | "lines" | "lines_of_memory" | "magic_cookie_glitch" | "max_attributes" | "max_colors" | "max_pairs" | "maximum_windows" | "no_color_video" | "num_labels" | "padding_baud_rate" | "virtual_terminal" | "width_status_line" | "bit_image_entwining" | "bit_image_type" | "buffer_capacity" | "buttons" | "dot_horz_spacing" | "dot_vert_spacing" | "max_micro_address" | "max_micro_jump" | "micro_col_size" | "micro_line_size" | "number_of_pins" | "output_res_char" | "output_res_horz_inch" | "output_res_line" | "output_res_vert_inch" | "print_rate" | "wide_char_size" | "acs_chars" | "back_tab" | "bell" | "carriage_return" | "change_char_pitch" | "change_line_pitch" | "change_res_horz" | "change_res_vert" | "change_scroll_region" | "char_padding" | "clear_all_tabs" | "clear_margins" | "clear_screen" | "clr_bol" | "clr_eol" | "clr_eos" | "column_address" | "command_character" | "create_window" | "cursor_address" | "cursor_down" | "cursor_home" | "cursor_invisible" | "cursor_left" | "cursor_mem_address" | "cursor_normal" | "cursor_right" | "cursor_to_ll" | "cursor_up" | "cursor_visible" | "define_char" | "delete_character" | "delete_line" | "dial_phone" | "dis_status_line" | "display_clock" | "down_half_line" | "ena_acs" | "enter_alt_charset_mode" | "enter_am_mode" | "enter_blink_mode" | "enter_bold_mode" | "enter_ca_mode" | "enter_delete_mode" | "enter_dim_mode" | "enter_doublewide_mode" | "enter_draft_quality" | "enter_insert_mode" | "enter_italics_mode" | "enter_leftward_mode" | "enter_micro_mode" | "enter_near_letter_quality" | "enter_normal_quality" | "enter_protected_mode" | "enter_reverse_mode" | "enter_secure_mode" | "enter_shadow_mode" | "enter_standout_mode" | "enter_subscript_mode" | "enter_superscript_mode" | "enter_underline_mode" | "enter_upward_mode" | "enter_xon_mode" | "erase_chars" | "exit_alt_charset_mode" | "exit_am_mode" | "exit_attribute_mode" | "exit_ca_mode" | "exit_delete_mode" | "exit_doublewide_mode" | "exit_insert_mode" | "exit_italics_mode" | "exit_leftward_mode" | "exit_micro_mode" | "exit_shadow_mode" | "exit_standout_mode" | "exit_subscript_mode" | "exit_superscript_mode" | "exit_underline_mode" | "exit_upward_mode" | "exit_xon_mode" | "fixed_pause" | "flash_hook" | "flash_screen" | "form_feed" | "from_status_line" | "goto_window" | "hangup" | "init_1string" | "init_2string" | "init_3string" | "init_file" | "init_prog" | "initialize_color" | "initialize_pair" | "insert_character" | "insert_line" | "insert_padding" | "key_a1" | "key_a3" | "key_b2" | "key_backspace" | "key_beg" | "key_btab" | "key_c1" | "key_c3" | "key_cancel" | "key_catab" | "key_clear" | "key_close" | "key_command" | "key_copy" | "key_create" | "key_ctab" | "key_dc" | "key_dl" | "key_down" | "key_eic" | "key_end" | "key_enter" | "key_eol" | "key_eos" | "key_exit" | "key_f0" | "key_f1" | "key_f10" | "key_f11" | "key_f12" | "key_f13" | "key_f14" | "key_f15" | "key_f16" | "key_f17" | "key_f18" | "key_f19" | "key_f2" | "key_f20" | "key_f21" | "key_f22" | "key_f23" | "key_f24" | "key_f25" | "key_f26" | "key_f27" | "key_f28" | "key_f29" | "key_f3" | "key_f30" | "key_f31" | "key_f32" | "key_f33" | "key_f34" | "key_f35" | "key_f36" | "key_f37" | "key_f38" | "key_f39" | "key_f4" | "key_f40" | "key_f41" | "key_f42" | "key_f43" | "key_f44" | "key_f45" | "key_f46" | "key_f47" | "key_f48" | "key_f49" | "key_f5" | "key_f50" | "key_f51" | "key_f52" | "key_f53" | "key_f54" | "key_f55" | "key_f56" | "key_f57" | "key_f58" | "key_f59" | "key_f6" | "key_f60" | "key_f61" | "key_f62" | "key_f63" | "key_f7" | "key_f8" | "key_f9" | "key_find" | "key_help" | "key_home" | "key_ic" | "key_il" | "key_left" | "key_ll" | "key_mark" | "key_message" | "key_move" | "key_next" | "key_npage" | "key_open" | "key_options" | "key_ppage" | "key_previous" | "key_print" | "key_redo" | "key_reference" | "key_refresh" | "key_replace" | "key_restart" | "key_resume" | "key_right" | "key_save" | "key_sbeg" | "key_scancel" | "key_scommand" | "key_scopy" | "key_screate" | "key_sdc" | "key_sdl" | "key_select" | "key_send" | "key_seol" | "key_sexit" | "key_sf" | "key_sfind" | "key_shelp" | "key_shome" | "key_sic" | "key_sleft" | "key_smessage" | "key_smove" | "key_snext" | "key_soptions" | "key_sprevious" | "key_sprint" | "key_sr" | "key_sredo" | "key_sreplace" | "key_sright" | "key_srsume" | "key_ssave" | "key_ssuspend" | "key_stab" | "key_sundo" | "key_suspend" | "key_undo" | "key_up" | "keypad_local" | "keypad_xmit" | "lab_f0" | "lab_f1" | "lab_f10" | "lab_f2" | "lab_f3" | "lab_f4" | "lab_f5" | "lab_f6" | "lab_f7" | "lab_f8" | "lab_f9" | "label_format" | "label_off" | "label_on" | "meta_off" | "meta_on" | "micro_column_address" | "micro_down" | "micro_left" | "micro_right" | "micro_row_address" | "micro_up" | "newline" | "order_of_pins" | "orig_colors" | "orig_pair" | "pad_char" | "parm_dch" | "parm_delete_line" | "parm_down_cursor" | "parm_down_micro" | "parm_ich" | "parm_index" | "parm_insert_line" | "parm_left_cursor" | "parm_left_micro" | "parm_right_cursor" | "parm_right_micro" | "parm_rindex" | "parm_up_cursor" | "parm_up_micro" | "pkey_key" | "pkey_local" | "pkey_xmit" | "plab_norm" | "print_screen" | "prtr_non" | "prtr_off" | "prtr_on" | "pulse" | "quick_dial" | "remove_clock" | "repeat_char" | "req_for_input" | "reset_1string" | "reset_2string" | "reset_3string" | "reset_file" | "restore_cursor" | "row_address" | "save_cursor" | "scroll_forward" | "scroll_reverse" | "select_char_set" | "set_attributes" | "set_background" | "set_bottom_margin" | "set_bottom_margin_parm" | "set_clock" | "set_color_pair" | "set_foreground" | "set_left_margin" | "set_left_margin_parm" | "set_right_margin" | "set_right_margin_parm" | "set_tab" | "set_top_margin" | "set_top_margin_parm" | "set_window" | "start_bit_image" | "start_char_set_def" | "stop_bit_image" | "stop_char_set_def" | "subscript_characters" | "superscript_characters" | "tab" | "these_cause_cr" | "to_status_line" | "tone" | "underline_char" | "up_half_line" | "user0" | "user1" | "user2" | "user3" | "user4" | "user5" | "user6" | "user7" | "user8" | "user9" | "wait_tone" | "xoff_character" | "xon_character" | "zero_motion" | "alt_scancode_esc" | "bit_image_carriage_return" | "bit_image_newline" | "bit_image_repeat" | "char_set_names" | "code_set_init" | "color_names" | "define_bit_image_region" | "device_type" | "display_pc_char" | "end_bit_image_region" | "enter_pc_charset_mode" | "enter_scancode_mode" | "exit_pc_charset_mode" | "exit_scancode_mode" | "get_mouse" | "key_mouse" | "mouse_info" | "pc_term_options" | "pkey_plab" | "req_mouse_pos" | "scancode_escape" | "set0_des_seq" | "set1_des_seq" | "set2_des_seq" | "set3_des_seq" | "set_a_background" | "set_a_foreground" | "set_color_band" | "set_lr_margin" | "set_page_length" | "set_tb_margin" | "enter_horizontal_hl_mode" | "enter_left_hl_mode" | "enter_low_hl_mode" | "enter_right_hl_mode" | "enter_top_hl_mode" | "enter_vertical_hl_mode" | "set_a_attributes" | "set_pglen_inch";
    export class $NonBlockingReader extends $Reader {
        shutdown(): void;
        read(arg0: number): number;
        available(): number;
        peek(arg0: number): number;
        readBuffered(arg0: string[]): number;
        static READ_EXPIRED: number;
        static EOF: number;
        constructor();
    }
    export class $ColorPalette {
        setDistance(arg0: string): void;
        round(arg0: number, arg1: number, arg2: number): number;
        round(arg0: number): number;
        getLength(): number;
        isReal(): boolean;
        setColor(arg0: number, arg1: number): void;
        getColor(arg0: number): number;
        canChange(): boolean;
        loadPalette(): boolean;
        getDistanceName(): string;
        static XTERM_INITC: string;
        static DEFAULT: $ColorPalette;
        constructor();
        constructor(arg0: $Terminal, arg1: string);
        constructor(arg0: $Terminal);
        set distance(value: string);
        get length(): number;
        get real(): boolean;
        get distanceName(): string;
    }
    export class $AttributedString extends $AttributedCharSequence {
        static join(arg0: $AttributedString, arg1: $Iterable_<$AttributedString>): $AttributedString;
        static join(arg0: $AttributedString, ...arg1: $AttributedString[]): $AttributedString;
        static fromAnsi(arg0: string, arg1: $List_<number>): $AttributedString;
        static fromAnsi(arg0: string, arg1: number): $AttributedString;
        static fromAnsi(arg0: string): $AttributedString;
        static stripAnsi(arg0: string): string;
        styleMatches(arg0: $Pattern, arg1: $AttributedStyle): $AttributedString;
        static NEWLINE: $AttributedString;
        static EMPTY: $AttributedString;
        static TRUE_COLORS: number;
        constructor(arg0: $CharSequence, arg1: number, arg2: number, arg3: $AttributedStyle);
        constructor(arg0: $CharSequence, arg1: $AttributedStyle);
        constructor(arg0: $CharSequence, arg1: number, arg2: number);
        constructor(arg0: $CharSequence);
    }
    export class $AttributedCharSequence$ForceMode extends $Enum<$AttributedCharSequence$ForceMode> {
        static values(): $AttributedCharSequence$ForceMode[];
        static valueOf(arg0: string): $AttributedCharSequence$ForceMode;
        static Force256Colors: $AttributedCharSequence$ForceMode;
        static None: $AttributedCharSequence$ForceMode;
        static ForceTrueColors: $AttributedCharSequence$ForceMode;
    }
    /**
     * Values that may be interpreted as {@link $AttributedCharSequence$ForceMode}.
     */
    export type $AttributedCharSequence$ForceMode_ = "none" | "force256colors" | "forcetruecolors";
    export class $AttributedCharSequence implements $CharSequence {
        println(arg0: $Terminal): void;
        isHidden(arg0: number): boolean;
        charAt(arg0: number): string;
        codePointAt(arg0: number): number;
        codePointBefore(arg0: number): number;
        codePointCount(arg0: number, arg1: number): number;
        substring(arg0: number, arg1: number): $AttributedString;
        subSequence(arg0: number, arg1: number): $AttributedString;
        contains(arg0: string): boolean;
        print(arg0: $Terminal): void;
        styleAt(arg0: number): $AttributedStyle;
        runStart(arg0: number): number;
        runLimit(arg0: number): number;
        toAnsi(arg0: number, arg1: $AttributedCharSequence$ForceMode_): string;
        toAnsi(): string;
        /**
         * @deprecated
         */
        toAnsi(arg0: number, arg1: boolean, arg2: string, arg3: string): string;
        toAnsi(arg0: $Terminal): string;
        toAnsi(arg0: number, arg1: $AttributedCharSequence$ForceMode_, arg2: $ColorPalette): string;
        toAnsi(arg0: number, arg1: $AttributedCharSequence$ForceMode_, arg2: $ColorPalette, arg3: string, arg4: string): string;
        /**
         * @deprecated
         */
        toAnsi(arg0: number, arg1: boolean): string;
        /**
         * @deprecated
         */
        static rgbColor(arg0: number): number;
        /**
         * @deprecated
         */
        static roundColor(arg0: number, arg1: number): number;
        columnLength(): number;
        /**
         * @deprecated
         */
        static roundRgbColor(arg0: number, arg1: number, arg2: number, arg3: number): number;
        columnSubSequence(arg0: number, arg1: number): $AttributedString;
        columnSplitLength(arg0: number, arg1: boolean, arg2: boolean): $List<$AttributedString>;
        columnSplitLength(arg0: number): $List<$AttributedString>;
        toAttributedString(): $AttributedString;
        isEmpty(): boolean;
        codePoints(): $IntStream;
        chars(): $IntStream;
        static TRUE_COLORS: number;
        constructor();
        get empty(): boolean;
    }
}
