import { $Level, $EntityGetter } from "@package/net/minecraft/world/level";
import { $Int2ObjectMap } from "@package/it/unimi/dsi/fastutil/ints";
import { $Codec } from "@package/com/mojang/serialization";
import { $Item$Properties, $Item } from "@package/net/minecraft/world/item";
import { $PartEntity } from "@package/net/neoforged/neoforge/entity";
import { $Mob, $Entity } from "@package/net/minecraft/world/entity";
import { $Raids } from "@package/net/minecraft/world/entity/raid";
import { $ServerLevelData, $WritableLevelData } from "@package/net/minecraft/world/level/storage";
import { $ArrayList, $HashMap, $List, $Map, $Set } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $ServerWorldCapabilities } from "@package/xaero/map/capabilities";
import { $BlockSnapshot } from "@package/net/neoforged/neoforge/common/util";
import { $BlockPos } from "@package/net/minecraft/core";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $IntProvider } from "@package/net/minecraft/util/valueproviders";
import { $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $PlacementSimulationServerLevel } from "@package/net/createmod/catnip/levelWrappers";
import { $Block } from "@package/net/minecraft/world/level/block";
import { $Object } from "@package/java/lang";
import { $TickingBlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $NeighborUpdater } from "@package/net/minecraft/world/level/redstone";
import { $EntityTickList, $PersistentEntitySectionManager } from "@package/net/minecraft/world/level/entity";
export * as zapper from "@package/com/simibubi/create/content/equipment/zapper";
export * as symmetryWand from "@package/com/simibubi/create/content/equipment/symmetryWand";
export * as potatoCannon from "@package/com/simibubi/create/content/equipment/potatoCannon";
export * as blueprint from "@package/com/simibubi/create/content/equipment/blueprint";
export * as toolbox from "@package/com/simibubi/create/content/equipment/toolbox";
export * as armor from "@package/com/simibubi/create/content/equipment/armor";
export * as hats from "@package/com/simibubi/create/content/equipment/hats";
export * as clipboard from "@package/com/simibubi/create/content/equipment/clipboard";
export * as bell from "@package/com/simibubi/create/content/equipment/bell";
export * as wrench from "@package/com/simibubi/create/content/equipment/wrench";
export * as sandPaper from "@package/com/simibubi/create/content/equipment/sandPaper";
export * as tool from "@package/com/simibubi/create/content/equipment/tool";
export * as extendoGrip from "@package/com/simibubi/create/content/equipment/extendoGrip";
export * as goggles from "@package/com/simibubi/create/content/equipment/goggles";

declare module "@package/com/simibubi/create/content/equipment" {
    export class $TreeFertilizerItem extends $Item {
        static BASE_ATTACK_DAMAGE_ID: $ResourceLocation;
        static DEFAULT_MAX_STACK_SIZE: number;
        static MAX_BAR_WIDTH: number;
        static BASE_ATTACK_SPEED_ID: $ResourceLocation;
        static ABSOLUTE_MAX_STACK_SIZE: number;
        canRepair: boolean;
        moonlight$clientAnimationProvider: $Object;
        static BY_BLOCK: $Map<$Block, $Item>;
        constructor(arg0: $Item$Properties);
    }
    export class $TreeFertilizerItem$TreesDreamWorld extends $PlacementSimulationServerLevel {
        self(): $EntityGetter;
        restoringBlockSnapshots: boolean;
        neighborUpdater: $NeighborUpdater;
        static LONG_PARTICLE_CLIP_RANGE: number;
        static RAIN_DELAY: $IntProvider;
        xaero_wm_capabilities: $ServerWorldCapabilities;
        randValue: number;
        levelData: $WritableLevelData;
        thunderLevel: number;
        random: $RandomSource;
        capturedBlockSnapshots: $ArrayList<$BlockSnapshot>;
        static MAX_ENTITY_SPAWN_Y: number;
        static NETHER: $ResourceKey<$Level>;
        pendingBlockEntityTickers: $List<$TickingBlockEntity>;
        blocksAdded: $HashMap<$BlockPos, $BlockState>;
        navigatingMobs: $Set<$Mob>;
        static MAX_BRIGHTNESS: number;
        static SHORT_PARTICLE_CLIP_RANGE: number;
        entityTickList: $EntityTickList;
        raids: $Raids;
        rainLevel: number;
        dragonParts: $Int2ObjectMap<$PartEntity<never>>;
        oThunderLevel: number;
        static THUNDER_DURATION: $IntProvider;
        serverLevelData: $ServerLevelData;
        static RAIN_DURATION: $IntProvider;
        players: $List<$ServerPlayer>;
        static $assertionsDisabled: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        isUpdatingNavigations: boolean;
        addend: number;
        entityManager: $PersistentEntitySectionManager<$Entity>;
        static OVERWORLD: $ResourceKey<$Level>;
        static TICKS_PER_DAY: number;
        oRainLevel: number;
        static END_SPAWN_POINT: $BlockPos;
        static RESOURCE_KEY_CODEC: $Codec<$ResourceKey<$Level>>;
        static END: $ResourceKey<$Level>;
        static MAX_LEVEL_SIZE: number;
        static MIN_ENTITY_SPAWN_Y: number;
        blockEntityTickers: $List<$TickingBlockEntity>;
        captureBlockSnapshots: boolean;
    }
    export class $BuildersTeaItem extends $Item {
        static BASE_ATTACK_DAMAGE_ID: $ResourceLocation;
        static DEFAULT_MAX_STACK_SIZE: number;
        static MAX_BAR_WIDTH: number;
        static BASE_ATTACK_SPEED_ID: $ResourceLocation;
        static ABSOLUTE_MAX_STACK_SIZE: number;
        canRepair: boolean;
        moonlight$clientAnimationProvider: $Object;
        static BY_BLOCK: $Map<$Block, $Item>;
        constructor(arg0: $Item$Properties);
    }
}
