import { $Serializable } from "@package/java/io";
import { $StandardLevel } from "@package/org/apache/logging/log4j/spi";
import { $MessageSupplier_, $Supplier_ } from "@package/org/apache/logging/log4j/util";
import { $Comparable, $Object, $StackTraceElement, $Throwable, $CharSequence, $Enum, $Class } from "@package/java/lang";
import { $FlowMessageFactory, $MessageFactory, $Message, $EntryMessage } from "@package/org/apache/logging/log4j/message";
export * as message from "@package/org/apache/logging/log4j/message";
export * as util from "@package/org/apache/logging/log4j/util";
export * as spi from "@package/org/apache/logging/log4j/spi";

declare module "@package/org/apache/logging/log4j" {
    export class $LogBuilder {
        static NOOP: $LogBuilder;
    }
    export interface $LogBuilder {
        log(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        log(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        log(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        log(message: string, p0: $Object, p1: $Object, p2: $Object): void;
        log(message: string, p0: $Object, p1: $Object): void;
        log(message: string, p0: $Object): void;
        log(): void;
        log(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        log(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        log(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        log(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        log(message: string, ...params: $Supplier_<never>[]): void;
        log(message: string, ...params: $Object[]): void;
        log(message: string): void;
        log(message: $CharSequence): void;
        log(message: $Message): void;
        log(messageSupplier: $Supplier_<$Message>): void;
        log(message: $Object): void;
        logAndGet(messageSupplier: $Supplier_<$Message>): $Message;
        withMarker(marker: $Marker): $LogBuilder;
        withLocation(): $LogBuilder;
        withLocation(location: $StackTraceElement): $LogBuilder;
        withThrowable(throwable: $Throwable): $LogBuilder;
    }
    export class $Logger {
    }
    export interface $Logger {
        getName(): string;
        /**
         * @deprecated
         */
        exit<R>(result: R): R;
        /**
         * @deprecated
         */
        exit(): void;
        log(level: $Level, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        log(level: $Level, messageSupplier: $Supplier_<never>): void;
        log(level: $Level, message: string, throwable: $Throwable): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object): void;
        log(level: $Level, message: $Object): void;
        log(level: $Level, message: $Object, throwable: $Throwable): void;
        log(level: $Level, message: string): void;
        log(level: $Level, message: string, ...params: $Object[]): void;
        log(level: $Level, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        log(level: $Level, message: string, p0: $Object): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        log(level: $Level, marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        log(level: $Level, marker: $Marker, message: $CharSequence, throwable: $Throwable): void;
        log(level: $Level, marker: $Marker, message: $Object): void;
        log(level: $Level, marker: $Marker, message: $Object, throwable: $Throwable): void;
        log(level: $Level, marker: $Marker, message: string, ...params: $Object[]): void;
        log(level: $Level, marker: $Marker, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        log(level: $Level, marker: $Marker, message: $Message): void;
        log(level: $Level, marker: $Marker, message: $Message, throwable: $Throwable): void;
        log(level: $Level, marker: $Marker, messageSupplier: $MessageSupplier_): void;
        log(level: $Level, marker: $Marker, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        log(level: $Level, marker: $Marker, message: $CharSequence): void;
        log(level: $Level, message: $Message, throwable: $Throwable): void;
        log(level: $Level, messageSupplier: $MessageSupplier_): void;
        log(level: $Level, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        log(level: $Level, message: $CharSequence): void;
        log(level: $Level, message: $CharSequence, throwable: $Throwable): void;
        log(level: $Level, marker: $Marker, message: string, throwable: $Throwable): void;
        log(level: $Level, marker: $Marker, messageSupplier: $Supplier_<never>): void;
        log(level: $Level, marker: $Marker, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        log(level: $Level, message: $Message): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        log(level: $Level, marker: $Marker, message: string): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        log(level: $Level, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        isEnabled(level: $Level): boolean;
        isEnabled(level: $Level, marker: $Marker): boolean;
        info(marker: $Marker, message: $CharSequence, throwable: $Throwable): void;
        info(marker: $Marker, message: $CharSequence): void;
        info(marker: $Marker, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        info(marker: $Marker, messageSupplier: $MessageSupplier_): void;
        info(marker: $Marker, message: $Message, throwable: $Throwable): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        info(marker: $Marker, message: string, ...params: $Object[]): void;
        info(marker: $Marker, message: string): void;
        info(marker: $Marker, message: $Object, throwable: $Throwable): void;
        info(marker: $Marker, message: $Object): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        info(marker: $Marker, message: $Message): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        info(message: string, p0: $Object, p1: $Object): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        info(messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        info(messageSupplier: $Supplier_<never>): void;
        info(message: string, throwable: $Throwable): void;
        info(message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        info(message: string, ...params: $Object[]): void;
        info(message: string): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        info(marker: $Marker, message: string, p0: $Object, p1: $Object): void;
        info(marker: $Marker, message: string, p0: $Object): void;
        info(message: $Message, throwable: $Throwable): void;
        info(message: $Message): void;
        info(marker: $Marker, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        info(marker: $Marker, messageSupplier: $Supplier_<never>): void;
        info(marker: $Marker, message: string, throwable: $Throwable): void;
        info(marker: $Marker, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        info(message: $Object, throwable: $Throwable): void;
        info(message: $Object): void;
        info(message: $CharSequence, throwable: $Throwable): void;
        info(message: $CharSequence): void;
        info(messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        info(messageSupplier: $MessageSupplier_): void;
        info(message: string, p0: $Object): void;
        info(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        printf(level: $Level, format: string, ...params: $Object[]): void;
        printf(level: $Level, marker: $Marker, format: string, ...params: $Object[]): void;
        /**
         * @deprecated
         */
        entry(): void;
        /**
         * @deprecated
         */
        entry(...params: $Object[]): void;
        trace(marker: $Marker, message: string, throwable: $Throwable): void;
        trace(message: $CharSequence, throwable: $Throwable): void;
        trace(message: $CharSequence): void;
        trace(marker: $Marker, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        trace(messageSupplier: $MessageSupplier_): void;
        trace(marker: $Marker, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        trace(message: $Message): void;
        trace(message: $Message, throwable: $Throwable): void;
        trace(marker: $Marker, messageSupplier: $Supplier_<never>): void;
        trace(messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        trace(marker: $Marker, message: string, p0: $Object): void;
        trace(messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        trace(messageSupplier: $Supplier_<never>): void;
        trace(message: string, throwable: $Throwable): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        trace(message: $Object): void;
        trace(message: $Object, throwable: $Throwable): void;
        trace(message: string): void;
        trace(message: string, ...params: $Object[]): void;
        trace(message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object): void;
        trace(message: string, p0: $Object, p1: $Object): void;
        trace(message: string, p0: $Object): void;
        trace(marker: $Marker, message: $CharSequence): void;
        trace(marker: $Marker, message: $CharSequence, throwable: $Throwable): void;
        trace(marker: $Marker, message: $Object): void;
        trace(marker: $Marker, message: $Object, throwable: $Throwable): void;
        trace(marker: $Marker, message: string): void;
        trace(marker: $Marker, message: string, ...params: $Object[]): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        trace(marker: $Marker, message: $Message): void;
        trace(marker: $Marker, message: $Message, throwable: $Throwable): void;
        trace(marker: $Marker, messageSupplier: $MessageSupplier_): void;
        trace(marker: $Marker, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        trace(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        trace(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        debug(message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        debug(message: string, throwable: $Throwable): void;
        debug(messageSupplier: $Supplier_<never>): void;
        debug(messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        debug(marker: $Marker, message: string, p0: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        debug(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        debug(message: string, p0: $Object): void;
        debug(message: string, p0: $Object, p1: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object): void;
        debug(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        debug(marker: $Marker, message: $Object): void;
        debug(marker: $Marker, message: $Object, throwable: $Throwable): void;
        debug(marker: $Marker, message: string): void;
        debug(marker: $Marker, message: string, ...params: $Object[]): void;
        debug(marker: $Marker, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        debug(marker: $Marker, message: string, throwable: $Throwable): void;
        debug(marker: $Marker, message: $Message): void;
        debug(marker: $Marker, message: $Message, throwable: $Throwable): void;
        debug(marker: $Marker, messageSupplier: $MessageSupplier_): void;
        debug(marker: $Marker, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        debug(marker: $Marker, message: $CharSequence): void;
        debug(marker: $Marker, message: $CharSequence, throwable: $Throwable): void;
        debug(message: $CharSequence): void;
        debug(message: $CharSequence, throwable: $Throwable): void;
        debug(message: $Object): void;
        debug(message: $Object, throwable: $Throwable): void;
        debug(message: string): void;
        debug(message: string, ...params: $Object[]): void;
        debug(marker: $Marker, messageSupplier: $Supplier_<never>): void;
        debug(marker: $Marker, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        debug(message: $Message): void;
        debug(messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        debug(messageSupplier: $MessageSupplier_): void;
        debug(message: $Message, throwable: $Throwable): void;
        error(message: $Message, throwable: $Throwable): void;
        error(messageSupplier: $MessageSupplier_): void;
        error(messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        error(message: $Message): void;
        error(marker: $Marker, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        error(marker: $Marker, messageSupplier: $Supplier_<never>): void;
        error(message: string, ...params: $Object[]): void;
        error(message: string): void;
        error(message: $Object, throwable: $Throwable): void;
        error(message: $Object): void;
        error(message: $CharSequence, throwable: $Throwable): void;
        error(message: $CharSequence): void;
        error(marker: $Marker, message: $CharSequence, throwable: $Throwable): void;
        error(marker: $Marker, message: $CharSequence): void;
        error(marker: $Marker, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        error(marker: $Marker, messageSupplier: $MessageSupplier_): void;
        error(marker: $Marker, message: $Message, throwable: $Throwable): void;
        error(marker: $Marker, message: $Message): void;
        error(marker: $Marker, message: string, throwable: $Throwable): void;
        error(marker: $Marker, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        error(marker: $Marker, message: string, ...params: $Object[]): void;
        error(marker: $Marker, message: string): void;
        error(marker: $Marker, message: $Object, throwable: $Throwable): void;
        error(marker: $Marker, message: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object): void;
        error(message: string, p0: $Object, p1: $Object): void;
        error(message: string, p0: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        error(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object): void;
        error(marker: $Marker, message: string, p0: $Object): void;
        error(messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        error(messageSupplier: $Supplier_<never>): void;
        error(message: string, throwable: $Throwable): void;
        error(message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        error(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        warn(message: $Message): void;
        warn(message: $Message, throwable: $Throwable): void;
        warn(messageSupplier: $MessageSupplier_): void;
        warn(messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        warn(marker: $Marker, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        warn(marker: $Marker, messageSupplier: $Supplier_<never>): void;
        warn(marker: $Marker, message: string, throwable: $Throwable): void;
        warn(message: string, ...params: $Object[]): void;
        warn(message: string): void;
        warn(message: $Object, throwable: $Throwable): void;
        warn(message: $Object): void;
        warn(message: $CharSequence, throwable: $Throwable): void;
        warn(message: $CharSequence): void;
        warn(marker: $Marker, message: $CharSequence): void;
        warn(marker: $Marker, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        warn(marker: $Marker, messageSupplier: $MessageSupplier_): void;
        warn(marker: $Marker, message: $Message, throwable: $Throwable): void;
        warn(marker: $Marker, message: $Message): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        warn(marker: $Marker, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        warn(marker: $Marker, message: string, ...params: $Object[]): void;
        warn(marker: $Marker, message: string): void;
        warn(marker: $Marker, message: $Object, throwable: $Throwable): void;
        warn(marker: $Marker, message: $Object): void;
        warn(marker: $Marker, message: $CharSequence, throwable: $Throwable): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        warn(message: string, p0: $Object): void;
        warn(message: string, p0: $Object, p1: $Object): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        warn(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object): void;
        warn(messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        warn(messageSupplier: $Supplier_<never>): void;
        warn(message: string, throwable: $Throwable): void;
        warn(message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        warn(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        getLevel(): $Level;
        throwing<T extends $Throwable>(level: $Level, throwable: T): T;
        throwing<T extends $Throwable>(throwable: T): T;
        catching(level: $Level, throwable: $Throwable): void;
        catching(throwable: $Throwable): void;
        logMessage(level: $Level, marker: $Marker, fqcn: string, location: $StackTraceElement, message: $Message, throwable: $Throwable): void;
        atWarn(): $LogBuilder;
        traceEntry(...paramSuppliers: $Supplier_<never>[]): $EntryMessage;
        traceEntry(format: string, ...params: $Object[]): $EntryMessage;
        traceEntry(format: string, ...paramSuppliers: $Supplier_<never>[]): $EntryMessage;
        traceEntry(): $EntryMessage;
        traceEntry(message: $Message): $EntryMessage;
        atError(): $LogBuilder;
        atTrace(): $LogBuilder;
        atDebug(): $LogBuilder;
        atFatal(): $LogBuilder;
        fatal(message: string, throwable: $Throwable): void;
        fatal(message: $CharSequence, throwable: $Throwable): void;
        fatal(message: $Object, throwable: $Throwable): void;
        fatal(message: $Object): void;
        fatal(message: string): void;
        fatal(message: string, ...params: $Object[]): void;
        fatal(message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object): void;
        fatal(marker: $Marker, message: $CharSequence): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        fatal(marker: $Marker, message: string, p0: $Object): void;
        fatal(messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        fatal(messageSupplier: $Supplier_<never>): void;
        fatal(marker: $Marker, message: string, ...params: $Object[]): void;
        fatal(marker: $Marker, message: string, ...paramSuppliers: $Supplier_<never>[]): void;
        fatal(marker: $Marker, message: string, throwable: $Throwable): void;
        fatal(marker: $Marker, messageSupplier: $Supplier_<never>): void;
        fatal(marker: $Marker, message: string): void;
        fatal(marker: $Marker, message: $Object, throwable: $Throwable): void;
        fatal(marker: $Marker, message: $Object): void;
        fatal(message: $Message, throwable: $Throwable): void;
        fatal(messageSupplier: $MessageSupplier_): void;
        fatal(messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        fatal(message: $CharSequence): void;
        fatal(message: $Message): void;
        fatal(marker: $Marker, messageSupplier: $Supplier_<never>, throwable: $Throwable): void;
        fatal(marker: $Marker, message: $CharSequence, throwable: $Throwable): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        fatal(marker: $Marker, message: $Message): void;
        fatal(marker: $Marker, message: $Message, throwable: $Throwable): void;
        fatal(marker: $Marker, messageSupplier: $MessageSupplier_): void;
        fatal(marker: $Marker, messageSupplier: $MessageSupplier_, throwable: $Throwable): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object, p9: $Object): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object): void;
        fatal(marker: $Marker, message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object, p5: $Object, p6: $Object, p7: $Object, p8: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object, p4: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object, p3: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object, p2: $Object): void;
        fatal(message: string, p0: $Object, p1: $Object): void;
        fatal(message: string, p0: $Object): void;
        traceExit<R>(message: $Message, result: R): R;
        traceExit<R>(message: $EntryMessage, result: R): R;
        traceExit(message: $EntryMessage): void;
        traceExit<R>(format: string, result: R): R;
        traceExit(): void;
        traceExit<R>(result: R): R;
        atInfo(): $LogBuilder;
        always(): $LogBuilder;
        atLevel(level: $Level): $LogBuilder;
        getFlowMessageFactory(): $FlowMessageFactory;
        isWarnEnabled(): boolean;
        isWarnEnabled(marker: $Marker): boolean;
        isTraceEnabled(marker: $Marker): boolean;
        isTraceEnabled(): boolean;
        isInfoEnabled(marker: $Marker): boolean;
        isInfoEnabled(): boolean;
        getMessageFactory<MF extends $MessageFactory>(): MF;
        isDebugEnabled(marker: $Marker): boolean;
        isDebugEnabled(): boolean;
        isErrorEnabled(): boolean;
        isErrorEnabled(marker: $Marker): boolean;
        isFatalEnabled(): boolean;
        isFatalEnabled(marker: $Marker): boolean;
        get name(): string;
        get level(): $Level;
        get flowMessageFactory(): $FlowMessageFactory;
        get messageFactory(): MF;
    }
    export class $Level implements $Comparable<$Level>, $Serializable {
        name(): string;
        static forName(name: string, intValue: number): $Level;
        static values(): $Level[];
        clone(): $Level;
        compareTo(other: $Level): number;
        static valueOf(name: string): $Level;
        static valueOf<T extends $Enum<T>>(enumType: $Class<T>, name: string): T;
        getDeclaringClass(): $Class<$Level>;
        static getLevel(name: string): $Level;
        isInRange(minLevel: $Level, maxLevel: $Level): boolean;
        static toLevel(name: string, defaultLevel: $Level): $Level;
        static toLevel(level: string): $Level;
        intLevel(): number;
        isMoreSpecificThan(level: $Level): boolean;
        getStandardLevel(): $StandardLevel;
        isLessSpecificThan(level: $Level): boolean;
        static TRACE: $Level;
        static ALL: $Level;
        static CATEGORY: string;
        static ERROR: $Level;
        static INFO: $Level;
        static FATAL: $Level;
        static DEBUG: $Level;
        static OFF: $Level;
        static WARN: $Level;
        get declaringClass(): $Class<$Level>;
        get standardLevel(): $StandardLevel;
    }
    export class $Marker {
    }
    export interface $Marker extends $Serializable {
        getName(): string;
        remove(marker: $Marker): boolean;
        equals(obj: $Object): boolean;
        hashCode(): number;
        setParents(...markers: $Marker[]): $Marker;
        hasParents(): boolean;
        getParents(): $Marker[];
        addParents(...markers: $Marker[]): $Marker;
        isInstanceOf(name: string): boolean;
        isInstanceOf(m: $Marker): boolean;
        get name(): string;
    }
}
