import { $ILightingSettings, $TextureSheetSegment } from "@package/net/createmod/catnip/gui";
import { $ItemStack_ } from "@package/net/minecraft/world/item";
import { $MultiBufferSource_ } from "@package/net/minecraft/client/renderer";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $FormattedText } from "@package/net/minecraft/network/chat";
import { $AbstractWidget, $EditBox } from "@package/net/minecraft/client/gui/components";
import { $List_ } from "@package/java/util";
import { $ScrollInput, $TooltipArea, $Label, $SelectionScrollInput } from "@package/com/simibubi/create/foundation/gui/widget";
import { $Consumer_, $BiConsumer_ } from "@package/java/util/function";
import { $ResourceLocation } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $DelegatedStencilElement, $ScreenElement } from "@package/net/createmod/catnip/gui/element";
import { $Color } from "@package/net/createmod/catnip/theme";
import { $Enum } from "@package/java/lang";
import { $Font, $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $GuiEventListener } from "@package/net/minecraft/client/gui/components/events";
import { $Pair } from "@package/net/createmod/catnip/data";
export * as menu from "@package/com/simibubi/create/foundation/gui/menu";
export * as widget from "@package/com/simibubi/create/foundation/gui/widget";

declare module "@package/com/simibubi/create/foundation/gui" {
    export class $CustomLightingSettings$Builder {
        build(): $CustomLightingSettings;
        doubleLight(): $CustomLightingSettings$Builder;
        firstLightRotation(arg0: number, arg1: number): $CustomLightingSettings$Builder;
        secondLightRotation(arg0: number, arg1: number): $CustomLightingSettings$Builder;
        constructor();
    }
    export class $AllGuiTextures extends $Enum<$AllGuiTextures> implements $ScreenElement, $TextureSheetSegment {
        getHeight(): number;
        static values(): $AllGuiTextures[];
        static valueOf(arg0: string): $AllGuiTextures;
        getLocation(): $ResourceLocation;
        getWidth(): number;
        render(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: $Color): void;
        render(arg0: $GuiGraphics, arg1: number, arg2: number): void;
        getStartY(): number;
        getStartX(): number;
        bind(): void;
        static FROGPORT_HEADER: $AllGuiTextures;
        static CURSEFORGE_LOGO: $AllGuiTextures;
        static THRESHOLD_SWITCH: $AllGuiTextures;
        static TRADE_OVERLAY: $AllGuiTextures;
        static STATION_TEXTBOX_BOTTOM: $AllGuiTextures;
        static WAND_OF_SYMMETRY: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY: $AllGuiTextures;
        static JEI_SHADOW: $AllGuiTextures;
        static FONT_COLOR: number;
        static SCHEDULE_EDITOR_ADDITIONAL_SLOT: $AllGuiTextures;
        static STOCK_KEEPER_SEARCH_SYNC_FROM_JEI: $AllGuiTextures;
        static DATA_AREA: $AllGuiTextures;
        static BRASS_FRAME_TR: $AllGuiTextures;
        static BRASS_FRAME_TL: $AllGuiTextures;
        static JEI_ARROW: $AllGuiTextures;
        static VALUE_SETTINGS_MILESTONE: $AllGuiTextures;
        static JEI_SLOT: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SCROLL_TOP: $AllGuiTextures;
        static TRAIN_HUD_SPEED_BG: $AllGuiTextures;
        static SCHEDULE_EDITOR_INACTIVE_SLOT: $AllGuiTextures;
        static SCHEDULE_POINTER_OFFSCREEN: $AllGuiTextures;
        static TRAINMAP_SIGNAL: $AllGuiTextures;
        static HOTSLOT_ARROW_BAD: $AllGuiTextures;
        static SCHEDULE_CARD_MOVE_UP: $AllGuiTextures;
        static REDSTONE_REQUESTER: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_HEADER: $AllGuiTextures;
        static BUTTON: $AllGuiTextures;
        static INDICATOR: $AllGuiTextures;
        static STATION_TEXTBOX_TOP: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SAYS: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BLUEPRINT_RIGHT: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_HIDDEN: $AllGuiTextures;
        static SCHEDULE_CARD_MEDIUM: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_UP: $AllGuiTextures;
        static SCHEMATIC_SLOT: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BLUEPRINT_MIDDLE: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_DOWN: $AllGuiTextures;
        static HOTSLOT_ACTIVE: $AllGuiTextures;
        static SCHEDULE_CONDITION_RIGHT: $AllGuiTextures;
        static STOCK_KEEPER_SEARCH_SYNC_DISABLED: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_FOOTER: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SLOT: $AllGuiTextures;
        static ATTRIBUTE_FILTER: $AllGuiTextures;
        static INDICATOR_GREEN: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BANNER_M: $AllGuiTextures;
        static JEI_LIGHT: $AllGuiTextures;
        static JEI_DOWN_ARROW: $AllGuiTextures;
        static INDICATOR_WHITE: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BANNER_L: $AllGuiTextures;
        static INDICATOR_RED: $AllGuiTextures;
        static THRESHOLD_SWITCH_CURRENT_STATE: $AllGuiTextures;
        static TRAINMAP_TOGGLE_OFF: $AllGuiTextures;
        static SCHEDULE_CONDITION_ITEM: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BANNER_R: $AllGuiTextures;
        static SCHEDULE_STRIP_ACTION: $AllGuiTextures;
        static BUTTON_GREEN: $AllGuiTextures;
        static TOOLBELT_SLOT_HIGHLIGHT: $AllGuiTextures;
        static SCHEMATICANNON_CHECKLIST_PROGRESS: $AllGuiTextures;
        static FROGPORT_BG: $AllGuiTextures;
        static PLACEMENT_INDICATOR_SHEET: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SEARCH: $AllGuiTextures;
        static SCHEDULE_CARD_NEW: $AllGuiTextures;
        static SCHEDULE_STRIP_END: $AllGuiTextures;
        static STATION: $AllGuiTextures;
        static JEI_CATALYST_SLOT: $AllGuiTextures;
        static SCHEDULE_CONDITION_LEFT_CLEAN: $AllGuiTextures;
        static VALUE_SETTINGS_BAR: $AllGuiTextures;
        static BUTTON_DOWN: $AllGuiTextures;
        static STATION_TEXTBOX_SPEECH: $AllGuiTextures;
        static JEI_NO_HEAT_BAR: $AllGuiTextures;
        static FACTORY_GAUGE_RECIPE: $AllGuiTextures;
        static TRAIN_HUD_SPEED: $AllGuiTextures;
        static TRAINMAP_STATION_ORTHO_HIGHLIGHT: $AllGuiTextures;
        static VALUE_SETTINGS_CURSOR: $AllGuiTextures;
        static SCHEMATICANNON_FUEL: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_ENTRY: $AllGuiTextures;
        static STATION_ASSEMBLING: $AllGuiTextures;
        static DATA_AREA_START: $AllGuiTextures;
        static SCHEDULE_CARD_MOVE_DOWN: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_LOCKED: $AllGuiTextures;
        static PACKAGE_FILTER: $AllGuiTextures;
        static SCHEMATIC_TABLE_PROGRESS: $AllGuiTextures;
        static FILTER: $AllGuiTextures;
        static HUD_BACKGROUND: $AllGuiTextures;
        static SCHEDULE_SCROLL_RIGHT: $AllGuiTextures;
        static THRESHOLD_SWITCH_ITEMCOUNT_INPUTS: $AllGuiTextures;
        static FACTORY_GAUGE_SET_ITEM: $AllGuiTextures;
        static BUTTON_HOVER: $AllGuiTextures;
        static FACTORY_GAUGE_BOTTOM: $AllGuiTextures;
        static SCHEDULE_CARD_REMOVE: $AllGuiTextures;
        static SCHEDULE_CONDITION_MIDDLE: $AllGuiTextures;
        location: $ResourceLocation;
        static SCHEDULE_STRIP_DARK: $AllGuiTextures;
        static CLIPBOARD_ADDRESS: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SCROLL_PAD: $AllGuiTextures;
        static SCHEDULE_STRIP_WAIT: $AllGuiTextures;
        static SEQUENCER: $AllGuiTextures;
        static SCHEDULE_STRIP_LIGHT: $AllGuiTextures;
        static SCHEDULE_EDITOR: $AllGuiTextures;
        static BRASS_FRAME_LEFT: $AllGuiTextures;
        static TERRAINZAPPER: $AllGuiTextures;
        static INDICATOR_YELLOW: $AllGuiTextures;
        static STATION_EDIT_NAME: $AllGuiTextures;
        static BRASS_FRAME_TOP: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SCROLL_MID: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BG: $AllGuiTextures;
        static JEI_QUESTION_MARK: $AllGuiTextures;
        static SCHEDULE_SCROLL_LEFT: $AllGuiTextures;
        static STATION_TEXTBOX_MIDDLE: $AllGuiTextures;
        static TOOLBELT_INACTIVE_SLOT: $AllGuiTextures;
        static VALUE_SETTINGS_CURSOR_ICON: $AllGuiTextures;
        static SCHEDULE_POINTER: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_HEADER: $AllGuiTextures;
        static SCHEMATIC_TABLE: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BLUEPRINT_LEFT: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_FOOTER: $AllGuiTextures;
        static VALUE_SETTINGS_BAR_BG: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_UNLOCKED: $AllGuiTextures;
        static MODRINTH_LOGO: $AllGuiTextures;
        static VALUE_SETTINGS_LABEL_BG: $AllGuiTextures;
        static BLUEPRINT: $AllGuiTextures;
        static SPEECH_TOOLTIP_BACKGROUND: $AllGuiTextures;
        static BUTTON_DISABLED: $AllGuiTextures;
        static POSTBOX_HEADER: $AllGuiTextures;
        static SCHEMATICANNON_TOP: $AllGuiTextures;
        static SCHEMATICANNON_FUEL_CREATIVE: $AllGuiTextures;
        static SCHEDULE_STRIP_TRAVEL: $AllGuiTextures;
        static SCHEDULE_CONDITION_APPEND: $AllGuiTextures;
        static TRAINMAP_SPRITES: $AllGuiTextures;
        static SCHEDULE_CONDITION_LEFT: $AllGuiTextures;
        static I_ASSEMBLE_TRAIN: $AllGuiTextures;
        static TRAIN_HUD_FRAME: $AllGuiTextures;
        static TERRAINZAPPER_INACTIVE_PARAM: $AllGuiTextures;
        static STOCK_KEEPER_SEARCH_SYNC_BOTH: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_SHOWN: $AllGuiTextures;
        static TOOLBELT_EMPTY_SLOT: $AllGuiTextures;
        static TRAIN_PROMPT: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_NEW: $AllGuiTextures;
        static TRAIN_HUD_THROTTLE: $AllGuiTextures;
        static TOOLBELT_SELECTED_ON: $AllGuiTextures;
        static SCHEMATIC_TITLE: $AllGuiTextures;
        static TOOLBELT_SLOT: $AllGuiTextures;
        static VALUE_SETTINGS_CURSOR_LEFT: $AllGuiTextures;
        static DATA_AREA_SPEECH: $AllGuiTextures;
        static VALUE_SETTINGS_OUTER_BG: $AllGuiTextures;
        static JEI_CHANCE_SLOT: $AllGuiTextures;
        static LOGO: $AllGuiTextures;
        static DATA_GATHERER: $AllGuiTextures;
        static TRAIN_PROMPT_R: $AllGuiTextures;
        static TRAINMAP_TOGGLE_ON: $AllGuiTextures;
        static SPEECH_TOOLTIP_COLOR: $AllGuiTextures;
        static TRAIN_PROMPT_L: $AllGuiTextures;
        static TOOLBELT_SELECTED_OFF: $AllGuiTextures;
        static BLOCKZAPPER: $AllGuiTextures;
        static I_DISASSEMBLE_TRAIN: $AllGuiTextures;
        static DATA_AREA_END: $AllGuiTextures;
        static SCHEMATICANNON_HIGHLIGHT: $AllGuiTextures;
        static SCHEDULE: $AllGuiTextures;
        static STOCK_KEEPER_SEARCH_SYNC_FROM_STOCK_KEEPER: $AllGuiTextures;
        static THRESHOLD_SWITCH_MISC_INPUTS: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_BODY: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SCROLL_BOT: $AllGuiTextures;
        static SCHEDULE_CARD_DUPLICATE: $AllGuiTextures;
        static ELEVATOR_CONTACT: $AllGuiTextures;
        static BLOCKZAPPER_UPGRADE_RECIPE: $AllGuiTextures;
        static LINKED_CONTROLLER: $AllGuiTextures;
        static NUMBERS: $AllGuiTextures;
        static SCHEMATIC_PROMPT: $AllGuiTextures;
        static VALUE_SETTINGS_CURSOR_RIGHT: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_SAYS: $AllGuiTextures;
        static TRAIN_HUD_THROTTLE_POINTER: $AllGuiTextures;
        static SCHEDULE_CARD_DARK: $AllGuiTextures;
        static TRAINMAP_TOGGLE_PANEL: $AllGuiTextures;
        static TRAINMAP_STATION_ORTHO: $AllGuiTextures;
        static SCHEDULE_STRIP_DOTTED: $AllGuiTextures;
        static JEI_HEAT_BAR: $AllGuiTextures;
        static SEQUENCER_AWAIT: $AllGuiTextures;
        static FACTORY_GAUGE_RESTOCK: $AllGuiTextures;
        static FROGPORT_EDIT_NAME: $AllGuiTextures;
        static TRAINMAP_STATION_DIAGO: $AllGuiTextures;
        static BRASS_FRAME_BOTTOM: $AllGuiTextures;
        static STOCK_KEEPER_CATEGORY_EDIT: $AllGuiTextures;
        static TOOLBOX: $AllGuiTextures;
        static CLIPBOARD: $AllGuiTextures;
        static BRASS_FRAME_BR: $AllGuiTextures;
        static CLIPBOARD_ADDRESS_INACTIVE: $AllGuiTextures;
        static SCHEDULE_CARD_LIGHT: $AllGuiTextures;
        static HOTSLOT_SUPER_ACTIVE: $AllGuiTextures;
        static SEQUENCER_INSTRUCTION: $AllGuiTextures;
        static SCHEDULE_CONDITION_NEW: $AllGuiTextures;
        static STOCK_KEEPER_REQUEST_SEND_HOVER: $AllGuiTextures;
        static I_NEW_TRAIN: $AllGuiTextures;
        static SCHEMATIC: $AllGuiTextures;
        static BRASS_FRAME_RIGHT: $AllGuiTextures;
        static SEQUENCER_EMPTY: $AllGuiTextures;
        static SCHEMATICANNON_BOTTOM: $AllGuiTextures;
        static FROGPORT_SLOT: $AllGuiTextures;
        static BRASS_FRAME_BL: $AllGuiTextures;
        static SEQUENCER_DELAY: $AllGuiTextures;
        static VALUE_SETTINGS_WIDE_MILESTONE: $AllGuiTextures;
        static HOTSLOT_ARROW: $AllGuiTextures;
        static STATION_EDIT_TRAIN_NAME: $AllGuiTextures;
        static TOOLBELT_HOTBAR_ON: $AllGuiTextures;
        static SCHEMATICANNON_PROGRESS: $AllGuiTextures;
        static TRAIN_HUD_DIRECTION: $AllGuiTextures;
        static TOOLBELT_MAIN_SLOT: $AllGuiTextures;
        static SEQUENCER_END: $AllGuiTextures;
        static TRAINMAP_STATION_DIAGO_HIGHLIGHT: $AllGuiTextures;
        static COMPUTER: $AllGuiTextures;
        static JEI_LONG_ARROW: $AllGuiTextures;
        static PLAYER_INVENTORY: $AllGuiTextures;
        static HOTSLOT: $AllGuiTextures;
        static TOOLBELT_HOTBAR_OFF: $AllGuiTextures;
        get height(): number;
        get width(): number;
        get startY(): number;
        get startX(): number;
    }
    /**
     * Values that may be interpreted as {@link $AllGuiTextures}.
     */
    export type $AllGuiTextures_ = "player_inventory" | "wand_of_symmetry" | "blockzapper" | "terrainzapper" | "terrainzapper_inactive_param" | "logo" | "curseforge_logo" | "modrinth_logo" | "schematic" | "schematic_title" | "schematic_slot" | "schematic_prompt" | "hud_background" | "schematic_table" | "schematic_table_progress" | "schematicannon_top" | "schematicannon_bottom" | "schematicannon_progress" | "schematicannon_checklist_progress" | "schematicannon_highlight" | "schematicannon_fuel" | "schematicannon_fuel_creative" | "threshold_switch" | "threshold_switch_itemcount_inputs" | "threshold_switch_misc_inputs" | "threshold_switch_current_state" | "filter" | "attribute_filter" | "package_filter" | "postbox_header" | "frogport_header" | "frogport_slot" | "frogport_edit_name" | "frogport_bg" | "toolbox" | "toolbelt_slot" | "toolbelt_slot_highlight" | "toolbelt_main_slot" | "toolbelt_empty_slot" | "toolbelt_inactive_slot" | "toolbelt_hotbar_off" | "toolbelt_hotbar_on" | "toolbelt_selected_off" | "toolbelt_selected_on" | "sequencer" | "sequencer_instruction" | "sequencer_delay" | "sequencer_end" | "sequencer_empty" | "sequencer_await" | "linked_controller" | "blueprint" | "clipboard" | "clipboard_address" | "clipboard_address_inactive" | "data_gatherer" | "data_area_start" | "data_area_speech" | "data_area" | "data_area_end" | "schedule" | "schedule_card_dark" | "schedule_card_medium" | "schedule_card_light" | "schedule_card_move_up" | "schedule_card_move_down" | "schedule_card_remove" | "schedule_card_duplicate" | "schedule_card_new" | "schedule_condition_new" | "schedule_condition_left" | "schedule_condition_left_clean" | "schedule_condition_middle" | "schedule_condition_item" | "schedule_condition_right" | "schedule_condition_append" | "schedule_scroll_left" | "schedule_scroll_right" | "schedule_strip_dark" | "schedule_strip_light" | "schedule_strip_wait" | "schedule_strip_travel" | "schedule_strip_dotted" | "schedule_strip_end" | "schedule_strip_action" | "schedule_editor" | "schedule_editor_additional_slot" | "schedule_editor_inactive_slot" | "schedule_pointer" | "schedule_pointer_offscreen" | "station" | "station_assembling" | "station_textbox_top" | "station_textbox_middle" | "station_textbox_bottom" | "station_textbox_speech" | "station_edit_name" | "station_edit_train_name" | "i_new_train" | "i_disassemble_train" | "i_assemble_train" | "elevator_contact" | "brass_frame_tl" | "brass_frame_tr" | "brass_frame_bl" | "brass_frame_br" | "brass_frame_left" | "brass_frame_right" | "brass_frame_top" | "brass_frame_bottom" | "value_settings_milestone" | "value_settings_wide_milestone" | "value_settings_bar" | "value_settings_bar_bg" | "value_settings_outer_bg" | "value_settings_cursor_left" | "value_settings_cursor" | "value_settings_cursor_right" | "value_settings_cursor_icon" | "value_settings_label_bg" | "factory_gauge_recipe" | "factory_gauge_restock" | "factory_gauge_bottom" | "factory_gauge_set_item" | "stock_keeper_request_header" | "stock_keeper_request_body" | "stock_keeper_request_footer" | "stock_keeper_request_search" | "stock_keeper_request_says" | "stock_keeper_request_locked" | "stock_keeper_request_unlocked" | "stock_keeper_request_slot" | "stock_keeper_request_blueprint_left" | "stock_keeper_request_blueprint_middle" | "stock_keeper_request_blueprint_right" | "stock_keeper_request_send_hover" | "stock_keeper_request_scroll_top" | "stock_keeper_request_scroll_pad" | "stock_keeper_request_scroll_mid" | "stock_keeper_request_scroll_bot" | "stock_keeper_request_banner_l" | "stock_keeper_request_banner_m" | "stock_keeper_request_banner_r" | "stock_keeper_request_bg" | "stock_keeper_category_hidden" | "stock_keeper_category_shown" | "numbers" | "stock_keeper_search_sync_both" | "stock_keeper_search_sync_from_stock_keeper" | "stock_keeper_search_sync_from_jei" | "stock_keeper_search_sync_disabled" | "stock_keeper_category" | "stock_keeper_category_says" | "stock_keeper_category_header" | "stock_keeper_category_edit" | "stock_keeper_category_footer" | "stock_keeper_category_new" | "stock_keeper_category_entry" | "stock_keeper_category_up" | "stock_keeper_category_down" | "redstone_requester" | "jei_slot" | "jei_chance_slot" | "jei_catalyst_slot" | "jei_arrow" | "jei_long_arrow" | "jei_down_arrow" | "jei_light" | "jei_question_mark" | "jei_shadow" | "blockzapper_upgrade_recipe" | "jei_heat_bar" | "jei_no_heat_bar" | "button" | "button_hover" | "button_down" | "button_green" | "button_disabled" | "indicator" | "indicator_white" | "indicator_green" | "indicator_yellow" | "indicator_red" | "hotslot_arrow" | "hotslot_arrow_bad" | "hotslot" | "hotslot_active" | "hotslot_super_active" | "speech_tooltip_background" | "speech_tooltip_color" | "train_hud_speed_bg" | "train_hud_speed" | "train_hud_throttle" | "train_hud_throttle_pointer" | "train_hud_frame" | "train_hud_direction" | "train_prompt_l" | "train_prompt_r" | "train_prompt" | "trade_overlay" | "placement_indicator_sheet" | "trainmap_sprites" | "trainmap_signal" | "trainmap_station_ortho" | "trainmap_station_diago" | "trainmap_station_ortho_highlight" | "trainmap_station_diago_highlight" | "trainmap_toggle_panel" | "trainmap_toggle_on" | "trainmap_toggle_off" | "computer";
    export class $AllIcons implements $ScreenElement {
        bind(): void;
        render(arg0: $GuiGraphics, arg1: number, arg2: number): void;
        render(arg0: $PoseStack, arg1: $MultiBufferSource_, arg2: number): void;
        asStencil(): $DelegatedStencilElement;
        static I_SKIP_BLOCK_ENTITIES: $AllIcons;
        static I_PARTIAL_REQUESTS: $AllIcons;
        static I_RESPECT_NBT: $AllIcons;
        static I_FULL_REQUESTS: $AllIcons;
        static I_SEQ_REPEAT: $AllIcons;
        static I_3x3: $AllIcons;
        static I_INSERTED: $AllIcons;
        static I_CONFIG_SAVE: $AllIcons;
        static I_FOLLOW_DIAGONAL: $AllIcons;
        static I_FX_SURFACE_OFF: $AllIcons;
        static I_CART_ROTATE: $AllIcons;
        static I_DONT_REPLACE: $AllIcons;
        static I_FX_SURFACE_ON: $AllIcons;
        static VALUE_BOX_HOVER_8PX: $AllIcons;
        static I_TUNNEL_RANDOMIZE: $AllIcons;
        static I_MTD_SLOW_MODE: $AllIcons;
        static I_ADD_INVERTED_ATTRIBUTE: $AllIcons;
        static I_TOOL_DEPLOY: $AllIcons;
        static VALUE_BOX_HOVER_4PX: $AllIcons;
        static I_ROTATE_CCW: $AllIcons;
        static I_PATTERN_SOLID: $AllIcons;
        static I_CLEAR: $AllIcons;
        static I_WHITELIST_AND: $AllIcons;
        static I_REPLACE_EMPTY: $AllIcons;
        static I_CONFIRM: $AllIcons;
        static I_ROLLER_PAVE: $AllIcons;
        static I_PATTERN_CHANCE_75: $AllIcons;
        static I_WHITELIST_NOT: $AllIcons;
        static I_MTD_CLOSE: $AllIcons;
        static I_PAUSE: $AllIcons;
        static I_PRIORITY_VERY_HIGH: $AllIcons;
        static I_TRASH: $AllIcons;
        static I_MOVE_PLACE_RETURNED: $AllIcons;
        static I_OPEN_FOLDER: $AllIcons;
        static I_DICE: $AllIcons;
        static I_MTD_SCAN: $AllIcons;
        static I_MOVE_GAUGE: $AllIcons;
        static I_CONFIG_DISCARD: $AllIcons;
        static I_PLACE: $AllIcons;
        static I_TOOL_ROTATE: $AllIcons;
        static I_RMB: $AllIcons;
        static I_CLEAR_CHECKED: $AllIcons;
        static I_TUNNEL_FORCED_ROUND_ROBIN: $AllIcons;
        static I_WHITELIST: $AllIcons;
        static I_FLIP: $AllIcons;
        static I_ROTATE_PLACE: $AllIcons;
        static I_PLACEMENT_SETTINGS: $AllIcons;
        static I_REFRESH: $AllIcons;
        static I_FILL: $AllIcons;
        static I_FX_BLEND: $AllIcons;
        static I_SKIP_MISSING: $AllIcons;
        static I_CONFIG_OPEN: $AllIcons;
        static I_PATTERN_CHANCE_50: $AllIcons;
        static I_SEND_ONLY: $AllIcons;
        static I_PRIORITY_HIGH: $AllIcons;
        static I_CART_ROTATE_PAUSED: $AllIcons;
        static I_TUNNEL_ROUND_ROBIN: $AllIcons;
        static ICON_ATLAS: $ResourceLocation;
        static I_CONFIG_PREV: $AllIcons;
        static I_ROLLER_FILL: $AllIcons;
        static I_TUNNEL_PREFER_NEAREST: $AllIcons;
        static I_MTD_USER_MODE: $AllIcons;
        static I_WHITELIST_OR: $AllIcons;
        static I_ARM_FORCED_ROUND_ROBIN: $AllIcons;
        static I_ROLLER_WIDE_FILL: $AllIcons;
        static I_CONFIG_LOCKED: $AllIcons;
        static I_TUNNEL_FORCED_SPLIT: $AllIcons;
        static I_BLACKLIST: $AllIcons;
        static I_REPLACE_SOLID: $AllIcons;
        static I_REPLACE: $AllIcons;
        static I_FX_FIELD_ON: $AllIcons;
        static I_ROTATE_NEVER_PLACE: $AllIcons;
        static I_TOOL_MOVE_XZ: $AllIcons;
        static VALUE_BOX_HOVER_6PX: $AllIcons;
        static I_FX_FIELD_OFF: $AllIcons;
        static I_PLAY: $AllIcons;
        static I_MOVE_NEVER_PLACE: $AllIcons;
        static I_FLATTEN: $AllIcons;
        static I_SCROLL: $AllIcons;
        static I_MTD_RIGHT: $AllIcons;
        static I_NONE: $AllIcons;
        static I_TUNNEL_SYNCHRONIZE: $AllIcons;
        static I_PRIORITY_VERY_LOW: $AllIcons;
        static I_TOOL_MIRROR: $AllIcons;
        static I_TUNNEL_SPLIT: $AllIcons;
        static I_FX_BLEND_OFF: $AllIcons;
        static I_CART_ROTATE_LOCKED: $AllIcons;
        static ICON_ATLAS_SIZE: number;
        static I_PRIORITY_LOW: $AllIcons;
        static I_CONFIG_BACK: $AllIcons;
        static I_MTD_REPLAY: $AllIcons;
        static I_DISABLE: $AllIcons;
        static I_CONFIG_NEXT: $AllIcons;
        static I_CONFIG_UNLOCKED: $AllIcons;
        static I_TOOL_MOVE_Y: $AllIcons;
        static I_PASSIVE: $AllIcons;
        static I_MOVE_PLACE: $AllIcons;
        static I_ADD: $AllIcons;
        static I_MTD_LEFT: $AllIcons;
        static I_PATTERN_CHECKERED_INVERSED: $AllIcons;
        static I_ATTACHED: $AllIcons;
        static I_ROTATE_PLACE_RETURNED: $AllIcons;
        static I_SCHEMATIC: $AllIcons;
        static I_CENTERED: $AllIcons;
        static I_PATTERN_CHANCE_25: $AllIcons;
        static I_PATTERN_CHECKERED: $AllIcons;
        static I_STOP: $AllIcons;
        static I_ARM_ROUND_ROBIN: $AllIcons;
        static I_ACTIVE: $AllIcons;
        static I_LMB: $AllIcons;
        static I_MINUTE_HAND_FIRST: $AllIcons;
        static I_SEND_AND_RECEIVE: $AllIcons;
        static I_ARM_PREFER_FIRST: $AllIcons;
        static I_HOUR_HAND_FIRST: $AllIcons;
        static I_IGNORE_NBT: $AllIcons;
        static I_OVERLAY: $AllIcons;
        static I_VIEW_SCHEDULE: $AllIcons;
        static I_TARGET: $AllIcons;
        static I_FOLLOW_MATERIAL: $AllIcons;
        static I_TOOLBOX: $AllIcons;
        static I_HOUR_HAND_FIRST_24: $AllIcons;
        static I_CONFIG_RESET: $AllIcons;
        static I_REPLACE_ANY: $AllIcons;
        constructor(arg0: number, arg1: number);
    }
    export class $CustomLightingSettings implements $ILightingSettings {
        static builder(): $CustomLightingSettings$Builder;
        applyLighting(): void;
    }
    export class $ModularGuiLine {
        clear(): void;
        add(arg0: $Pair<$AbstractWidget, string>): void;
        forEach(arg0: $Consumer_<$GuiEventListener>): void;
        saveValues(arg0: $CompoundTag_): void;
        loadValues<T extends $GuiEventListener>(arg0: $CompoundTag_, arg1: $Consumer_<T>, arg2: $Consumer_<T>): void;
        renderWidgetBG(arg0: number, arg1: $GuiGraphics): void;
        constructor();
    }
    export class $RemovedGuiUtils {
        static drawHoveringText(arg0: $ItemStack_, arg1: $GuiGraphics, arg2: $List_<$FormattedText>, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: $Font): void;
        static drawHoveringText(arg0: $GuiGraphics, arg1: $List_<$FormattedText>, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: $Font): void;
        static drawHoveringText(arg0: $ItemStack_, arg1: $GuiGraphics, arg2: $List_<$FormattedText>, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: $Font): void;
        static drawHoveringText(arg0: $GuiGraphics, arg1: $List_<$FormattedText>, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: $Font): void;
        static preItemToolTip(arg0: $ItemStack_): void;
        static postItemToolTip(): void;
        constructor();
    }
    export class $ModularGuiLineBuilder {
        addSelectionScrollInput(arg0: number, arg1: number, arg2: $BiConsumer_<$SelectionScrollInput, $Label>, arg3: string): $ModularGuiLineBuilder;
        addScrollInput(arg0: number, arg1: number, arg2: $BiConsumer_<$ScrollInput, $Label>, arg3: string): $ModularGuiLineBuilder;
        customArea(arg0: number, arg1: number): $ModularGuiLineBuilder;
        addIntegerTextInput(arg0: number, arg1: number, arg2: $BiConsumer_<$EditBox, $TooltipArea>, arg3: string): $ModularGuiLineBuilder;
        addTextInput(arg0: number, arg1: number, arg2: $BiConsumer_<$EditBox, $TooltipArea>, arg3: string): $ModularGuiLineBuilder;
        speechBubble(): $ModularGuiLineBuilder;
        constructor(arg0: $Font, arg1: $ModularGuiLine, arg2: number, arg3: number);
    }
}
