import { $MapCodec } from "@package/com/mojang/serialization";
import { $ParticleProvider, $TextureSheetParticle } from "@package/net/minecraft/client/particle";
import { $FluidStack_ } from "@package/net/neoforged/neoforge/fluids";
import { $ParticleType_, $ParticleOptions, $ParticleType } from "@package/net/minecraft/core/particles";
import { $WeakReference } from "@package/java/lang/ref";
import { $RegisterParticleProvidersEvent } from "@package/net/neoforged/neoforge/client/event";
import { $RandomSource } from "@package/net/minecraft/util";
import { $ClientLevel } from "@package/net/minecraft/client/multiplayer";
import { $BlockPos } from "@package/net/minecraft/core";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $TextureAtlasSprite } from "@package/net/minecraft/client/renderer/texture";
import { $ICustomParticleData } from "@package/com/simibubi/create/foundation/particle";
import { $AABB } from "@package/net/minecraft/world/phys";
import { $StreamCodec } from "@package/net/minecraft/network/codec";

declare module "@package/com/simibubi/create/content/fluids/particle" {
    export class $FluidStackParticle extends $TextureSheetParticle {
        static create(arg0: $ParticleType_<$FluidParticleData>, arg1: $ClientLevel, arg2: $FluidStack_, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): $FluidStackParticle;
        speedUpWhenYMotionIsBlocked: boolean;
        lifetime: number;
        roll: number;
        yd: number;
        static MAXIMUM_COLLISION_VELOCITY_SQUARED: number;
        oRoll: number;
        random: $RandomSource;
        asyncparticle$lossSublevelPos: $BlockPos;
        bCol: number;
        yo: number;
        alpha: number;
        sprite: $TextureAtlasSprite;
        rCol: number;
        asyncparticle$tracingSubLevel: $WeakReference<any>;
        quadSize: number;
        level: $ClientLevel;
        zd: number;
        static INITIAL_AABB: $AABB;
        xd: number;
        friction: number;
        stoppedByCollision: boolean;
        onGround: boolean;
        removed: boolean;
        bbHeight: number;
        zo: number;
        gravity: number;
        gCol: number;
        xo: number;
        x: number;
        y: number;
        hasPhysics: boolean;
        z: number;
        bbWidth: number;
        age: number;
        constructor(arg0: $ClientLevel, arg1: $FluidStack_, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number);
    }
    export class $BasinFluidParticle extends $FluidStackParticle {
        speedUpWhenYMotionIsBlocked: boolean;
        lifetime: number;
        roll: number;
        yd: number;
        static MAXIMUM_COLLISION_VELOCITY_SQUARED: number;
        oRoll: number;
        random: $RandomSource;
        asyncparticle$lossSublevelPos: $BlockPos;
        bCol: number;
        yo: number;
        alpha: number;
        sprite: $TextureAtlasSprite;
        rCol: number;
        asyncparticle$tracingSubLevel: $WeakReference<any>;
        quadSize: number;
        level: $ClientLevel;
        zd: number;
        static INITIAL_AABB: $AABB;
        xd: number;
        friction: number;
        stoppedByCollision: boolean;
        onGround: boolean;
        removed: boolean;
        bbHeight: number;
        zo: number;
        gravity: number;
        gCol: number;
        xo: number;
        x: number;
        y: number;
        hasPhysics: boolean;
        z: number;
        bbWidth: number;
        age: number;
        constructor(arg0: $ClientLevel, arg1: $FluidStack_, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number);
    }
    export class $FluidParticleData implements $ParticleOptions, $ICustomParticleData<$FluidParticleData> {
        getCodec(arg0: $ParticleType_<$FluidParticleData>): $MapCodec<$FluidParticleData>;
        getFactory(): $ParticleProvider<$FluidParticleData>;
        getType(): $ParticleType<never>;
        getStreamCodec(): $StreamCodec<$RegistryFriendlyByteBuf, $FluidParticleData>;
        register(arg0: $ParticleType_<$FluidParticleData>, arg1: $RegisterParticleProvidersEvent): void;
        createType(): $ParticleType<$FluidParticleData>;
        static DRIP_STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $FluidParticleData>;
        static CODEC: $MapCodec<$FluidParticleData>;
        static BASIN_STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $FluidParticleData>;
        static BASIN_CODEC: $MapCodec<$FluidParticleData>;
        static DRIP_CODEC: $MapCodec<$FluidParticleData>;
        static STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $FluidParticleData>;
        constructor();
        constructor(arg0: $ParticleType_<never>, arg1: $FluidStack_);
        get factory(): $ParticleProvider<$FluidParticleData>;
        get type(): $ParticleType<never>;
        get streamCodec(): $StreamCodec<$RegistryFriendlyByteBuf, $FluidParticleData>;
    }
}
