import { $MapCodec } from "@package/com/mojang/serialization";
import { $GameEventListener } from "@package/net/minecraft/world/level/gameevent";
import { $SuperByteBufferCache$Compartment } from "@package/net/createmod/catnip/render";
import { $Supplier_, $Function_, $Consumer_ } from "@package/java/util/function";
import { $InteractionResult, $InteractionHand_, $ItemInteractionResult } from "@package/net/minecraft/world";
import { $Object2ByteLinkedOpenHashMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $StructureTransform } from "@package/com/simibubi/create/content/contraptions";
import { $Direction$Axis_, $BlockPos_, $Direction$Axis, $Direction, $IdMapper } from "@package/net/minecraft/core";
import { $ServerLevel } from "@package/net/minecraft/server/level";
import { $KineticBlockEntityRenderer, $KineticBlockEntity, $RotatedPillarKineticBlock, $KineticBlockEntityVisual, $AbstractEncasedShaftBlock } from "@package/com/simibubi/create/content/kinetics/base";
import { $StateDefinition, $BlockBehaviour$Properties, $BlockState_, $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $BlockEntityRendererProvider$Context } from "@package/net/minecraft/client/renderer/blockentity";
import { $IBE } from "@package/com/simibubi/create/foundation/block";
import { $Class, $ThreadLocal } from "@package/java/lang";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $Couple } from "@package/net/createmod/catnip/data";
import { $BlockGetter, $Level_ } from "@package/net/minecraft/world/level";
import { $ItemRequirement } from "@package/com/simibubi/create/content/schematics/requirement";
import { $SpecialBlockItemRequirement } from "@package/com/simibubi/create/api/schematic/requirement";
import { $VisualizationContext } from "@package/dev/engine_room/flywheel/api/visualization";
import { $CTSpriteShiftEntry } from "@package/com/simibubi/create/foundation/block/connected";
import { $Item, $ItemStack_ } from "@package/net/minecraft/world/item";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $ICogWheel, $SimpleKineticBlockEntity } from "@package/com/simibubi/create/content/kinetics/simpleRelays";
import { $EncasedBlock, $EncasedCTBehaviour } from "@package/com/simibubi/create/content/decoration/encasing";
import { $EnumProperty, $BooleanProperty } from "@package/net/minecraft/world/level/block/state/properties";
import { $ResourceKey } from "@package/net/minecraft/resources";
import { $Model } from "@package/dev/engine_room/flywheel/api/model";
import { $Rotation_, $Block$BlockStatePairKey, $SoundType, $Block } from "@package/net/minecraft/world/level/block";
import { $TransformableBlock } from "@package/com/simibubi/create/api/contraption/transformable";
import { $BlockHitResult } from "@package/net/minecraft/world/phys";
import { $BlockEntityTicker, $BlockEntityType, $BlockEntityType_, $BlockEntity } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/com/simibubi/create/content/kinetics/simpleRelays/encased" {
    export class $EncasedCogVisual extends $KineticBlockEntityVisual<$KineticBlockEntity> {
        static small(arg0: $VisualizationContext, arg1: $KineticBlockEntity, arg2: number): $EncasedCogVisual;
        static large(arg0: $VisualizationContext, arg1: $KineticBlockEntity, arg2: number): $EncasedCogVisual;
        constructor(arg0: $VisualizationContext, arg1: $KineticBlockEntity, arg2: boolean, arg3: number, arg4: $Model);
    }
    export class $EncasedCogwheelBlock extends $RotatedPillarKineticBlock implements $ICogWheel, $IBE<$SimpleKineticBlockEntity>, $SpecialBlockItemRequirement, $TransformableBlock, $EncasedBlock {
        getRequiredItems(arg0: $BlockState_, arg1: $BlockEntity): $ItemRequirement;
        transform(arg0: $BlockState_, arg1: $StructureTransform): $BlockState;
        handleEncasing(arg0: $BlockState_, arg1: $Level_, arg2: $BlockPos_, arg3: $ItemStack_, arg4: $Player, arg5: $InteractionHand_, arg6: $BlockHitResult): void;
        getBlockEntityType(): $BlockEntityType<$SimpleKineticBlockEntity>;
        getBlockEntityClass(): $Class<$SimpleKineticBlockEntity>;
        swapShafts(arg0: $BlockState_): $BlockState;
        getCasing(): $Block;
        swapShaftsForRotation(arg0: $BlockState_, arg1: $Rotation_, arg2: $Direction$Axis_): $BlockState;
        isSmallCog(): boolean;
        isLargeCog(): boolean;
        isDedicatedCogWheel(): boolean;
        withBlockEntityDo(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Consumer_<$SimpleKineticBlockEntity>): void;
        onBlockEntityUse(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Function_<$SimpleKineticBlockEntity, $InteractionResult>): $InteractionResult;
        getBlockEntityOptional(arg0: $BlockGetter, arg1: $BlockPos_): ($SimpleKineticBlockEntity) | undefined;
        onBlockEntityUseItemOn(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Function_<$SimpleKineticBlockEntity, $ItemInteractionResult>): $ItemInteractionResult;
        getBlockEntity(arg0: $BlockGetter, arg1: $BlockPos_): $SimpleKineticBlockEntity;
        getTicker<S extends $BlockEntity>(arg0: $Level_, arg1: $BlockState_, arg2: $BlockEntityType_<S>): $BlockEntityTicker<S>;
        newBlockEntity(arg0: $BlockPos_, arg1: $BlockState_): $BlockEntity;
        getListener<T extends $BlockEntity>(arg0: $ServerLevel, arg1: T): $GameEventListener;
        explosionResistance: number;
        static UPDATE_SHAPE_ORDER: $Direction[];
        static OCCLUSION_CACHE: $ThreadLocal<$Object2ByteLinkedOpenHashMap<$Block$BlockStatePairKey>>;
        static UPDATE_NONE: number;
        static UPDATE_INVISIBLE: number;
        stateDefinition: $StateDefinition<$Block, $BlockState>;
        static UPDATE_MOVE_BY_PISTON: number;
        static UPDATE_LIMIT: number;
        static UPDATE_ALL: number;
        drops: $ResourceKey<$LootTable>;
        static UPDATE_KNOWN_SHAPE: number;
        static UPDATE_SUPPRESS_DROPS: number;
        dynamicShape: boolean;
        soundType: $SoundType;
        jumpFactor: number;
        static UPDATE_IMMEDIATE: number;
        item: $Item;
        static TOP_SHAFT: $BooleanProperty;
        static CODEC: $MapCodec<$Block>;
        static UPDATE_NEIGHBORS: number;
        static INDESTRUCTIBLE: number;
        speedFactor: number;
        friction: number;
        static BLOCK_STATE_REGISTRY: $IdMapper<$BlockState>;
        static UPDATE_ALL_IMMEDIATE: number;
        static INSTANT: number;
        static UPDATE_CLIENTS: number;
        hasCollision: boolean;
        static BOTTOM_SHAFT: $BooleanProperty;
        static AXIS: $EnumProperty<$Direction$Axis>;
        constructor(arg0: $BlockBehaviour$Properties, arg1: boolean, arg2: $Supplier_<$Block>);
        get blockEntityType(): $BlockEntityType<$SimpleKineticBlockEntity>;
        get blockEntityClass(): $Class<$SimpleKineticBlockEntity>;
        get casing(): $Block;
        get smallCog(): boolean;
        get largeCog(): boolean;
        get dedicatedCogWheel(): boolean;
    }
    export class $EncasedShaftBlock extends $AbstractEncasedShaftBlock implements $IBE<$KineticBlockEntity>, $SpecialBlockItemRequirement, $EncasedBlock {
        getRequiredItems(arg0: $BlockState_, arg1: $BlockEntity): $ItemRequirement;
        handleEncasing(arg0: $BlockState_, arg1: $Level_, arg2: $BlockPos_, arg3: $ItemStack_, arg4: $Player, arg5: $InteractionHand_, arg6: $BlockHitResult): void;
        getBlockEntityType(): $BlockEntityType<$KineticBlockEntity>;
        getBlockEntityClass(): $Class<$KineticBlockEntity>;
        getCasing(): $Block;
        withBlockEntityDo(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Consumer_<$KineticBlockEntity>): void;
        onBlockEntityUse(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Function_<$KineticBlockEntity, $InteractionResult>): $InteractionResult;
        getBlockEntityOptional(arg0: $BlockGetter, arg1: $BlockPos_): ($KineticBlockEntity) | undefined;
        onBlockEntityUseItemOn(arg0: $BlockGetter, arg1: $BlockPos_, arg2: $Function_<$KineticBlockEntity, $ItemInteractionResult>): $ItemInteractionResult;
        getBlockEntity(arg0: $BlockGetter, arg1: $BlockPos_): $KineticBlockEntity;
        getTicker<S extends $BlockEntity>(arg0: $Level_, arg1: $BlockState_, arg2: $BlockEntityType_<S>): $BlockEntityTicker<S>;
        newBlockEntity(arg0: $BlockPos_, arg1: $BlockState_): $BlockEntity;
        getListener<T extends $BlockEntity>(arg0: $ServerLevel, arg1: T): $GameEventListener;
        explosionResistance: number;
        static UPDATE_SHAPE_ORDER: $Direction[];
        static OCCLUSION_CACHE: $ThreadLocal<$Object2ByteLinkedOpenHashMap<$Block$BlockStatePairKey>>;
        static UPDATE_NONE: number;
        static UPDATE_INVISIBLE: number;
        stateDefinition: $StateDefinition<$Block, $BlockState>;
        static UPDATE_MOVE_BY_PISTON: number;
        static UPDATE_LIMIT: number;
        static UPDATE_ALL: number;
        drops: $ResourceKey<$LootTable>;
        static UPDATE_KNOWN_SHAPE: number;
        static UPDATE_SUPPRESS_DROPS: number;
        dynamicShape: boolean;
        soundType: $SoundType;
        jumpFactor: number;
        static UPDATE_IMMEDIATE: number;
        item: $Item;
        static CODEC: $MapCodec<$Block>;
        static UPDATE_NEIGHBORS: number;
        static INDESTRUCTIBLE: number;
        speedFactor: number;
        friction: number;
        static BLOCK_STATE_REGISTRY: $IdMapper<$BlockState>;
        static UPDATE_ALL_IMMEDIATE: number;
        static INSTANT: number;
        static UPDATE_CLIENTS: number;
        hasCollision: boolean;
        static AXIS: $EnumProperty<$Direction$Axis>;
        constructor(arg0: $BlockBehaviour$Properties, arg1: $Supplier_<$Block>);
        get blockEntityType(): $BlockEntityType<$KineticBlockEntity>;
        get blockEntityClass(): $Class<$KineticBlockEntity>;
        get casing(): $Block;
    }
    export class $EncasedCogCTBehaviour extends $EncasedCTBehaviour {
        constructor(arg0: $CTSpriteShiftEntry);
        constructor(arg0: $CTSpriteShiftEntry, arg1: $Couple<$CTSpriteShiftEntry>);
    }
    export class $EncasedCogRenderer extends $KineticBlockEntityRenderer<$SimpleKineticBlockEntity> {
        static small(arg0: $BlockEntityRendererProvider$Context): $EncasedCogRenderer;
        static large(arg0: $BlockEntityRendererProvider$Context): $EncasedCogRenderer;
        static KINETIC_BLOCK: $SuperByteBufferCache$Compartment<$BlockState>;
        static rainbowMode: boolean;
        constructor(arg0: $BlockEntityRendererProvider$Context, arg1: boolean);
    }
}
