import { $ModCommonEvents, $CommonEvents, $ModClientEvents, $ClientEvents, $ClientEventsListener } from "@package/xaero/common/events";
import { $InfoDisplayIO } from "@package/xaero/hud/minimap/info";
import { $HudIO } from "@package/xaero/hud/io";
import { $ServerPlayerTickHandler } from "@package/xaero/common/server/player";
import { $EntityRadarCategorySerializers } from "@package/xaero/hud/minimap/common/radar/category";
import { $KeyMappingControllerManager } from "@package/xaero/hud/controls/key";
import { $Hud, $HudSession } from "@package/xaero/hud";
import { $LegacyCommonConfigIO } from "@package/xaero/common/config";
import { $Path } from "@package/java/nio/file";
import { $InterfaceRenderer } from "@package/xaero/common/interfaces/render";
import { $GuiHelper } from "@package/xaero/common/gui";
import { $HighlighterRegistry } from "@package/xaero/common/minimap/highlight";
import { $Object } from "@package/java/lang";
import { $PatreonMod } from "@package/xaero/lib/patreon";
import { $PlayerTrackerSystemManager } from "@package/xaero/common/minimap/radar/tracker/system";
import { $File } from "@package/java/io";
import { $MinimapSession } from "@package/xaero/hud/minimap/module";
import { $MinimapProcessor } from "@package/xaero/common/minimap";
import { $HudRenderer } from "@package/xaero/hud/render";
import { $LocalPlayer } from "@package/net/minecraft/client/player";
import { $EntityRadarCategoryManager } from "@package/xaero/hud/minimap/radar/category";
import { $SupportServerMods } from "@package/xaero/common/server/mods";
import { $ControlsRegister } from "@package/xaero/hud/controls";
import { $MinimapWriter } from "@package/xaero/common/minimap/write";
import { $FieldValidatorHolder } from "@package/xaero/common/validator";
import { $ConfigChannel } from "@package/xaero/lib/common/config/channel";
import { $BlockStateShortShapeCache } from "@package/xaero/common/cache";
import { $InterfaceManager } from "@package/xaero/common/interfaces";
import { $IPacketHandler } from "@package/xaero/lib/common/packet";
import { $RenderedPlayerTrackerManager } from "@package/xaero/hud/minimap/player/tracker/system";
import { $SupportMods } from "@package/xaero/common/mods";
import { $ModSettings } from "@package/xaero/common/settings";
import { $Minimap } from "@package/xaero/hud/minimap";
import { $Logger } from "@package/org/apache/logging/log4j";
import { $WaypointSharingHandler, $WaypointsManager } from "@package/xaero/common/minimap/waypoints";
import { $PlayerTrackerMinimapElementRenderer } from "@package/xaero/hud/minimap/player/tracker";
export * as server from "@package/xaero/common/server";
export * as minimap from "@package/xaero/common/minimap";
export * as core from "@package/xaero/common/core";
export * as validator from "@package/xaero/common/validator";
export * as mods from "@package/xaero/common/mods";
export * as controls from "@package/xaero/common/controls";
export * as interfaces from "@package/xaero/common/interfaces";
export * as config from "@package/xaero/common/config";
export * as events from "@package/xaero/common/events";
export * as graphics from "@package/xaero/common/graphics";
export * as settings from "@package/xaero/common/settings";
export * as gui from "@package/xaero/common/gui";
export * as cache from "@package/xaero/common/cache";

declare module "@package/xaero/common" {
    export class $HudMod implements $IXaeroMinimap {
        getInterfaces(): $InterfaceManager;
        getMessage(): string;
        isStandalone(): boolean;
        getEvents(): $ClientEvents;
        setSettings(arg0: $ModSettings): void;
        getSettings(): $ModSettings;
        setMessage(arg0: string): void;
        /**
         * @deprecated
         */
        getWaypointsFolder(): $Path;
        resetSettings(): void;
        getLatestVersion(): string;
        getModClientEvents(): $ModClientEvents;
        getModEvents(): $ModClientEvents;
        getHudRenderer(): $HudRenderer;
        getInfoDisplaysIO(): $InfoDisplayIO;
        getSupportMods(): $SupportMods;
        getPlatformContext(): $PlatformContext;
        getCommonEvents(): $CommonEvents;
        getFieldValidators(): $FieldValidatorHolder;
        getNewestUpdateID(): number;
        setNewestUpdateID(arg0: number): void;
        tryLoadLaterServer(): void;
        tryLoadLater(): void;
        getModCommonEvents(): $ModCommonEvents;
        getMessageHandler(): $IPacketHandler;
        getPlayerTracker(): $RenderedPlayerTrackerManager;
        getCommonConfigIO(): $LegacyCommonConfigIO;
        isFirstStageLoaded(): boolean;
        getWaypointsFile(): $Path;
        setCommonConfigIO(arg0: $LegacyCommonConfigIO): void;
        setLatestVersion(arg0: string): void;
        setOutdated(arg0: boolean): void;
        getGuiHelper(): $GuiHelper;
        getConfigSubFolder(): $Path;
        getVersionID(): string;
        isLoadedClient(): boolean;
        getMinimapFolder(): $Path;
        getHudConfigs(): $ConfigChannel;
        isLoadedServer(): boolean;
        getConfigFile(): $Path;
        getServerPlayerTickHandler(): $ServerPlayerTickHandler;
        setServerPlayerTickHandler(arg0: $ServerPlayerTickHandler): void;
        getLatestVersionMD5(): string;
        setLatestVersionMD5(arg0: string): void;
        getSupportServerMods(): $SupportServerMods;
        getClientEventsListener(): $ClientEventsListener;
        getInterfaceRenderer(): $InterfaceRenderer;
        ensureControlsRegister(): void;
        getKeyMappingControllers(): $KeyMappingControllerManager;
        getTrackedPlayerRenderer(): $PlayerTrackerMinimapElementRenderer;
        getControlsRegister(): $ControlsRegister;
        getHud(): $Hud;
        isOutdated(): boolean;
        isFairPlay(): boolean;
        loadLater(): void;
        getHudIO(): $HudIO;
        getMinimap(): $Minimap;
        loadServer(): void;
        getModJAR(): $File;
        getPatreon(): $PatreonMod;
        getOldConfigFileName(): string;
        getDefaultConfigsSubFolder(): $Path;
        getEntityRadarCategorySerializers(): $EntityRadarCategorySerializers;
        getEntityRadarCategoryManager(): $EntityRadarCategoryManager;
        /**
         * @deprecated
         */
        getPlayerTrackerSystemManager(): $PlayerTrackerSystemManager;
        waypointsFile: $Path;
        static INSTANCE: $HudMod;
        static LOGGER: $Logger;
        static FAIRPLAY: boolean;
        shouldLoadLegacySettings: boolean;
        minimapFolder: $Path;
        get interfaces(): $InterfaceManager;
        get standalone(): boolean;
        get events(): $ClientEvents;
        get waypointsFolder(): $Path;
        get modClientEvents(): $ModClientEvents;
        get modEvents(): $ModClientEvents;
        get hudRenderer(): $HudRenderer;
        get infoDisplaysIO(): $InfoDisplayIO;
        get supportMods(): $SupportMods;
        get platformContext(): $PlatformContext;
        get commonEvents(): $CommonEvents;
        get fieldValidators(): $FieldValidatorHolder;
        get modCommonEvents(): $ModCommonEvents;
        get messageHandler(): $IPacketHandler;
        get playerTracker(): $RenderedPlayerTrackerManager;
        get firstStageLoaded(): boolean;
        get guiHelper(): $GuiHelper;
        get configSubFolder(): $Path;
        get versionID(): string;
        get loadedClient(): boolean;
        get hudConfigs(): $ConfigChannel;
        get loadedServer(): boolean;
        get configFile(): $Path;
        get supportServerMods(): $SupportServerMods;
        get clientEventsListener(): $ClientEventsListener;
        get interfaceRenderer(): $InterfaceRenderer;
        get keyMappingControllers(): $KeyMappingControllerManager;
        get trackedPlayerRenderer(): $PlayerTrackerMinimapElementRenderer;
        get controlsRegister(): $ControlsRegister;
        get hud(): $Hud;
        get fairPlay(): boolean;
        get hudIO(): $HudIO;
        get minimap(): $Minimap;
        get modJAR(): $File;
        get patreon(): $PatreonMod;
        get oldConfigFileName(): string;
        get defaultConfigsSubFolder(): $Path;
        get entityRadarCategorySerializers(): $EntityRadarCategorySerializers;
        get entityRadarCategoryManager(): $EntityRadarCategoryManager;
        get playerTrackerSystemManager(): $PlayerTrackerSystemManager;
    }
    /**
     * @deprecated
     */
    export class $XaeroMinimapSession extends $HudSession {
        static getCurrentSession(): $XaeroMinimapSession;
        getModMain(): $IXaeroMinimap;
        getWaypointsManager(): $WaypointsManager;
        getMinimapProcessor(): $MinimapProcessor;
        static getForPlayer(arg0: $LocalPlayer): $XaeroMinimapSession;
        getWaypointSharing(): $WaypointSharingHandler;
        constructor(arg0: $HudMod);
        static get currentSession(): $XaeroMinimapSession;
        get modMain(): $IXaeroMinimap;
        get waypointsManager(): $WaypointsManager;
        get minimapProcessor(): $MinimapProcessor;
        get waypointSharing(): $WaypointSharingHandler;
    }
    export class $PlatformContext {
        createSupportMods(arg0: $IXaeroMinimap): $SupportMods;
        getModInfoVersion(): string;
        createCommonEvents(arg0: $HudMod): $CommonEvents;
        createClientEvents(arg0: $HudMod): $ClientEvents;
        createModCommonEvents(arg0: $IXaeroMinimap): $ModCommonEvents;
        createModClientEvents(arg0: $IXaeroMinimap): $ModClientEvents;
        createMinimapWriter(arg0: $IXaeroMinimap, arg1: $MinimapSession, arg2: $BlockStateShortShapeCache, arg3: $HighlighterRegistry): $MinimapWriter;
        getLoaderClientOnly(): $PlatformContextLoaderClientOnly;
        getLoaderCommon(): $PlatformContextLoaderCommon;
        constructor();
        get modInfoVersion(): string;
        get loaderClientOnly(): $PlatformContextLoaderClientOnly;
        get loaderCommon(): $PlatformContextLoaderCommon;
    }
    export class $PlatformContextLoaderClientOnly {
        preInit(arg0: string, arg1: $IXaeroMinimap): void;
        constructor();
    }
    export class $PlatformContextLoaderCommon {
        setup(arg0: $IXaeroMinimap): void;
        constructor();
        set up(value: $IXaeroMinimap);
    }
    export class $IXaeroMinimap {
        static wrongWaypointsFolder: $File;
        static old_waypointsFile: $Path;
        static wrongWaypointsFile: $File;
    }
    export interface $IXaeroMinimap {
        getModId(): string;
        getInterfaces(): $InterfaceManager;
        getMessage(): string;
        isStandalone(): boolean;
        getEvents(): $ClientEvents;
        setSettings(arg0: $ModSettings): void;
        getSettings(): $ModSettings;
        setMessage(arg0: string): void;
        getWaypointsFolder(): $Path;
        resetSettings(): void;
        getLatestVersion(): string;
        getModClientEvents(): $ModClientEvents;
        getModEvents(): $ModClientEvents;
        getHudRenderer(): $HudRenderer;
        getSupportMods(): $SupportMods;
        getPlatformContext(): $PlatformContext;
        getCommonEvents(): $CommonEvents;
        getFieldValidators(): $FieldValidatorHolder;
        getNewestUpdateID(): number;
        setNewestUpdateID(arg0: number): void;
        tryLoadLaterServer(): void;
        tryLoadLater(): void;
        getModCommonEvents(): $ModCommonEvents;
        getMessageHandler(): $IPacketHandler;
        getPlayerTracker(): $RenderedPlayerTrackerManager;
        getCommonConfigIO(): $LegacyCommonConfigIO;
        isFirstStageLoaded(): boolean;
        getWaypointsFile(): $Path;
        setCommonConfigIO(arg0: $LegacyCommonConfigIO): void;
        setLatestVersion(arg0: string): void;
        setOutdated(arg0: boolean): void;
        getGuiHelper(): $GuiHelper;
        createSession(): $XaeroMinimapSession;
        getVersionsURL(): string;
        getFileLayoutID(): string;
        getSettingsKey(): $Object;
        getVersionID(): string;
        isLoadedClient(): boolean;
        isLoadedServer(): boolean;
        getConfigFile(): $Path;
        getUpdateLink(): string;
        getServerPlayerTickHandler(): $ServerPlayerTickHandler;
        setServerPlayerTickHandler(arg0: $ServerPlayerTickHandler): void;
        getLatestVersionMD5(): string;
        setLatestVersionMD5(arg0: string): void;
        getSupportServerMods(): $SupportServerMods;
        getClientEventsListener(): $ClientEventsListener;
        getInterfaceRenderer(): $InterfaceRenderer;
        ensureControlsRegister(): void;
        getTrackedPlayerRenderer(): $PlayerTrackerMinimapElementRenderer;
        getControlsRegister(): $ControlsRegister;
        getHud(): $Hud;
        isOutdated(): boolean;
        isFairPlay(): boolean;
        getHudIO(): $HudIO;
        getMinimap(): $Minimap;
        getModJAR(): $File;
        getPatreon(): $PatreonMod;
        getServerSettingsKey(): $Object;
        getEntityRadarCategoryManager(): $EntityRadarCategoryManager;
        /**
         * @deprecated
         */
        getPlayerTrackerSystemManager(): $PlayerTrackerSystemManager;
        get modId(): string;
        get interfaces(): $InterfaceManager;
        get standalone(): boolean;
        get events(): $ClientEvents;
        get waypointsFolder(): $Path;
        get modClientEvents(): $ModClientEvents;
        get modEvents(): $ModClientEvents;
        get hudRenderer(): $HudRenderer;
        get supportMods(): $SupportMods;
        get platformContext(): $PlatformContext;
        get commonEvents(): $CommonEvents;
        get fieldValidators(): $FieldValidatorHolder;
        get modCommonEvents(): $ModCommonEvents;
        get messageHandler(): $IPacketHandler;
        get playerTracker(): $RenderedPlayerTrackerManager;
        get firstStageLoaded(): boolean;
        get waypointsFile(): $Path;
        get guiHelper(): $GuiHelper;
        get versionsURL(): string;
        get fileLayoutID(): string;
        get settingsKey(): $Object;
        get versionID(): string;
        get loadedClient(): boolean;
        get loadedServer(): boolean;
        get configFile(): $Path;
        get updateLink(): string;
        get supportServerMods(): $SupportServerMods;
        get clientEventsListener(): $ClientEventsListener;
        get interfaceRenderer(): $InterfaceRenderer;
        get trackedPlayerRenderer(): $PlayerTrackerMinimapElementRenderer;
        get controlsRegister(): $ControlsRegister;
        get hud(): $Hud;
        get fairPlay(): boolean;
        get hudIO(): $HudIO;
        get minimap(): $Minimap;
        get modJAR(): $File;
        get patreon(): $PatreonMod;
        get serverSettingsKey(): $Object;
        get entityRadarCategoryManager(): $EntityRadarCategoryManager;
        get playerTrackerSystemManager(): $PlayerTrackerSystemManager;
    }
}
