import { $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey } from "@package/net/minecraft/tags";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $RigidBodyHandle } from "@package/dev/ryanhcode/sable/api/physics/handle";
import { $EntityType_, $Entity$RemovalReason, $Pose, $PortalProcessor } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $ThrowableProjectile } from "@package/net/minecraft/world/entity/projectile";
import { $ServerSubLevel } from "@package/dev/ryanhcode/sable/sublevel";
import { $UUID } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $SynchedEntityData, $EntityDataAccessor_, $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $HolderLookup$Provider, $BlockPos, $Direction } from "@package/net/minecraft/core";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";

declare module "@package/dev/simulated_team/simulated/content/entities/launched_plunger" {
    export class $LaunchedPlungerEntity extends $ThrowableProjectile {
        static create(arg0: $EntityType_<$LaunchedPlungerEntity>, arg1: $Level_): $LaunchedPlungerEntity;
        getTarget(): $Vec3;
        getData<T>(arg0: $EntityDataAccessor_<T>): T;
        setData<T>(arg0: $EntityDataAccessor_<T>, arg1: T): void;
        isPlunged(): boolean;
        setOther(arg0: $LaunchedPlungerEntity): void;
        getOther(): $LaunchedPlungerEntity;
        physicsTick(arg0: $ServerSubLevel, arg1: $RigidBodyHandle, arg2: number): void;
        getClientSmoothedVelocity(arg0: number): $Vec3;
        resetPlunged(): void;
        getAttachmentPos(): $Vec3;
        getAttachmentPos(arg0: number): $Vec3;
        getClientTarget(arg0: number): $Vec3;
        getPlungedTime(): number;
        getAnimationOffset(): number;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        leftOwner: boolean;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        sodiumdynamiclights$luminance: number;
        removalReason: $Entity$RemovalReason;
        static PLUNGED_BLOCK_POS: $EntityDataAccessor<$BlockPos>;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static OTHER_PLUNGER_ID: $EntityDataAccessor<number>;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static IS_FIRST: $EntityDataAccessor<boolean>;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        static PLUNGED_DIRECTION: $EntityDataAccessor<$Direction>;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        ownerUUID: $UUID;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static OTHER_PLUNGER: $EntityDataAccessor<($UUID) | undefined>;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static TARGET_POS: $EntityDataAccessor<$Vec3>;
        static IS_PLUNGED: $EntityDataAccessor<boolean>;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(arg0: $EntityType_<$LaunchedPlungerEntity>, arg1: $Level_);
        get target(): $Vec3;
        get plunged(): boolean;
        get plungedTime(): number;
        get animationOffset(): number;
    }
}
