import { $EntityRendererProvider$Context, $EntityRenderDispatcher, $EntityRenderer } from "@package/net/minecraft/client/renderer/entity";
import { $GeoModel } from "@package/software/bernie/geckolib/model";
import { $MultiBufferSource_, $BlockEntityWithoutLevelRenderer, $RenderType } from "@package/net/minecraft/client/renderer";
import { $Item, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $EntityModelSet, $ModelPart } from "@package/net/minecraft/client/model/geom";
import { $EquipmentSlot, $EntityType_, $EquipmentSlot_, $Mob, $Entity } from "@package/net/minecraft/world/entity";
import { $GeoRenderLayer } from "@package/software/bernie/geckolib/renderer/layer";
import { $CallbackInfo } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $List } from "@package/java/util";
import { $GeoAnimatable } from "@package/software/bernie/geckolib/animatable";
import { $HumanoidModel, $HumanoidModel$ArmPose } from "@package/net/minecraft/client/model";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Color } from "@package/software/bernie/geckolib/util";
import { $VertexConsumer, $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $BlockEntityRenderDispatcher, $BlockEntityRenderer } from "@package/net/minecraft/client/renderer/blockentity";
import { $GeoBone, $GeoCube_, $BakedGeoModel_, $GeoQuad_ } from "@package/software/bernie/geckolib/cache/object";
import { $Vec3_, $AABB } from "@package/net/minecraft/world/phys";
import { $BlockEntityType_, $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $Matrix4f, $Vector3f } from "@package/org/joml";
export * as layer from "@package/software/bernie/geckolib/renderer/layer";

declare module "@package/software/bernie/geckolib/renderer" {
    export class $GeoEntityRenderer<T extends $Entity> extends $EntityRenderer<T> implements $GeoRenderer<T> {
        getRenderType(arg0: T, arg1: $ResourceLocation_, arg2: $MultiBufferSource_, arg3: number): $RenderType;
        isShaking(arg0: T): boolean;
        getRenderLayers(): $List<$GeoRenderLayer<T>>;
        firePostRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): void;
        updateAnimatedTextureFrame(arg0: T): void;
        doPostRenderCleanup(): void;
        getGeoModel(): $GeoModel<T>;
        renderRecursively(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        applyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        addRenderLayer(arg0: $GeoRenderLayer<T>): $GeoEntityRenderer<T>;
        getPackedOverlay(arg0: T, arg1: number, arg2: number): number;
        actuallyRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        getInstanceId(arg0: T): number;
        getRenderColor(arg0: T, arg1: number, arg2: number): $Color;
        renderFinal(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number, arg8: number): void;
        firePreRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): boolean;
        renderLeash<E extends $Entity, M extends $Mob>(arg0: M, arg1: number, arg2: $PoseStack, arg3: $MultiBufferSource_, arg4: E): void;
        fireCompileRenderLayersEvent(): void;
        getNameRenderCutoffDistance(arg0: T): number;
        withScale(arg0: number): $GeoEntityRenderer<T>;
        withScale(arg0: number, arg1: number): $GeoEntityRenderer<T>;
        preRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        handler$cae000$acceleratedrendering$renderCubesOfBoneFast(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number, arg6: $CallbackInfo): void;
        renderCube(arg0: $PoseStack, arg1: $GeoCube_, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        createVerticesOfQuad(arg0: $GeoQuad_, arg1: $Matrix4f, arg2: $Vector3f, arg3: $VertexConsumer, arg4: number, arg5: number, arg6: number): void;
        preApplyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        postRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        reRender(arg0: $BakedGeoModel_, arg1: $PoseStack, arg2: $MultiBufferSource_, arg3: T, arg4: $RenderType, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number, arg9: number): void;
        scaleModelForRender(arg0: number, arg1: number, arg2: $PoseStack, arg3: T, arg4: $BakedGeoModel_, arg5: boolean, arg6: number, arg7: number, arg8: number): void;
        applyRenderLayersForBone(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        checkAndRefreshBuffer(arg0: boolean, arg1: $VertexConsumer, arg2: $MultiBufferSource_, arg3: $RenderType): $VertexConsumer;
        getMotionAnimThreshold(arg0: T): number;
        renderCubesOfBone(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        defaultRender(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number): void;
        renderChildBones(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        getTextureLocation(arg0: T): $ResourceLocation;
        getAnimatable(): T;
        shadowRadius: number;
        static LEASH_RENDER_STEPS: number;
        entityRenderDispatcher: $EntityRenderDispatcher;
        shadowStrength: number;
        static NAMETAG_SCALE: number;
        constructor(arg0: $EntityRendererProvider$Context, arg1: $EntityType_<T>);
        constructor(arg0: $EntityRendererProvider$Context, arg1: $GeoModel<T>);
        get renderLayers(): $List<$GeoRenderLayer<T>>;
        get geoModel(): $GeoModel<T>;
        get animatable(): T;
    }
    export class $GeoItemRenderer<T extends $Item> extends $BlockEntityWithoutLevelRenderer implements $GeoRenderer<T> {
        getRenderLayers(): $List<$GeoRenderLayer<T>>;
        getTextureLocation(arg0: T): $ResourceLocation;
        firePostRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): void;
        updateAnimatedTextureFrame(arg0: T): void;
        doPostRenderCleanup(): void;
        getGeoModel(): $GeoModel<T>;
        getAnimatable(): T;
        renderRecursively(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addRenderLayer(arg0: $GeoRenderLayer<T>): $GeoItemRenderer<T>;
        actuallyRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        getInstanceId(arg0: T): number;
        firePreRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): boolean;
        fireCompileRenderLayersEvent(): void;
        withScale(arg0: number): $GeoItemRenderer<T>;
        withScale(arg0: number, arg1: number): $GeoItemRenderer<T>;
        preRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        useAlternateGuiLighting(): $GeoItemRenderer<T>;
        setupLightingForGuiRender(): void;
        getCurrentItemStack(): $ItemStack;
        getRenderType(arg0: T, arg1: $ResourceLocation_, arg2: $MultiBufferSource_, arg3: number): $RenderType;
        handler$cae000$acceleratedrendering$renderCubesOfBoneFast(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number, arg6: $CallbackInfo): void;
        renderCube(arg0: $PoseStack, arg1: $GeoCube_, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        createVerticesOfQuad(arg0: $GeoQuad_, arg1: $Matrix4f, arg2: $Vector3f, arg3: $VertexConsumer, arg4: number, arg5: number, arg6: number): void;
        preApplyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        postRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        reRender(arg0: $BakedGeoModel_, arg1: $PoseStack, arg2: $MultiBufferSource_, arg3: T, arg4: $RenderType, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number, arg9: number): void;
        scaleModelForRender(arg0: number, arg1: number, arg2: $PoseStack, arg3: T, arg4: $BakedGeoModel_, arg5: boolean, arg6: number, arg7: number, arg8: number): void;
        applyRenderLayersForBone(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        checkAndRefreshBuffer(arg0: boolean, arg1: $VertexConsumer, arg2: $MultiBufferSource_, arg3: $RenderType): $VertexConsumer;
        getMotionAnimThreshold(arg0: T): number;
        renderCubesOfBone(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        applyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        getPackedOverlay(arg0: T, arg1: number, arg2: number): number;
        defaultRender(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number): void;
        getRenderColor(arg0: T, arg1: number, arg2: number): $Color;
        renderChildBones(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        renderFinal(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number, arg8: number): void;
        constructor(arg0: $BlockEntityRenderDispatcher, arg1: $EntityModelSet, arg2: $GeoModel<T>);
        constructor(arg0: $GeoModel<T>);
        constructor<I extends T>(arg0: I);
        get renderLayers(): $List<$GeoRenderLayer<T>>;
        get geoModel(): $GeoModel<T>;
        get animatable(): T;
        get currentItemStack(): $ItemStack;
    }
    export class $GeoObjectRenderer<T extends $GeoAnimatable> implements $GeoRenderer<T> {
        render(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number): void;
        getRenderLayers(): $List<$GeoRenderLayer<T>>;
        getTextureLocation(arg0: T): $ResourceLocation;
        firePostRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): void;
        updateAnimatedTextureFrame(arg0: T): void;
        doPostRenderCleanup(): void;
        getGeoModel(): $GeoModel<T>;
        getAnimatable(): T;
        renderRecursively(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addRenderLayer(arg0: $GeoRenderLayer<T>): $GeoObjectRenderer<T>;
        actuallyRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        firePreRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): boolean;
        fireCompileRenderLayersEvent(): void;
        withScale(arg0: number, arg1: number): $GeoObjectRenderer<T>;
        withScale(arg0: number): $GeoObjectRenderer<T>;
        preRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        getRenderType(arg0: T, arg1: $ResourceLocation_, arg2: $MultiBufferSource_, arg3: number): $RenderType;
        handler$cae000$acceleratedrendering$renderCubesOfBoneFast(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number, arg6: $CallbackInfo): void;
        renderCube(arg0: $PoseStack, arg1: $GeoCube_, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        createVerticesOfQuad(arg0: $GeoQuad_, arg1: $Matrix4f, arg2: $Vector3f, arg3: $VertexConsumer, arg4: number, arg5: number, arg6: number): void;
        preApplyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        postRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        reRender(arg0: $BakedGeoModel_, arg1: $PoseStack, arg2: $MultiBufferSource_, arg3: T, arg4: $RenderType, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number, arg9: number): void;
        scaleModelForRender(arg0: number, arg1: number, arg2: $PoseStack, arg3: T, arg4: $BakedGeoModel_, arg5: boolean, arg6: number, arg7: number, arg8: number): void;
        applyRenderLayersForBone(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        checkAndRefreshBuffer(arg0: boolean, arg1: $VertexConsumer, arg2: $MultiBufferSource_, arg3: $RenderType): $VertexConsumer;
        getMotionAnimThreshold(arg0: T): number;
        renderCubesOfBone(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        applyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        getPackedOverlay(arg0: T, arg1: number, arg2: number): number;
        getInstanceId(arg0: T): number;
        defaultRender(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number): void;
        getRenderColor(arg0: T, arg1: number, arg2: number): $Color;
        renderChildBones(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        renderFinal(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number, arg8: number): void;
        constructor(arg0: $GeoModel<T>);
        get renderLayers(): $List<$GeoRenderLayer<T>>;
        get geoModel(): $GeoModel<T>;
        get animatable(): T;
    }
    export class $GeoReplacedEntityRenderer<E extends $Entity, T extends $GeoAnimatable> extends $EntityRenderer<E> implements $GeoRenderer<T> {
        getCurrentEntity(): E;
        getRenderType(arg0: T, arg1: $ResourceLocation_, arg2: $MultiBufferSource_, arg3: number): $RenderType;
        isShaking(arg0: T): boolean;
        getRenderLayers(): $List<$GeoRenderLayer<T>>;
        postRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        firePostRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): void;
        updateAnimatedTextureFrame(arg0: T): void;
        doPostRenderCleanup(): void;
        getGeoModel(): $GeoModel<T>;
        getAnimatable(): T;
        renderRecursively(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        applyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        addRenderLayer(arg0: $GeoRenderLayer<T>): $GeoReplacedEntityRenderer<E, T>;
        getPackedOverlay(arg0: T, arg1: number, arg2: number): number;
        actuallyRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        getInstanceId(arg0: T): number;
        renderFinal(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number, arg8: number): void;
        firePreRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): boolean;
        renderLeash<H extends $Entity, M extends $Mob>(arg0: M, arg1: number, arg2: $PoseStack, arg3: $MultiBufferSource_, arg4: H): void;
        fireCompileRenderLayersEvent(): void;
        getNameRenderCutoffDistance(arg0: E, arg1: T): number;
        withScale(arg0: number): $GeoReplacedEntityRenderer<E, T>;
        withScale(arg0: number, arg1: number): $GeoReplacedEntityRenderer<E, T>;
        preRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        handler$cae000$acceleratedrendering$renderCubesOfBoneFast(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number, arg6: $CallbackInfo): void;
        renderCube(arg0: $PoseStack, arg1: $GeoCube_, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        createVerticesOfQuad(arg0: $GeoQuad_, arg1: $Matrix4f, arg2: $Vector3f, arg3: $VertexConsumer, arg4: number, arg5: number, arg6: number): void;
        preApplyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        getTextureLocation(arg0: T): $ResourceLocation;
        reRender(arg0: $BakedGeoModel_, arg1: $PoseStack, arg2: $MultiBufferSource_, arg3: T, arg4: $RenderType, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number, arg9: number): void;
        scaleModelForRender(arg0: number, arg1: number, arg2: $PoseStack, arg3: T, arg4: $BakedGeoModel_, arg5: boolean, arg6: number, arg7: number, arg8: number): void;
        applyRenderLayersForBone(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        checkAndRefreshBuffer(arg0: boolean, arg1: $VertexConsumer, arg2: $MultiBufferSource_, arg3: $RenderType): $VertexConsumer;
        getMotionAnimThreshold(arg0: T): number;
        renderCubesOfBone(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        defaultRender(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number): void;
        getRenderColor(arg0: T, arg1: number, arg2: number): $Color;
        renderChildBones(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        shadowRadius: number;
        static LEASH_RENDER_STEPS: number;
        entityRenderDispatcher: $EntityRenderDispatcher;
        shadowStrength: number;
        static NAMETAG_SCALE: number;
        constructor(arg0: $EntityRendererProvider$Context, arg1: $GeoModel<T>, arg2: T);
        get currentEntity(): E;
        get renderLayers(): $List<$GeoRenderLayer<T>>;
        get geoModel(): $GeoModel<T>;
        get animatable(): T;
    }
    export class $GeoRenderer<T extends $GeoAnimatable> {
    }
    export interface $GeoRenderer<T extends $GeoAnimatable> {
        getRenderType(arg0: T, arg1: $ResourceLocation_, arg2: $MultiBufferSource_, arg3: number): $RenderType;
        handler$cae000$acceleratedrendering$renderCubesOfBoneFast(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number, arg6: $CallbackInfo): void;
        renderCube(arg0: $PoseStack, arg1: $GeoCube_, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        getRenderLayers(): $List<$GeoRenderLayer<T>>;
        createVerticesOfQuad(arg0: $GeoQuad_, arg1: $Matrix4f, arg2: $Vector3f, arg3: $VertexConsumer, arg4: number, arg5: number, arg6: number): void;
        preApplyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        postRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        getTextureLocation(arg0: T): $ResourceLocation;
        reRender(arg0: $BakedGeoModel_, arg1: $PoseStack, arg2: $MultiBufferSource_, arg3: T, arg4: $RenderType, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number, arg9: number): void;
        scaleModelForRender(arg0: number, arg1: number, arg2: $PoseStack, arg3: T, arg4: $BakedGeoModel_, arg5: boolean, arg6: number, arg7: number, arg8: number): void;
        applyRenderLayersForBone(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        firePostRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): void;
        updateAnimatedTextureFrame(arg0: T): void;
        doPostRenderCleanup(): void;
        checkAndRefreshBuffer(arg0: boolean, arg1: $VertexConsumer, arg2: $MultiBufferSource_, arg3: $RenderType): $VertexConsumer;
        getMotionAnimThreshold(arg0: T): number;
        getGeoModel(): $GeoModel<T>;
        getAnimatable(): T;
        renderCubesOfBone(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        renderRecursively(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        applyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        getPackedOverlay(arg0: T, arg1: number, arg2: number): number;
        actuallyRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        getInstanceId(arg0: T): number;
        defaultRender(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number): void;
        getRenderColor(arg0: T, arg1: number, arg2: number): $Color;
        renderChildBones(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        renderFinal(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number, arg8: number): void;
        firePreRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): boolean;
        fireCompileRenderLayersEvent(): void;
        preRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        get renderLayers(): $List<$GeoRenderLayer<T>>;
        get geoModel(): $GeoModel<T>;
        get animatable(): T;
    }
    export class $GeoBlockRenderer<T extends $BlockEntity> implements $GeoRenderer<T>, $BlockEntityRenderer<T> {
        render(arg0: T, arg1: number, arg2: $PoseStack, arg3: $MultiBufferSource_, arg4: number, arg5: number): void;
        getRenderLayers(): $List<$GeoRenderLayer<T>>;
        firePostRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): void;
        updateAnimatedTextureFrame(arg0: T): void;
        doPostRenderCleanup(): void;
        getGeoModel(): $GeoModel<T>;
        renderRecursively(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addRenderLayer(arg0: $GeoRenderLayer<T>): $GeoBlockRenderer<T>;
        actuallyRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        getInstanceId(arg0: T): number;
        firePreRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): boolean;
        fireCompileRenderLayersEvent(): void;
        withScale(arg0: number): $GeoBlockRenderer<T>;
        withScale(arg0: number, arg1: number): $GeoBlockRenderer<T>;
        preRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        getRenderType(arg0: T, arg1: $ResourceLocation_, arg2: $MultiBufferSource_, arg3: number): $RenderType;
        handler$cae000$acceleratedrendering$renderCubesOfBoneFast(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number, arg6: $CallbackInfo): void;
        renderCube(arg0: $PoseStack, arg1: $GeoCube_, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        createVerticesOfQuad(arg0: $GeoQuad_, arg1: $Matrix4f, arg2: $Vector3f, arg3: $VertexConsumer, arg4: number, arg5: number, arg6: number): void;
        preApplyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        postRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        getTextureLocation(arg0: T): $ResourceLocation;
        reRender(arg0: $BakedGeoModel_, arg1: $PoseStack, arg2: $MultiBufferSource_, arg3: T, arg4: $RenderType, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number, arg9: number): void;
        scaleModelForRender(arg0: number, arg1: number, arg2: $PoseStack, arg3: T, arg4: $BakedGeoModel_, arg5: boolean, arg6: number, arg7: number, arg8: number): void;
        applyRenderLayersForBone(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        checkAndRefreshBuffer(arg0: boolean, arg1: $VertexConsumer, arg2: $MultiBufferSource_, arg3: $RenderType): $VertexConsumer;
        getMotionAnimThreshold(arg0: T): number;
        renderCubesOfBone(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        applyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        getPackedOverlay(arg0: T, arg1: number, arg2: number): number;
        defaultRender(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number): void;
        getRenderColor(arg0: T, arg1: number, arg2: number): $Color;
        renderChildBones(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        renderFinal(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number, arg8: number): void;
        shouldRender(arg0: T, arg1: $Vec3_): boolean;
        getViewDistance(): number;
        shouldRenderOffScreen(arg0: T): boolean;
        getRenderBoundingBox(arg0: T): $AABB;
        getAnimatable(): T;
        constructor(arg0: $BlockEntityType_<T>);
        constructor(arg0: $GeoModel<T>);
        get renderLayers(): $List<$GeoRenderLayer<T>>;
        get geoModel(): $GeoModel<T>;
        get viewDistance(): number;
        get animatable(): T;
    }
    export class $GeoArmorRenderer<T extends $Item> extends $HumanoidModel<any> implements $GeoRenderer<T> {
        getCurrentEntity(): $Entity;
        getRenderType(arg0: T, arg1: $ResourceLocation_, arg2: $MultiBufferSource_, arg3: number): $RenderType;
        getRenderLayers(): $List<$GeoRenderLayer<T>>;
        firePostRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): void;
        updateAnimatedTextureFrame(arg0: T): void;
        doPostRenderCleanup(): void;
        getGeoModel(): $GeoModel<T>;
        getAnimatable(): T;
        renderRecursively(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        addRenderLayer(arg0: $GeoRenderLayer<T>): $GeoArmorRenderer<T>;
        actuallyRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        getInstanceId(arg0: T): number;
        getRenderColor(arg0: T, arg1: number, arg2: number): $Color;
        firePreRenderEvent(arg0: $PoseStack, arg1: $BakedGeoModel_, arg2: $MultiBufferSource_, arg3: number, arg4: number): boolean;
        fireCompileRenderLayersEvent(): void;
        withScale(arg0: number, arg1: number): $GeoArmorRenderer<T>;
        withScale(arg0: number): $GeoArmorRenderer<T>;
        preRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        getCurrentStack(): $ItemStack;
        prepForRender(arg0: $Entity, arg1: $ItemStack_, arg2: $EquipmentSlot_, arg3: $HumanoidModel<never>, arg4: $MultiBufferSource_, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): void;
        /**
         * @deprecated
         */
        prepForRender(arg0: $Entity, arg1: $ItemStack_, arg2: $EquipmentSlot_, arg3: $HumanoidModel<never>): void;
        applyBoneVisibilityByPart(arg0: $EquipmentSlot_, arg1: $ModelPart, arg2: $HumanoidModel<never>): void;
        /**
         * @deprecated
         */
        doArmourPostRenderCleanup(): void;
        getCurrentSlot(): $EquipmentSlot;
        getBodyBone(arg0: $GeoModel<T>): $GeoBone;
        scaleModelForBaby(arg0: $PoseStack, arg1: T, arg2: number, arg3: boolean): void;
        getLeftLegBone(arg0: $GeoModel<T>): $GeoBone;
        getLeftBootBone(arg0: $GeoModel<T>): $GeoBone;
        getRightLegBone(arg0: $GeoModel<T>): $GeoBone;
        getRightArmBone(arg0: $GeoModel<T>): $GeoBone;
        getLeftArmBone(arg0: $GeoModel<T>): $GeoBone;
        getHeadBone(arg0: $GeoModel<T>): $GeoBone;
        getRightBootBone(arg0: $GeoModel<T>): $GeoBone;
        handler$cae000$acceleratedrendering$renderCubesOfBoneFast(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number, arg6: $CallbackInfo): void;
        renderCube(arg0: $PoseStack, arg1: $GeoCube_, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        createVerticesOfQuad(arg0: $GeoQuad_, arg1: $Matrix4f, arg2: $Vector3f, arg3: $VertexConsumer, arg4: number, arg5: number, arg6: number): void;
        preApplyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        postRender(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: boolean, arg6: number, arg7: number, arg8: number, arg9: number): void;
        getTextureLocation(arg0: T): $ResourceLocation;
        reRender(arg0: $BakedGeoModel_, arg1: $PoseStack, arg2: $MultiBufferSource_, arg3: T, arg4: $RenderType, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number, arg9: number): void;
        scaleModelForRender(arg0: number, arg1: number, arg2: $PoseStack, arg3: T, arg4: $BakedGeoModel_, arg5: boolean, arg6: number, arg7: number, arg8: number): void;
        applyRenderLayersForBone(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        checkAndRefreshBuffer(arg0: boolean, arg1: $VertexConsumer, arg2: $MultiBufferSource_, arg3: $RenderType): $VertexConsumer;
        getMotionAnimThreshold(arg0: T): number;
        renderCubesOfBone(arg0: $PoseStack, arg1: $GeoBone, arg2: $VertexConsumer, arg3: number, arg4: number, arg5: number): void;
        applyRenderLayers(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: number, arg7: number, arg8: number): void;
        getPackedOverlay(arg0: T, arg1: number, arg2: number): number;
        defaultRender(arg0: $PoseStack, arg1: T, arg2: $MultiBufferSource_, arg3: $RenderType, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number): void;
        renderChildBones(arg0: $PoseStack, arg1: T, arg2: $GeoBone, arg3: $RenderType, arg4: $MultiBufferSource_, arg5: $VertexConsumer, arg6: boolean, arg7: number, arg8: number, arg9: number, arg10: number): void;
        renderFinal(arg0: $PoseStack, arg1: T, arg2: $BakedGeoModel_, arg3: $MultiBufferSource_, arg4: $VertexConsumer, arg5: number, arg6: number, arg7: number, arg8: number): void;
        scaleHead: boolean;
        young: boolean;
        rightArm: $ModelPart;
        static OVERLAY_SCALE: number;
        leftLeg: $ModelPart;
        riding: boolean;
        body: $ModelPart;
        swimAmount: number;
        head: $ModelPart;
        leftArm: $ModelPart;
        babyYHeadOffset: number;
        static TOOT_HORN_YROT_BASE: number;
        hat: $ModelPart;
        bodyYOffset: number;
        static TOOT_HORN_XROT_BASE: number;
        leftArmPose: $HumanoidModel$ArmPose;
        attackTime: number;
        babyZHeadOffset: number;
        babyHeadScale: number;
        static LEGGINGS_OVERLAY_SCALE: number;
        static HAT_OVERLAY_SCALE: number;
        crouching: boolean;
        rightLeg: $ModelPart;
        babyBodyScale: number;
        rightArmPose: $HumanoidModel$ArmPose;
        constructor<I extends T>(arg0: I);
        constructor(arg0: $GeoModel<T>);
        get currentEntity(): $Entity;
        get renderLayers(): $List<$GeoRenderLayer<T>>;
        get geoModel(): $GeoModel<T>;
        get animatable(): T;
        get currentStack(): $ItemStack;
        get currentSlot(): $EquipmentSlot;
    }
}
