import { $StructureTemplatePool, $StructurePoolElementType } from "@package/net/minecraft/world/level/levelgen/structure/pools";
import { $SensorType } from "@package/net/minecraft/world/entity/ai/sensing";
import { $MapCodec } from "@package/com/mojang/serialization";
import { $Recipe, $RecipeSerializer, $RecipeType } from "@package/net/minecraft/world/item/crafting";
import { $WorldPreset } from "@package/net/minecraft/world/level/levelgen/presets";
import { $EntityType } from "@package/net/minecraft/world/entity";
import { $ParticleType } from "@package/net/minecraft/core/particles";
import { $Schedule, $Activity } from "@package/net/minecraft/world/entity/schedule";
import { $PoolAliasBinding } from "@package/net/minecraft/world/level/levelgen/structure/pools/alias";
import { $NumberFormatType } from "@package/net/minecraft/network/chat/numbers";
import { $HeightProviderType } from "@package/net/minecraft/world/level/levelgen/heightproviders";
import { $CatVariant, $FrogVariant, $WolfVariant } from "@package/net/minecraft/world/entity/animal";
import { $Advancement, $CriterionTrigger } from "@package/net/minecraft/advancements";
import { $SoundEvent } from "@package/net/minecraft/sounds";
import { $Feature, $ConfiguredFeature } from "@package/net/minecraft/world/level/levelgen/feature";
import { $WorldCarver, $ConfiguredWorldCarver } from "@package/net/minecraft/world/level/levelgen/carver";
import { $MenuType } from "@package/net/minecraft/world/inventory";
import { $DataComponentType } from "@package/net/minecraft/core/component";
import { $TrimPattern, $TrimMaterial } from "@package/net/minecraft/world/item/armortrim";
import { $StructureType, $StructureSet, $Structure } from "@package/net/minecraft/world/level/levelgen/structure";
import { $StructurePlacementType } from "@package/net/minecraft/world/level/levelgen/structure/placement";
import { $LootScoreProviderType } from "@package/net/minecraft/world/level/storage/loot/providers/score";
import { $CreativeModeTab, $Item, $JukeboxSong, $ArmorMaterial, $Instrument } from "@package/net/minecraft/world/item";
import { $TrunkPlacerType } from "@package/net/minecraft/world/level/levelgen/feature/trunkplacers";
import { $ChatType } from "@package/net/minecraft/network/chat";
import { $BiomeSource, $Biome, $MultiNoiseBiomeSourceParameterList } from "@package/net/minecraft/world/level/biome";
import { $FlatLevelGeneratorPreset } from "@package/net/minecraft/world/level/levelgen/flat";
import { $MobEffect } from "@package/net/minecraft/world/effect";
import { $BlockStateProviderType } from "@package/net/minecraft/world/level/levelgen/feature/stateproviders";
import { $StructureProcessorList, $StructureProcessorType, $PosRuleTestType, $RuleTestType } from "@package/net/minecraft/world/level/levelgen/structure/templatesystem";
import { $ChunkGenerator } from "@package/net/minecraft/world/level/chunk";
import { $MemoryModuleType } from "@package/net/minecraft/world/entity/ai/memory";
import { $PlacedFeature, $PlacementModifierType } from "@package/net/minecraft/world/level/levelgen/placement";
import { $BlockPredicateType } from "@package/net/minecraft/world/level/levelgen/blockpredicates";
import { $IntProviderType, $FloatProviderType } from "@package/net/minecraft/util/valueproviders";
import { $StructurePieceType } from "@package/net/minecraft/world/level/levelgen/structure/pieces";
import { $Block } from "@package/net/minecraft/world/level/block";
import { $EnchantmentLocationBasedEffect, $EnchantmentValueEffect, $EnchantmentEntityEffect } from "@package/net/minecraft/world/item/enchantment/effects";
import { $DimensionType, $LevelStem } from "@package/net/minecraft/world/level/dimension";
import { $StatType } from "@package/net/minecraft/stats";
import { $LootNumberProviderType } from "@package/net/minecraft/world/level/storage/loot/providers/number";
import { $RuleBlockEntityModifierType } from "@package/net/minecraft/world/level/levelgen/structure/templatesystem/rule/blockentity";
import { $FoliagePlacerType } from "@package/net/minecraft/world/level/levelgen/feature/foliageplacers";
import { $NormalNoise$NoiseParameters } from "@package/net/minecraft/world/level/levelgen/synth";
import { $LootPoolEntryType } from "@package/net/minecraft/world/level/storage/loot/entries";
import { $GameEvent, $PositionSourceType } from "@package/net/minecraft/world/level/gameevent";
import { $Attribute } from "@package/net/minecraft/world/entity/ai/attributes";
import { $RootPlacerType } from "@package/net/minecraft/world/level/levelgen/feature/rootplacers";
import { $PaintingVariant } from "@package/net/minecraft/world/entity/decoration";
import { $Map, $Set } from "@package/java/util";
import { $Supplier } from "@package/java/util/function";
import { $DefaultedRegistry, $Registry } from "@package/net/minecraft/core";
import { $LevelBasedValue, $Enchantment } from "@package/net/minecraft/world/item/enchantment";
import { $ChunkStatus } from "@package/net/minecraft/world/level/chunk/status";
import { $MapDecorationType } from "@package/net/minecraft/world/level/saveddata/maps";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $SurfaceRules$ConditionSource, $DensityFunction, $SurfaceRules$RuleSource, $NoiseGeneratorSettings } from "@package/net/minecraft/world/level/levelgen";
import { $FeatureSizeType } from "@package/net/minecraft/world/level/levelgen/feature/featuresize";
import { $Level } from "@package/net/minecraft/world/level";
import { $PoiType } from "@package/net/minecraft/world/entity/ai/village/poi";
import { $TreeDecoratorType } from "@package/net/minecraft/world/level/levelgen/feature/treedecorators";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $LootItemFunctionType, $LootItemFunction } from "@package/net/minecraft/world/level/storage/loot/functions";
import { $VillagerType, $VillagerProfession } from "@package/net/minecraft/world/entity/npc";
import { $ItemSubPredicate$Type, $EntitySubPredicate } from "@package/net/minecraft/advancements/critereon";
import { $LootNbtProviderType } from "@package/net/minecraft/world/level/storage/loot/providers/nbt";
import { $Potion } from "@package/net/minecraft/world/item/alchemy";
import { $EnchantmentProvider } from "@package/net/minecraft/world/item/enchantment/providers";
import { $ResourceKey_, $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $LootItemConditionType, $LootItemCondition } from "@package/net/minecraft/world/level/storage/loot/predicates";
import { $ArgumentTypeInfo } from "@package/net/minecraft/commands/synchronization";
import { $DecoratedPotPattern, $BlockEntityType, $BannerPattern } from "@package/net/minecraft/world/level/block/entity";
import { $DamageType } from "@package/net/minecraft/world/damagesource";

declare module "@package/net/minecraft/core/registries" {
    export class $Registries {
        static elementsDirPath(registryKey: $ResourceKey_<$Registry<never>>): string;
        static levelStemToLevel(levelStem: $ResourceKey_<$LevelStem>): $ResourceKey<$Level>;
        static tagsDirPath(registryKey: $ResourceKey_<$Registry<never>>): string;
        static levelToLevelStem(levelStem: $ResourceKey_<$Level>): $ResourceKey<$LevelStem>;
        static ENCHANTMENT_LOCATION_BASED_EFFECT_TYPE: $ResourceKey<$Registry<$MapCodec<$EnchantmentLocationBasedEffect>>>;
        static VILLAGER_TYPE: $ResourceKey<$Registry<$VillagerType>>;
        static PROCESSOR_LIST: $ResourceKey<$Registry<$StructureProcessorList>>;
        static STAT_TYPE: $ResourceKey<$Registry<$StatType<never>>>;
        static TEMPLATE_POOL: $ResourceKey<$Registry<$StructureTemplatePool>>;
        static TREE_DECORATOR_TYPE: $ResourceKey<$Registry<$TreeDecoratorType<never>>>;
        static CONFIGURED_FEATURE: $ResourceKey<$Registry<$ConfiguredFeature<never, never>>>;
        static PARTICLE_TYPE: $ResourceKey<$Registry<$ParticleType<never>>>;
        static COMMAND_ARGUMENT_TYPE: $ResourceKey<$Registry<$ArgumentTypeInfo<never, never>>>;
        static ROOT_REGISTRY_NAME: $ResourceLocation;
        static TRIM_PATTERN: $ResourceKey<$Registry<$TrimPattern>>;
        static MATERIAL_RULE: $ResourceKey<$Registry<$MapCodec<$SurfaceRules$RuleSource>>>;
        static LOOT_FUNCTION_TYPE: $ResourceKey<$Registry<$LootItemFunctionType<never>>>;
        static POOL_ALIAS_BINDING: $ResourceKey<$Registry<$MapCodec<$PoolAliasBinding>>>;
        static PAINTING_VARIANT: $ResourceKey<$Registry<$PaintingVariant>>;
        static POINT_OF_INTEREST_TYPE: $ResourceKey<$Registry<$PoiType>>;
        static DAMAGE_TYPE: $ResourceKey<$Registry<$DamageType>>;
        static PREDICATE: $ResourceKey<$Registry<$LootItemCondition>>;
        static ITEM: $ResourceKey<$Registry<$Item>>;
        static VILLAGER_PROFESSION: $ResourceKey<$Registry<$VillagerProfession>>;
        static FROG_VARIANT: $ResourceKey<$Registry<$FrogVariant>>;
        static DIMENSION_TYPE: $ResourceKey<$Registry<$DimensionType>>;
        static BIOME_SOURCE: $ResourceKey<$Registry<$MapCodec<$BiomeSource>>>;
        static FLAT_LEVEL_GENERATOR_PRESET: $ResourceKey<$Registry<$FlatLevelGeneratorPreset>>;
        static ITEM_MODIFIER: $ResourceKey<$Registry<$LootItemFunction>>;
        static CARVER: $ResourceKey<$Registry<$WorldCarver<never>>>;
        static CUSTOM_STAT: $ResourceKey<$Registry<$ResourceLocation>>;
        static LOOT_NBT_PROVIDER_TYPE: $ResourceKey<$Registry<$LootNbtProviderType>>;
        static BIOME: $ResourceKey<$Registry<$Biome>>;
        static PLACEMENT_MODIFIER_TYPE: $ResourceKey<$Registry<$PlacementModifierType<never>>>;
        static DENSITY_FUNCTION_TYPE: $ResourceKey<$Registry<$MapCodec<$DensityFunction>>>;
        static MEMORY_MODULE_TYPE: $ResourceKey<$Registry<$MemoryModuleType<never>>>;
        static FLUID: $ResourceKey<$Registry<$Fluid>>;
        static ENCHANTMENT_LEVEL_BASED_VALUE_TYPE: $ResourceKey<$Registry<$MapCodec<$LevelBasedValue>>>;
        static RULE_BLOCK_ENTITY_MODIFIER: $ResourceKey<$Registry<$RuleBlockEntityModifierType<never>>>;
        static ENTITY_SUB_PREDICATE_TYPE: $ResourceKey<$Registry<$MapCodec<$EntitySubPredicate>>>;
        static RECIPE: $ResourceKey<$Registry<$Recipe<never>>>;
        static DATA_COMPONENT_TYPE: $ResourceKey<$Registry<$DataComponentType<never>>>;
        static DECORATED_POT_PATTERN: $ResourceKey<$Registry<$DecoratedPotPattern>>;
        static STRUCTURE_POOL_ELEMENT: $ResourceKey<$Registry<$StructurePoolElementType<never>>>;
        static LOOT_POOL_ENTRY_TYPE: $ResourceKey<$Registry<$LootPoolEntryType>>;
        static ENTITY_TYPE: $ResourceKey<$Registry<$EntityType<never>>>;
        static ROOT_PLACER_TYPE: $ResourceKey<$Registry<$RootPlacerType<never>>>;
        static POSITION_SOURCE_TYPE: $ResourceKey<$Registry<$PositionSourceType<never>>>;
        static BANNER_PATTERN: $ResourceKey<$Registry<$BannerPattern>>;
        static NUMBER_FORMAT_TYPE: $ResourceKey<$Registry<$NumberFormatType<never>>>;
        static ENCHANTMENT_PROVIDER: $ResourceKey<$Registry<$EnchantmentProvider>>;
        static FLOAT_PROVIDER_TYPE: $ResourceKey<$Registry<$FloatProviderType<never>>>;
        static RECIPE_TYPE: $ResourceKey<$Registry<$RecipeType<never>>>;
        static SOUND_EVENT: $ResourceKey<$Registry<$SoundEvent>>;
        static ENCHANTMENT_ENTITY_EFFECT_TYPE: $ResourceKey<$Registry<$MapCodec<$EnchantmentEntityEffect>>>;
        static GAME_EVENT: $ResourceKey<$Registry<$GameEvent>>;
        static MENU: $ResourceKey<$Registry<$MenuType<never>>>;
        static WORLD_PRESET: $ResourceKey<$Registry<$WorldPreset>>;
        static BLOCK_PREDICATE_TYPE: $ResourceKey<$Registry<$BlockPredicateType<never>>>;
        static CREATIVE_MODE_TAB: $ResourceKey<$Registry<$CreativeModeTab>>;
        static FOLIAGE_PLACER_TYPE: $ResourceKey<$Registry<$FoliagePlacerType<never>>>;
        static ENCHANTMENT: $ResourceKey<$Registry<$Enchantment>>;
        static ENCHANTMENT_VALUE_EFFECT_TYPE: $ResourceKey<$Registry<$MapCodec<$EnchantmentValueEffect>>>;
        static NOISE: $ResourceKey<$Registry<$NormalNoise$NoiseParameters>>;
        static FEATURE_SIZE_TYPE: $ResourceKey<$Registry<$FeatureSizeType<never>>>;
        static LOOT_NUMBER_PROVIDER_TYPE: $ResourceKey<$Registry<$LootNumberProviderType>>;
        static MATERIAL_CONDITION: $ResourceKey<$Registry<$MapCodec<$SurfaceRules$ConditionSource>>>;
        static BLOCK_TYPE: $ResourceKey<$Registry<$MapCodec<$Block>>>;
        static DIMENSION: $ResourceKey<$Registry<$Level>>;
        static WOLF_VARIANT: $ResourceKey<$Registry<$WolfVariant>>;
        static POTION: $ResourceKey<$Registry<$Potion>>;
        static LOOT_TABLE: $ResourceKey<$Registry<$LootTable>>;
        static SCHEDULE: $ResourceKey<$Registry<$Schedule>>;
        static MAP_DECORATION_TYPE: $ResourceKey<$Registry<$MapDecorationType>>;
        static CONFIGURED_CARVER: $ResourceKey<$Registry<$ConfiguredWorldCarver<never>>>;
        static CHUNK_GENERATOR: $ResourceKey<$Registry<$MapCodec<$ChunkGenerator>>>;
        static ATTRIBUTE: $ResourceKey<$Registry<$Attribute>>;
        static TRUNK_PLACER_TYPE: $ResourceKey<$Registry<$TrunkPlacerType<never>>>;
        static BLOCK: $ResourceKey<$Registry<$Block>>;
        static STRUCTURE_TYPE: $ResourceKey<$Registry<$StructureType<never>>>;
        static CHAT_TYPE: $ResourceKey<$Registry<$ChatType>>;
        static INT_PROVIDER_TYPE: $ResourceKey<$Registry<$IntProviderType<never>>>;
        static CAT_VARIANT: $ResourceKey<$Registry<$CatVariant>>;
        static STRUCTURE_PLACEMENT: $ResourceKey<$Registry<$StructurePlacementType<never>>>;
        static TRIM_MATERIAL: $ResourceKey<$Registry<$TrimMaterial>>;
        static LOOT_SCORE_PROVIDER_TYPE: $ResourceKey<$Registry<$LootScoreProviderType>>;
        static SENSOR_TYPE: $ResourceKey<$Registry<$SensorType<never>>>;
        static FEATURE: $ResourceKey<$Registry<$Feature<never>>>;
        static LOOT_CONDITION_TYPE: $ResourceKey<$Registry<$LootItemConditionType>>;
        static MOB_EFFECT: $ResourceKey<$Registry<$MobEffect>>;
        static STRUCTURE_PIECE: $ResourceKey<$Registry<$StructurePieceType>>;
        static RECIPE_SERIALIZER: $ResourceKey<$Registry<$RecipeSerializer<never>>>;
        static MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST: $ResourceKey<$Registry<$MultiNoiseBiomeSourceParameterList>>;
        static LEVEL_STEM: $ResourceKey<$Registry<$LevelStem>>;
        static BLOCK_STATE_PROVIDER_TYPE: $ResourceKey<$Registry<$BlockStateProviderType<never>>>;
        static TRIGGER_TYPE: $ResourceKey<$Registry<$CriterionTrigger<never>>>;
        static STRUCTURE_PROCESSOR: $ResourceKey<$Registry<$StructureProcessorType<never>>>;
        static STRUCTURE_SET: $ResourceKey<$Registry<$StructureSet>>;
        static RULE_TEST: $ResourceKey<$Registry<$RuleTestType<never>>>;
        static ENCHANTMENT_EFFECT_COMPONENT_TYPE: $ResourceKey<$Registry<$DataComponentType<never>>>;
        static BLOCK_ENTITY_TYPE: $ResourceKey<$Registry<$BlockEntityType<never>>>;
        static NOISE_SETTINGS: $ResourceKey<$Registry<$NoiseGeneratorSettings>>;
        static STRUCTURE: $ResourceKey<$Registry<$Structure>>;
        static ADVANCEMENT: $ResourceKey<$Registry<$Advancement>>;
        static ARMOR_MATERIAL: $ResourceKey<$Registry<$ArmorMaterial>>;
        static DENSITY_FUNCTION: $ResourceKey<$Registry<$DensityFunction>>;
        static JUKEBOX_SONG: $ResourceKey<$Registry<$JukeboxSong>>;
        static INSTRUMENT: $ResourceKey<$Registry<$Instrument>>;
        static ITEM_SUB_PREDICATE_TYPE: $ResourceKey<$Registry<$ItemSubPredicate$Type<never>>>;
        static CHUNK_STATUS: $ResourceKey<$Registry<$ChunkStatus>>;
        static HEIGHT_PROVIDER_TYPE: $ResourceKey<$Registry<$HeightProviderType<never>>>;
        static ENCHANTMENT_PROVIDER_TYPE: $ResourceKey<$Registry<$MapCodec<$EnchantmentProvider>>>;
        static PLACED_FEATURE: $ResourceKey<$Registry<$PlacedFeature>>;
        static ACTIVITY: $ResourceKey<$Registry<$Activity>>;
        static POS_RULE_TEST: $ResourceKey<$Registry<$PosRuleTestType<never>>>;
        constructor();
    }
    export class $BuiltInRegistries {
        static bootStrap(): void;
        static createContents(): void;
        static getVanillaRegistrationOrder(): $Set<$ResourceLocation>;
        static FOLIAGE_PLACER_TYPE: $Registry<$FoliagePlacerType<never>>;
        static POOL_ALIAS_BINDING_TYPE: $Registry<$MapCodec<$PoolAliasBinding>>;
        static VILLAGER_TYPE: $DefaultedRegistry<$VillagerType>;
        static ENCHANTMENT_LOCATION_BASED_EFFECT_TYPE: $Registry<$MapCodec<$EnchantmentLocationBasedEffect>>;
        static STAT_TYPE: $Registry<$StatType<never>>;
        static TREE_DECORATOR_TYPE: $Registry<$TreeDecoratorType<never>>;
        static PARTICLE_TYPE: $Registry<$ParticleType<never>>;
        static ENCHANTMENT_VALUE_EFFECT_TYPE: $Registry<$MapCodec<$EnchantmentValueEffect>>;
        static LOOT_NUMBER_PROVIDER_TYPE: $Registry<$LootNumberProviderType>;
        static FEATURE_SIZE_TYPE: $Registry<$FeatureSizeType<never>>;
        static COMMAND_ARGUMENT_TYPE: $Registry<$ArgumentTypeInfo<never, never>>;
        static MATERIAL_CONDITION: $Registry<$MapCodec<$SurfaceRules$ConditionSource>>;
        static BLOCK_TYPE: $Registry<$MapCodec<$Block>>;
        static MATERIAL_RULE: $Registry<$MapCodec<$SurfaceRules$RuleSource>>;
        static POTION: $Registry<$Potion>;
        static SCHEDULE: $Registry<$Schedule>;
        static LOOT_FUNCTION_TYPE: $Registry<$LootItemFunctionType<never>>;
        static MAP_DECORATION_TYPE: $Registry<$MapDecorationType>;
        static POINT_OF_INTEREST_TYPE: $Registry<$PoiType>;
        static CHUNK_GENERATOR: $Registry<$MapCodec<$ChunkGenerator>>;
        static ATTRIBUTE: $Registry<$Attribute>;
        static TRUNK_PLACER_TYPE: $Registry<$TrunkPlacerType<never>>;
        static BLOCK: $DefaultedRegistry<$Block>;
        static STRUCTURE_TYPE: $Registry<$StructureType<never>>;
        static INT_PROVIDER_TYPE: $Registry<$IntProviderType<never>>;
        static ITEM: $DefaultedRegistry<$Item>;
        static CAT_VARIANT: $Registry<$CatVariant>;
        static VILLAGER_PROFESSION: $DefaultedRegistry<$VillagerProfession>;
        static STRUCTURE_PLACEMENT: $Registry<$StructurePlacementType<never>>;
        static SENSOR_TYPE: $DefaultedRegistry<$SensorType<never>>;
        static LOOT_SCORE_PROVIDER_TYPE: $Registry<$LootScoreProviderType>;
        static LOOT_CONDITION_TYPE: $Registry<$LootItemConditionType>;
        static FEATURE: $Registry<$Feature<never>>;
        static TRIGGER_TYPES: $Registry<$CriterionTrigger<never>>;
        static FROG_VARIANT: $Registry<$FrogVariant>;
        static MOB_EFFECT: $Registry<$MobEffect>;
        static STRUCTURE_PIECE: $Registry<$StructurePieceType>;
        static BIOME_SOURCE: $Registry<$MapCodec<$BiomeSource>>;
        static RECIPE_SERIALIZER: $Registry<$RecipeSerializer<never>>;
        static REGISTRY: $Registry<$Registry<never>>;
        static CARVER: $Registry<$WorldCarver<never>>;
        static CUSTOM_STAT: $Registry<$ResourceLocation>;
        static LOOT_NBT_PROVIDER_TYPE: $Registry<$LootNbtProviderType>;
        static PLACEMENT_MODIFIER_TYPE: $Registry<$PlacementModifierType<never>>;
        static BLOCKSTATE_PROVIDER_TYPE: $Registry<$BlockStateProviderType<never>>;
        static DENSITY_FUNCTION_TYPE: $Registry<$MapCodec<$DensityFunction>>;
        static MEMORY_MODULE_TYPE: $DefaultedRegistry<$MemoryModuleType<never>>;
        static STRUCTURE_PROCESSOR: $Registry<$StructureProcessorType<never>>;
        static FLUID: $DefaultedRegistry<$Fluid>;
        static ENCHANTMENT_LEVEL_BASED_VALUE_TYPE: $Registry<$MapCodec<$LevelBasedValue>>;
        static RULE_BLOCK_ENTITY_MODIFIER: $Registry<$RuleBlockEntityModifierType<never>>;
        static ENTITY_SUB_PREDICATE_TYPE: $Registry<$MapCodec<$EntitySubPredicate>>;
        static RULE_TEST: $Registry<$RuleTestType<never>>;
        static ENCHANTMENT_EFFECT_COMPONENT_TYPE: $Registry<$DataComponentType<never>>;
        static BLOCK_ENTITY_TYPE: $Registry<$BlockEntityType<never>>;
        static DATA_COMPONENT_TYPE: $Registry<$DataComponentType<never>>;
        static DECORATED_POT_PATTERN: $Registry<$DecoratedPotPattern>;
        static STRUCTURE_POOL_ELEMENT: $Registry<$StructurePoolElementType<never>>;
        static ARMOR_MATERIAL: $Registry<$ArmorMaterial>;
        static LOOT_POOL_ENTRY_TYPE: $Registry<$LootPoolEntryType>;
        static ENTITY_TYPE: $DefaultedRegistry<$EntityType<never>>;
        static ROOT_PLACER_TYPE: $Registry<$RootPlacerType<never>>;
        static POSITION_SOURCE_TYPE: $Registry<$PositionSourceType<never>>;
        static INSTRUMENT: $Registry<$Instrument>;
        static ITEM_SUB_PREDICATE_TYPE: $Registry<$ItemSubPredicate$Type<never>>;
        static CHUNK_STATUS: $DefaultedRegistry<$ChunkStatus>;
        static NUMBER_FORMAT_TYPE: $Registry<$NumberFormatType<never>>;
        static HEIGHT_PROVIDER_TYPE: $Registry<$HeightProviderType<never>>;
        static RECIPE_TYPE: $Registry<$RecipeType<never>>;
        static FLOAT_PROVIDER_TYPE: $Registry<$FloatProviderType<never>>;
        static ENCHANTMENT_PROVIDER_TYPE: $Registry<$MapCodec<$EnchantmentProvider>>;
        static SOUND_EVENT: $Registry<$SoundEvent>;
        static GAME_EVENT: $DefaultedRegistry<$GameEvent>;
        static ENCHANTMENT_ENTITY_EFFECT_TYPE: $Registry<$MapCodec<$EnchantmentEntityEffect>>;
        static MENU: $Registry<$MenuType<never>>;
        static LOADERS: $Map<$ResourceLocation, $Supplier<never>>;
        static POS_RULE_TEST: $Registry<$PosRuleTestType<never>>;
        static ACTIVITY: $Registry<$Activity>;
        static BLOCK_PREDICATE_TYPE: $Registry<$BlockPredicateType<never>>;
        static CREATIVE_MODE_TAB: $Registry<$CreativeModeTab>;
        constructor();
        static get vanillaRegistrationOrder(): $Set<$ResourceLocation>;
    }
    export class $BuiltInRegistries$RegistryBootstrap<T> {
    }
    export interface $BuiltInRegistries$RegistryBootstrap<T> {
    }
    /**
     * Values that may be interpreted as {@link $BuiltInRegistries$RegistryBootstrap}.
     */
    export type $BuiltInRegistries$RegistryBootstrap_<T> = (() => void);
}
