import { $BlockStateFunction_ } from "@package/com/almostreliable/ponderjs/util";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $Outliner } from "@package/net/createmod/catnip/outliner";
import { $SceneBuilder, $EffectInstructions, $OverlayInstructions, $Selection, $SpecialInstructions, $SceneBuildingUtil, $WorldInstructions, $DebugInstructions } from "@package/net/createmod/ponder/api/scene";
import { $EntityType_, $Entity } from "@package/net/minecraft/world/entity";
import { $CallbackInfo } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $ParticleOptions } from "@package/net/minecraft/core/particles";
import { $Camera } from "@package/net/minecraft/client";
import { $List, $Collection_, $Set } from "@package/java/util";
import { $PonderUI } from "@package/net/createmod/ponder/foundation/ui";
import { $SuperRenderTypeBuffer } from "@package/net/createmod/catnip/render";
import { $Supplier_, $Function_, $Consumer_, $Supplier } from "@package/java/util/function";
import { $SoundEvent_, $SoundSource_ } from "@package/net/minecraft/sounds";
import { $HolderLookup$Provider, $BlockPos, $BlockPos_, $Direction_ } from "@package/net/minecraft/core";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $SceneBuilderExtension, $WorldInstructionExtension } from "@package/com/almostreliable/ponderjs/extension";
import { $AnimatedSceneElement, $EntityElement, $MinecartElement, $ParrotElement, $WorldSectionElement, $PonderElement, $InputElementBuilder, $MinecartElement$MinecartConstructor_, $TextElementBuilder, $ParrotPose, $ElementLink } from "@package/net/createmod/ponder/api/element";
import { $PonderInstruction } from "@package/net/createmod/ponder/foundation/instruction";
import { $Class, $Object } from "@package/java/lang";
import { $PonderLevel } from "@package/net/createmod/ponder/api/level";
import { $BoundingBox } from "@package/net/minecraft/world/level/levelgen/structure";
import { $Pair } from "@package/net/createmod/catnip/data";
import { $Level, $BlockGetter } from "@package/net/minecraft/world/level";
import { $TextElementBuilderJS } from "@package/com/almostreliable/ponderjs";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $ParticleEmitter, $ParticleEmitter_ } from "@package/net/createmod/ponder/api";
import { $Component_ } from "@package/net/minecraft/network/chat";
import { $LerpedFloat } from "@package/net/createmod/catnip/animation";
import { $PonderLocalization } from "@package/net/createmod/ponder/foundation/registration";
import { $ParticleInstructions } from "@package/com/almostreliable/ponderjs/particles";
import { $Property } from "@package/net/minecraft/world/level/block/state/properties";
import { $StoryBoardEntry$SceneOrderingEntry, $StoryBoardEntry$SceneOrderingEntry_ } from "@package/net/createmod/ponder/api/registration";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $CustomPonderSceneElement } from "@package/com/almostreliable/ponderjs/api";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $ScreenElement } from "@package/net/createmod/catnip/gui/element";
import { $Pointing_ } from "@package/net/createmod/catnip/math";
import { $PonderSceneExtension } from "@package/dev/simulated_team/simulated/mixin_interface/ponder";
import { $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $Vec3, $Vec2, $Vec3_ } from "@package/net/minecraft/world/phys";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
export * as element from "@package/net/createmod/ponder/foundation/element";
export * as instruction from "@package/net/createmod/ponder/foundation/instruction";
export * as registration from "@package/net/createmod/ponder/foundation/registration";
export * as ui from "@package/net/createmod/ponder/foundation/ui";

declare module "@package/net/createmod/ponder/foundation" {
    export class $PonderScene implements $PonderSceneExtension {
        fadeOut(): void;
        getTransform(): $PonderScene$SceneTransform;
        getScaleFactor(): number;
        runWith<E extends $PonderElement>(arg0: $ElementLink<E>, arg1: $Consumer_<E>): void;
        reset(): void;
        begin(): void;
        builder(): $SceneBuilder;
        getBounds(): $BoundingBox;
        getLocation(): $ResourceLocation;
        resolve<E extends $PonderElement>(arg0: $ElementLink<E>): E;
        forEach<T extends $PonderElement>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        forEach(arg0: $Consumer_<$PonderElement>): void;
        getId(): $ResourceLocation;
        getString(arg0: string): string;
        tick(): void;
        getTotalTime(): number;
        getTitle(): string;
        getNamespace(): string;
        addElement(arg0: $PonderElement): void;
        applyTo<E extends $PonderElement, F>(arg0: $ElementLink<E>, arg1: $Function_<E, F>): F;
        forEachVisible<T extends $PonderElement>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        getElements(): $Set<$PonderElement>;
        renderOverlay(arg0: $PonderUI, arg1: $GuiGraphics, arg2: number): void;
        getBaseWorldSection(): $WorldSectionElement;
        getBasePlateOffsetX(): number;
        getBasePlateOffsetZ(): number;
        shouldHidePlatformShadow(): boolean;
        simulated$getShadowOffset(arg0: number): $Vec3;
        simulated$setScaleFactor(arg0: number): void;
        simulated$setShadowOffset(arg0: $Vec3_): void;
        simulated$getYOffset(arg0: number): number;
        simulated$moveShadowOffset(arg0: $Vec3_): void;
        simulated$setYOffset(arg0: number): void;
        getOrderingEntries(): $List<$StoryBoardEntry$SceneOrderingEntry>;
        getTags(): $List<$PonderTag>;
        getWorld(): $PonderLevel;
        getSceneBuildingUtil(): $SceneBuildingUtil;
        getYOffset(): number;
        simulated$toggleRenderBasePlateShadow(): void;
        redirect$eik000$simulated$onCameraSet(arg0: $PonderScene$SceneCamera, arg1: number, arg2: number, arg3: $SuperRenderTypeBuffer, arg4: $GuiGraphics, arg5: number): void;
        simulated$getBasePlateAnimationTimer(arg0: number): number;
        setFinished(arg0: boolean): void;
        handler$eik000$simulated$tailBegin(arg0: $CallbackInfo): void;
        simulated$setOldShadowOffset(arg0: $Vec3_): void;
        handler$eik000$simulated$headTick(arg0: $CallbackInfo): void;
        rayTraceScene(arg0: $Vec3_, arg1: $Vec3_): $Pair<$ItemStack, $BlockPos>;
        getSceneProgress(): number;
        getPointOfInterest(): $Vec3;
        addToSceneTime(arg0: number): void;
        renderScene(arg0: $SuperRenderTypeBuffer, arg1: $GuiGraphics, arg2: number): void;
        stopCounting(): void;
        markKeyframe(arg0: number): void;
        linkElement<E extends $PonderElement>(arg0: E, arg1: $ElementLink<E>): void;
        resolveOptional<E extends $PonderElement>(arg0: $ElementLink<E>): (E) | undefined;
        setPointOfInterest(arg0: $Vec3_): void;
        forEachWorldEntity<T extends $Entity>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        getKeyframeCount(): number;
        registerText(arg0: string): $Supplier<string>;
        registerText(arg0: string, ...arg1: $Object[]): $Supplier<string>;
        getKeyframeTime(arg0: number): number;
        setNextUpEnabled(arg0: boolean): void;
        isNextUpEnabled(): boolean;
        getBasePlateSize(): number;
        getCurrentTime(): number;
        simulated$getScale(arg0: number): number;
        getOutliner(): $Outliner;
        isFinished(): boolean;
        deselect(): void;
        seekToTime(arg0: number): void;
        static TITLE_KEY: string;
        constructor(arg0: $PonderLevel | null, arg1: $PonderLocalization, arg2: string, arg3: $ResourceLocation_, arg4: $Collection_<$ResourceLocation_>, arg5: $Collection_<$StoryBoardEntry$SceneOrderingEntry_>);
        get transform(): $PonderScene$SceneTransform;
        get scaleFactor(): number;
        get bounds(): $BoundingBox;
        get location(): $ResourceLocation;
        get id(): $ResourceLocation;
        get totalTime(): number;
        get title(): string;
        get namespace(): string;
        get elements(): $Set<$PonderElement>;
        get baseWorldSection(): $WorldSectionElement;
        get basePlateOffsetX(): number;
        get basePlateOffsetZ(): number;
        get orderingEntries(): $List<$StoryBoardEntry$SceneOrderingEntry>;
        get tags(): $List<$PonderTag>;
        get world(): $PonderLevel;
        get sceneBuildingUtil(): $SceneBuildingUtil;
        get YOffset(): number;
        get sceneProgress(): number;
        get keyframeCount(): number;
        get basePlateSize(): number;
        get currentTime(): number;
        get outliner(): $Outliner;
    }
    export class $PonderSceneBuilder implements $SceneBuilder, $SceneBuilderExtension {
        getDebug(): $DebugInstructions;
        idle(arg0: number): void;
        getSpecial(): $SpecialInstructions;
        title(arg0: string, arg1: string): void;
        getOverlay(): $OverlayInstructions;
        getEffects(): $EffectInstructions;
        getWorld(): $WorldInstructions;
        setNextUpEnabled(arg0: boolean): void;
        rotateCameraY(arg0: number): void;
        addInstruction(arg0: $Consumer_<$PonderScene>): void;
        addInstruction(arg0: $PonderInstruction): void;
        removeShadow(): void;
        setSceneOffsetY(arg0: number): void;
        markAsFinished(): void;
        addLazyKeyframe(): void;
        scaleSceneView(arg0: number): void;
        addKeyframe(): void;
        configureBasePlate(arg0: number, arg1: number, arg2: number): void;
        idleSeconds(arg0: number): void;
        showBasePlate(): void;
        getScene(): $PonderScene;
        ponderjs$getParticles(): $ParticleInstructions;
        text(arg0: number, arg1: $Component_): $TextElementBuilderJS;
        text(arg0: number, arg1: $Component_, arg2: $Vec3_): $TextElementBuilderJS;
        playSound(arg0: $SoundEvent_, arg1: $SoundSource_, arg2: number, arg3: number): void;
        playSound(arg0: $SoundEvent_, arg1: number): void;
        playSound(arg0: $SoundEvent_): void;
        showControls(arg0: number, arg1: $Vec3_, arg2: $Pointing_): $InputElementBuilder;
        encapsulateBounds(arg0: $BlockPos_): void;
        showStructure(arg0: number): void;
        showStructure(): void;
        sharedText(arg0: number, arg1: $ResourceLocation_, arg2: $Vec3_): $TextElementBuilder;
        sharedText(arg0: number, arg1: $ResourceLocation_): $TextElementBuilderJS;
        constructor(arg0: $PonderScene);
        get debug(): $DebugInstructions;
        get special(): $SpecialInstructions;
        get overlay(): $OverlayInstructions;
        get effects(): $EffectInstructions;
        get world(): $WorldInstructions;
        set nextUpEnabled(value: boolean);
        set sceneOffsetY(value: number);
        get scene(): $PonderScene;
    }
    export class $PonderSceneBuilder$PonderEffectInstructions implements $EffectInstructions {
        emitParticles(arg0: $Vec3_, arg1: $ParticleEmitter_, arg2: number, arg3: number): void;
        particleEmitterWithinBlockSpace<T extends $ParticleOptions>(arg0: T, arg1: $Vec3_): $ParticleEmitter;
        indicateRedstone(arg0: $BlockPos_): void;
        indicateSuccess(arg0: $BlockPos_): void;
        simpleParticleEmitter<T extends $ParticleOptions>(arg0: T, arg1: $Vec3_): $ParticleEmitter;
        createRedstoneParticles(arg0: $BlockPos_, arg1: number, arg2: number): void;
        constructor(arg0: $PonderSceneBuilder);
    }
    export class $PonderScene$SceneTransform {
        apply(arg0: $PoseStack, arg1: number): $PoseStack;
        apply(arg0: $PoseStack): $PoseStack;
        tick(): void;
        sceneToScreen(arg0: $Vec3_, arg1: number): $Vec2;
        screenToScene(arg0: number, arg1: number, arg2: number, arg3: number): $Vec3;
        updateSceneRVE(arg0: number): void;
        updateScreenParams(arg0: number, arg1: number, arg2: number): void;
        xRotation: $LerpedFloat;
        yRotation: $LerpedFloat;
        constructor(arg0: $PonderScene);
    }
    export class $PonderSceneBuilder$PonderWorldInstructions implements $WorldInstructions, $WorldInstructionExtension {
        setBlock(arg0: $BlockPos_, arg1: $BlockState_, arg2: boolean): void;
        createEntity(arg0: $Function_<$Level, $Entity>): $ElementLink<$EntityElement>;
        modifyEntity(arg0: $ElementLink<$EntityElement>, arg1: $Consumer_<$Entity>): void;
        destroyBlock(arg0: $BlockPos_): void;
        restoreBlocks(arg0: $Selection): void;
        showIndependentSectionImmediately(arg0: $Selection): $ElementLink<$WorldSectionElement>;
        incrementBlockBreakingProgress(arg0: $BlockPos_): void;
        cycleBlockProperty(arg0: $BlockPos_, arg1: $Property<never>): void;
        moveSection(arg0: $ElementLink<$WorldSectionElement>, arg1: $Vec3_, arg2: number): void;
        rotateSection(arg0: $ElementLink<$WorldSectionElement>, arg1: number, arg2: number, arg3: number, arg4: number): void;
        hideSection(arg0: $Selection, arg1: $Direction_): void;
        createItemEntity(arg0: $Vec3_, arg1: $Vec3_, arg2: $ItemStack_): $ElementLink<$EntityElement>;
        modifyEntities<T extends $Entity>(arg0: $Class<T>, arg1: $Consumer_<T>): void;
        glueBlockOnto(arg0: $BlockPos_, arg1: $Direction_, arg2: $ElementLink<$WorldSectionElement>): void;
        hideIndependentSection(arg0: $ElementLink<$WorldSectionElement>, arg1: $Direction_): void;
        showIndependentSection(arg0: $Selection, arg1: $Direction_): $ElementLink<$WorldSectionElement>;
        modifyBlockEntity<T extends $BlockEntity>(arg0: $BlockPos_, arg1: $Class<T>, arg2: $Consumer_<T>): void;
        replaceBlocks(arg0: $Selection, arg1: $BlockState_, arg2: boolean): void;
        showSection(arg0: $Selection, arg1: $Direction_): void;
        setBlocks(arg0: $Selection, arg1: $BlockState_, arg2: boolean): void;
        modifyBlockEntityNBT(arg0: $Selection, arg1: $Class<$BlockEntity>, arg2: $Consumer_<$CompoundTag>): void;
        modifyBlockEntityNBT(arg0: $Selection, arg1: $Class<$BlockEntity>, arg2: $Consumer_<$CompoundTag>, arg3: boolean): void;
        makeSectionIndependent(arg0: $Selection): $ElementLink<$WorldSectionElement>;
        toggleRedstonePower(arg0: $Selection): void;
        configureCenterOfRotation(arg0: $ElementLink<$WorldSectionElement>, arg1: $Vec3_): void;
        getHolderLookupProvider(): $HolderLookup$Provider;
        configureStabilization(arg0: $ElementLink<$WorldSectionElement>, arg1: $Vec3_): void;
        showSectionAndMerge(arg0: $Selection, arg1: $Direction_, arg2: $ElementLink<$WorldSectionElement>): void;
        modifyEntitiesInside<T extends $Entity>(arg0: $Class<T>, arg1: $Selection, arg2: $Consumer_<T>): void;
        setBlocks(arg0: $Selection, arg1: $BlockState_): void;
        setBlocks(arg0: $Selection, arg1: boolean, arg2: $BlockState_): void;
        createEntity(arg0: $EntityType_<never>, arg1: $Vec3_, arg2: $Consumer_<$Entity>): $ElementLink<$EntityElement>;
        createEntity(arg0: $EntityType_<never>, arg1: $Vec3_): $ElementLink<$EntityElement>;
        removeEntity(arg0: $ElementLink<$EntityElement>): void;
        addElement(arg0: number): $CustomPonderSceneElement;
        addElement(): $CustomPonderSceneElement;
        modifyBlock(arg0: $BlockPos_, arg1: $BlockStateFunction_, arg2: boolean): void;
        modifyBlocks(arg0: $Selection, arg1: $BlockStateFunction_): void;
        modifyBlocks(arg0: $Selection, arg1: boolean, arg2: $BlockStateFunction_): void;
        modifyBlocks(arg0: $Selection, arg1: $BlockStateFunction_, arg2: boolean): void;
        modifyBlockEntityNBT(arg0: $Selection, arg1: $Consumer_<$CompoundTag>): void;
        modifyBlockEntityNBT(arg0: $Selection, arg1: boolean, arg2: $Consumer_<$CompoundTag>): void;
        constructor(arg0: $PonderSceneBuilder);
        get holderLookupProvider(): $HolderLookup$Provider;
    }
    export class $PonderSceneBuilder$PonderSpecialInstructions implements $SpecialInstructions {
        rotateParrot(arg0: $ElementLink<$ParrotElement>, arg1: number, arg2: number, arg3: number, arg4: number): void;
        changeBirbPose(arg0: $ElementLink<$ParrotElement>, arg1: $Supplier_<$ParrotPose>): void;
        hideElement<T extends $AnimatedSceneElement>(arg0: $ElementLink<T>, arg1: $Direction_): void;
        createBirb(arg0: $Vec3_, arg1: $Supplier_<$ParrotPose>): $ElementLink<$ParrotElement>;
        moveParrot(arg0: $ElementLink<$ParrotElement>, arg1: $Vec3_, arg2: number): void;
        rotateCart(arg0: $ElementLink<$MinecartElement>, arg1: number, arg2: number): void;
        createCart(arg0: $Vec3_, arg1: number, arg2: $MinecartElement$MinecartConstructor_): $ElementLink<$MinecartElement>;
        moveCart(arg0: $ElementLink<$MinecartElement>, arg1: $Vec3_, arg2: number): void;
        movePointOfInterest(arg0: $Vec3_): void;
        constructor(arg0: $PonderSceneBuilder);
    }
    export class $PonderScene$SceneCamera extends $Camera {
        set(arg0: number, arg1: number): void;
        eyeHeightOld: number;
        static FOG_DISTANCE_SCALE: number;
        level: $BlockGetter;
        eyeHeight: number;
        initialized: boolean;
        static $assertionsDisabled: boolean;
        entity: $Entity;
        constructor();
    }
    export class $PonderTag implements $ScreenElement {
        getDescription(): string;
        getId(): $ResourceLocation;
        getTitle(): string;
        render(arg0: $GuiGraphics, arg1: number, arg2: number): void;
        getMainItem(): $ItemStack;
        constructor(arg0: $ResourceLocation_, arg1: $ResourceLocation_ | null, arg2: $ItemStack_, arg3: $ItemStack_);
        get description(): string;
        get id(): $ResourceLocation;
        get title(): string;
        get mainItem(): $ItemStack;
    }
}
