import { $RegistryBuilder } from "@package/net/neoforged/neoforge/registries";
import { $Codec } from "@package/com/mojang/serialization";
import { $CreativeModeTab, $Item, $CreativeModeTab$Builder, $Item$Properties } from "@package/net/minecraft/world/item";
import { $IEventBus } from "@package/net/neoforged/bus/api";
import { $MutableComponent } from "@package/net/minecraft/network/chat";
import { $MobCategory_, $Entity, $EntityType$EntityFactory_ } from "@package/net/minecraft/world/entity";
import { $BaseFlowingFluid$Flowing, $BaseFlowingFluid, $BaseFlowingFluid$Properties, $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $Collection } from "@package/java/util";
import { $NonNullUnaryOperator_, $NonNullFunction_, $NonNullSupplier_, $NonNullConsumer_, $NonNullBiFunction_ } from "@package/com/tterrag/registrate/util/nullness";
import { $BuilderCallback, $Builder, $FluidBuilder, $MenuBuilder$ForgeMenuFactory_, $MenuBuilder$ScreenFactory, $BlockBuilder, $EntityBuilder, $BlockEntityBuilder$BlockEntityFactory_, $ItemBuilder, $NoConfigBuilder, $MenuBuilder, $FluidBuilder$FluidTypeFactory_, $BlockEntityBuilder, $MenuBuilder$MenuFactory_ } from "@package/com/tterrag/registrate/builders";
import { $RegistryEntry } from "@package/com/tterrag/registrate/util/entry";
import { $Function_, $Consumer_ } from "@package/java/util/function";
import { $Registry } from "@package/net/minecraft/core";
import { $Screen } from "@package/net/minecraft/client/gui/screens";
import { $BlockBehaviour$Properties } from "@package/net/minecraft/world/level/block/state";
import { $CreativeModeTabModifier } from "@package/com/tterrag/registrate/util";
import { $ResourceLocation_, $ResourceKey_, $ResourceKey } from "@package/net/minecraft/resources";
import { $ProviderType_, $RegistrateProvider, $DataProviderInitializer } from "@package/com/tterrag/registrate/providers";
import { $Block } from "@package/net/minecraft/world/level/block";
import { $AbstractContainerMenu } from "@package/net/minecraft/world/inventory";
import { $Runnable_ } from "@package/java/lang";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
export * as providers from "@package/com/tterrag/registrate/providers";
export * as util from "@package/com/tterrag/registrate/util";
export * as builders from "@package/com/tterrag/registrate/builders";

declare module "@package/com/tterrag/registrate" {
    export class $AbstractRegistrate<S extends $AbstractRegistrate<S>> {
        simple<R, T extends R>(arg0: string, arg1: $ResourceKey_<$Registry<R>>, arg2: $NonNullSupplier_<T>): $RegistryEntry<R, T>;
        simple<R, T extends R, P>(arg0: P, arg1: $ResourceKey_<$Registry<R>>, arg2: $NonNullSupplier_<T>): $RegistryEntry<R, T>;
        simple<R, T extends R>(arg0: $ResourceKey_<$Registry<R>>, arg1: $NonNullSupplier_<T>): $RegistryEntry<R, T>;
        simple<R, T extends R, P>(arg0: P, arg1: string, arg2: $ResourceKey_<$Registry<R>>, arg3: $NonNullSupplier_<T>): $RegistryEntry<R, T>;
        static isDevEnvironment(): boolean;
        get<R, T extends R>(arg0: $ResourceKey_<$Registry<R>>): $RegistryEntry<R, T>;
        get<R, T extends R>(arg0: string, arg1: $ResourceKey_<$Registry<R>>): $RegistryEntry<R, T>;
        transform<R, T extends R, P, S2 extends $Builder<R, T, P, S2>>(arg0: $NonNullFunction_<S, S2>): S2;
        transform(arg0: $NonNullUnaryOperator_<S>): S;
        isRegistered<R>(arg0: $ResourceKey_<$Registry<R>>): boolean;
        entry<R, T extends R, P, S2 extends $Builder<R, T, P, S2>>(arg0: $NonNullBiFunction_<string, $BuilderCallback, S2>): S2;
        entry<R, T extends R, P, S2 extends $Builder<R, T, P, S2>>(arg0: string, arg1: $NonNullFunction_<$BuilderCallback, S2>): S2;
        generic<R, T extends R>(arg0: $ResourceKey_<$Registry<R>>, arg1: $NonNullSupplier_<T>): $NoConfigBuilder<R, T, S>;
        generic<R, T extends R, P>(arg0: P, arg1: string, arg2: $ResourceKey_<$Registry<R>>, arg3: $NonNullSupplier_<T>): $NoConfigBuilder<R, T, P>;
        generic<R, T extends R>(arg0: string, arg1: $ResourceKey_<$Registry<R>>, arg2: $NonNullSupplier_<T>): $NoConfigBuilder<R, T, S>;
        generic<R, T extends R, P>(arg0: P, arg1: $ResourceKey_<$Registry<R>>, arg2: $NonNullSupplier_<T>): $NoConfigBuilder<R, T, P>;
        block<T extends $Block>(arg0: string, arg1: $NonNullFunction_<$BlockBehaviour$Properties, T>): $BlockBuilder<T, S>;
        block<T extends $Block, P>(arg0: P, arg1: $NonNullFunction_<$BlockBehaviour$Properties, T>): $BlockBuilder<T, P>;
        block<T extends $Block, P>(arg0: P, arg1: string, arg2: $NonNullFunction_<$BlockBehaviour$Properties, T>): $BlockBuilder<T, P>;
        block<T extends $Block>(arg0: $NonNullFunction_<$BlockBehaviour$Properties, T>): $BlockBuilder<T, S>;
        object(arg0: string): S;
        getAll<R, T extends R>(arg0: $ResourceKey_<$Registry<R>>): $Collection<$RegistryEntry<R, T>>;
        item<T extends $Item, P>(arg0: P, arg1: $NonNullFunction_<$Item$Properties, T>): $ItemBuilder<T, P>;
        item<T extends $Item>(arg0: $NonNullFunction_<$Item$Properties, T>): $ItemBuilder<T, S>;
        item<T extends $Item, P>(arg0: P, arg1: string, arg2: $NonNullFunction_<$Item$Properties, T>): $ItemBuilder<T, P>;
        item<T extends $Item>(arg0: string, arg1: $NonNullFunction_<$Item$Properties, T>): $ItemBuilder<T, S>;
        getOptional<R, T extends R>(arg0: string, arg1: $ResourceKey_<$Registry<R>>): ($RegistryEntry<R, T>) | undefined;
        makeDatapackRegistry<R>(arg0: string, arg1: $Codec<R>): $ResourceKey<$Registry<R>>;
        makeDatapackRegistry<R>(arg0: string, arg1: $Codec<R>, arg2: $Codec<R> | null): $ResourceKey<$Registry<R>>;
        addRegisterCallback<R>(arg0: $ResourceKey_<$Registry<R>>, arg1: $Runnable_): S;
        addRegisterCallback<R, T extends R>(arg0: string, arg1: $ResourceKey_<$Registry<R>>, arg2: $NonNullConsumer_<T>): S;
        modifyCreativeModeTab(arg0: $ResourceKey_<$CreativeModeTab>, arg1: $Consumer_<$CreativeModeTabModifier>): S;
        getDataGenInitializer(): $DataProviderInitializer;
        addRawLang(arg0: string, arg1: string): $MutableComponent;
        addLang(arg0: string, arg1: $ResourceLocation_, arg2: string): $MutableComponent;
        addLang(arg0: string, arg1: $ResourceLocation_, arg2: string, arg3: string): $MutableComponent;
        getModid(): string;
        skipErrors(arg0: boolean): S;
        genData<T extends $RegistrateProvider>(arg0: $ProviderType_<T>, arg1: T): void;
        fluid<P>(arg0: P, arg1: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: $ResourceLocation_, arg2: $ResourceLocation_): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<T extends $BaseFlowingFluid, P>(arg0: P, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, P>;
        fluid(arg0: string, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid<T extends $BaseFlowingFluid>(arg0: string, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, S>;
        fluid<T extends $BaseFlowingFluid>(arg0: string, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $FluidBuilder$FluidTypeFactory_, arg4: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, S>;
        fluid<T extends $BaseFlowingFluid>(arg0: string, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $NonNullSupplier_<$FluidType>, arg4: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, S>;
        fluid<P>(arg0: P): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: string, arg2: $ResourceLocation_, arg3: $ResourceLocation_, arg4: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: string, arg2: $ResourceLocation_, arg3: $ResourceLocation_, arg4: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<T extends $BaseFlowingFluid, P>(arg0: P, arg1: string, arg2: $ResourceLocation_, arg3: $ResourceLocation_, arg4: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, P>;
        fluid<T extends $BaseFlowingFluid, P>(arg0: P, arg1: string, arg2: $ResourceLocation_, arg3: $ResourceLocation_, arg4: $FluidBuilder$FluidTypeFactory_, arg5: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, P>;
        fluid(arg0: string, arg1: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid<T extends $BaseFlowingFluid, P>(arg0: P, arg1: string, arg2: $ResourceLocation_, arg3: $ResourceLocation_, arg4: $NonNullSupplier_<$FluidType>, arg5: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, P>;
        fluid<T extends $BaseFlowingFluid, P>(arg0: P, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $FluidBuilder$FluidTypeFactory_, arg4: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, P>;
        fluid<T extends $BaseFlowingFluid, P>(arg0: P, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $NonNullSupplier_<$FluidType>, arg4: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, P>;
        fluid<P>(arg0: P, arg1: string): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: string, arg2: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: string, arg2: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid<P>(arg0: P, arg1: string, arg2: $ResourceLocation_, arg3: $ResourceLocation_): $FluidBuilder<$BaseFlowingFluid$Flowing, P>;
        fluid(arg0: $ResourceLocation_, arg1: $ResourceLocation_): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid(arg0: $ResourceLocation_, arg1: $ResourceLocation_, arg2: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid(arg0: $ResourceLocation_, arg1: $ResourceLocation_, arg2: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid<T extends $BaseFlowingFluid>(arg0: $ResourceLocation_, arg1: $ResourceLocation_, arg2: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, S>;
        fluid(arg0: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid(arg0: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid(): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid(arg0: string, arg1: $ResourceLocation_, arg2: $ResourceLocation_, arg3: $FluidBuilder$FluidTypeFactory_): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid(arg0: string, arg1: $ResourceLocation_, arg2: $ResourceLocation_): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid(arg0: string, arg1: $NonNullSupplier_<$FluidType>): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        fluid<T extends $BaseFlowingFluid>(arg0: $ResourceLocation_, arg1: $ResourceLocation_, arg2: $FluidBuilder$FluidTypeFactory_, arg3: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, S>;
        fluid<T extends $BaseFlowingFluid>(arg0: $ResourceLocation_, arg1: $ResourceLocation_, arg2: $NonNullSupplier_<$FluidType>, arg3: $NonNullFunction_<$BaseFlowingFluid$Properties, T>): $FluidBuilder<T, S>;
        fluid(arg0: string): $FluidBuilder<$BaseFlowingFluid$Flowing, S>;
        entity<T extends $Entity, P>(arg0: P, arg1: string, arg2: $EntityType$EntityFactory_<T>, arg3: $MobCategory_): $EntityBuilder<T, P>;
        entity<T extends $Entity, P>(arg0: P, arg1: $EntityType$EntityFactory_<T>, arg2: $MobCategory_): $EntityBuilder<T, P>;
        entity<T extends $Entity>(arg0: string, arg1: $EntityType$EntityFactory_<T>, arg2: $MobCategory_): $EntityBuilder<T, S>;
        entity<T extends $Entity>(arg0: $EntityType$EntityFactory_<T>, arg1: $MobCategory_): $EntityBuilder<T, S>;
        getDataProvider<P extends $RegistrateProvider>(arg0: $ProviderType_<P>): (P) | undefined;
        defaultCreativeTab(): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, S>;
        defaultCreativeTab<P>(arg0: P, arg1: string): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, P>;
        defaultCreativeTab(arg0: $Consumer_<$CreativeModeTab$Builder>): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, S>;
        defaultCreativeTab<P>(arg0: P): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, P>;
        defaultCreativeTab(arg0: string): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, S>;
        defaultCreativeTab<P>(arg0: P, arg1: $Consumer_<$CreativeModeTab$Builder>): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, P>;
        defaultCreativeTab<P>(arg0: P, arg1: string, arg2: $Consumer_<$CreativeModeTab$Builder>): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, P>;
        defaultCreativeTab(arg0: $ResourceKey_<$CreativeModeTab>): S;
        defaultCreativeTab(arg0: string, arg1: $Consumer_<$CreativeModeTab$Builder>): $NoConfigBuilder<$CreativeModeTab, $CreativeModeTab, S>;
        registerEventListeners(arg0: $IEventBus): S;
        blockEntity<T extends $BlockEntity>(arg0: string, arg1: $BlockEntityBuilder$BlockEntityFactory_<T>): $BlockEntityBuilder<T, S>;
        blockEntity<T extends $BlockEntity>(arg0: $BlockEntityBuilder$BlockEntityFactory_<T>): $BlockEntityBuilder<T, S>;
        blockEntity<T extends $BlockEntity, P>(arg0: P, arg1: string, arg2: $BlockEntityBuilder$BlockEntityFactory_<T>): $BlockEntityBuilder<T, P>;
        blockEntity<T extends $BlockEntity, P>(arg0: P, arg1: $BlockEntityBuilder$BlockEntityFactory_<T>): $BlockEntityBuilder<T, P>;
        setDataGenerator<P extends $RegistrateProvider, R>(arg0: $Builder<R, never, never, never>, arg1: $ProviderType_<P>, arg2: $NonNullConsumer_<P>): S;
        setDataGenerator<P extends $RegistrateProvider, R>(arg0: string, arg1: $ResourceKey_<$Registry<R>>, arg2: $ProviderType_<P>, arg3: $NonNullConsumer_<P>): S;
        addDataGenerator<T extends $RegistrateProvider>(arg0: $ProviderType_<T>, arg1: $NonNullConsumer_<T>): S;
        setModEventBus(arg0: $IEventBus | null): void;
        makeRegistry<R>(arg0: string, arg1: $Function_<$ResourceKey<$Registry<R>>, $RegistryBuilder<R>>): $ResourceKey<$Registry<R>>;
        getModEventBus(): $IEventBus;
        menu<T extends $AbstractContainerMenu, SC extends $Screen>(arg0: $MenuBuilder$ForgeMenuFactory_<T>, arg1: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, S>;
        menu<T extends $AbstractContainerMenu, SC extends $Screen, P>(arg0: P, arg1: string, arg2: $MenuBuilder$ForgeMenuFactory_<T>, arg3: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, P>;
        menu<T extends $AbstractContainerMenu, SC extends $Screen, P>(arg0: P, arg1: $MenuBuilder$ForgeMenuFactory_<T>, arg2: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, P>;
        menu<T extends $AbstractContainerMenu, SC extends $Screen>(arg0: string, arg1: $MenuBuilder$ForgeMenuFactory_<T>, arg2: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, S>;
        menu<T extends $AbstractContainerMenu, SC extends $Screen>(arg0: $MenuBuilder$MenuFactory_<T>, arg1: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, S>;
        menu<T extends $AbstractContainerMenu, SC extends $Screen>(arg0: string, arg1: $MenuBuilder$MenuFactory_<T>, arg2: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, S>;
        menu<T extends $AbstractContainerMenu, SC extends $Screen, P>(arg0: P, arg1: $MenuBuilder$MenuFactory_<T>, arg2: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, P>;
        menu<T extends $AbstractContainerMenu, SC extends $Screen, P>(arg0: P, arg1: string, arg2: $MenuBuilder$MenuFactory_<T>, arg3: $NonNullSupplier_<$MenuBuilder$ScreenFactory<T, SC>>): $MenuBuilder<T, SC, P>;
        static get devEnvironment(): boolean;
        get dataGenInitializer(): $DataProviderInitializer;
        get modid(): string;
    }
}
