import { $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey } from "@package/net/minecraft/tags";
import { $Item_, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $Camera } from "@package/io/github/mortuusars/exposure/world/camera";
import { $EntityType_, $Entity$RemovalReason, $LivingEntity, $Pose, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $UUID } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $SynchedEntityData, $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $InteractionResult, $InteractionHand_ } from "@package/net/minecraft/world";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $BlockPos } from "@package/net/minecraft/core";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $CameraItem } from "@package/io/github/mortuusars/exposure/world/item/camera";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";

declare module "@package/io/github/mortuusars/exposure/world/entity" {
    export class $CameraHolder {
    }
    export interface $CameraHolder {
        getPlayerAwardedForExposure(): ($Player) | undefined;
        getServerPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        getServerPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        asHolderEntity(): $Entity;
        getPlayerExecutingExposure(): ($Player) | undefined;
        getExposureAuthorEntity(): $Entity;
        getExposureCameraOperator(): ($CameraOperator) | undefined;
        get playerAwardedForExposure(): ($Player) | undefined;
        get serverPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        get serverPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        get playerExecutingExposure(): ($Player) | undefined;
        get exposureAuthorEntity(): $Entity;
        get exposureCameraOperator(): ($CameraOperator) | undefined;
    }
    export class $CameraOperator {
    }
    export interface $CameraOperator {
        getExposureCameraActionAnim(partialTick: number): number;
        getActiveExposureCameraOptional(): ($Camera) | undefined;
        getActiveExposureCamera(): $Camera;
        asOperatorEntity(): $LivingEntity;
        removeActiveExposureCamera(): void;
        setActiveExposureCamera(camera: $Camera): void;
        get activeExposureCameraOptional(): ($Camera) | undefined;
    }
    export class $CameraStandEntity extends $Entity implements $CameraHolder {
        getPlayerAwardedForExposure(): ($Player) | undefined;
        playCameraRemoveSound(): void;
        getClosestPlayerInRange(): ($Player) | undefined;
        syncRotationToClients(): void;
        openAttachmentsMenu(player: $Player, hand: $InteractionHand_): $InteractionResult;
        isInInteractionRange(entity: $LivingEntity): boolean;
        destroy(dropItem: $Item_): void;
        canUse(player: $Player): boolean;
        release(): void;
        operator(): $CameraOperator;
        playBreakSound(): void;
        syncRotationToClientsIfNeeded(): void;
        getOwnerPlayer(): ($Player) | undefined;
        isCameraActive(): boolean;
        isInRangeForPhoto(player: $Player): boolean;
        playCameraSetSound(): void;
        startControlling(player: $Player, cameraItem: $CameraItem): void;
        startCooldown(cooldown: number): void;
        setOperator(operator: $CameraOperator): void;
        playPlaceSound(): void;
        getOperatorId(): number;
        stopControlling(): void;
        forceUpdate(): void;
        setOwnerPlayer(player: $Player): void;
        setCooldownTime(cooldown: number): void;
        isMalfunctioned(): boolean;
        setMalfunctioned(malfunctioned: boolean): void;
        getOwnerPlayerUuid(): $UUID;
        getCooldownTime(): number;
        playHitSound(): void;
        getCooldown(): number;
        isOnCooldown(): boolean;
        getCooldownPercent(): number;
        getPlayerExecutingExposure(): ($Player) | undefined;
        getExposureAuthorEntity(): $Entity;
        getExposureCameraOperator(): ($CameraOperator) | undefined;
        setCamera(cameraStack: $ItemStack_): void;
        getCamera(): $ItemStack;
        isClientSide(): boolean;
        getHurtDir(): number;
        getHurtTime(): number;
        setHurtTime(hurtTime: number): void;
        getDamage(): number;
        setDamage(damage: number): void;
        setHurtDir(hurtDir: number): void;
        setCooldown(cooldown: number): void;
        getServerPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        getServerPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        asHolderEntity(): $Entity;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        sodiumdynamiclights$luminance: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(entityType: $EntityType_<$CameraStandEntity>, level: $Level_);
        get playerAwardedForExposure(): ($Player) | undefined;
        get closestPlayerInRange(): ($Player) | undefined;
        get cameraActive(): boolean;
        get operatorId(): number;
        get ownerPlayerUuid(): $UUID;
        get onCooldown(): boolean;
        get cooldownPercent(): number;
        get playerExecutingExposure(): ($Player) | undefined;
        get exposureAuthorEntity(): $Entity;
        get exposureCameraOperator(): ($CameraOperator) | undefined;
        get clientSide(): boolean;
        get serverPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        get serverPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
    }
}
