import { $DefaultConstructorMarker } from "@package/kotlin/jvm/internal";
import { $Model_, $EssentialAsset, $Model } from "@package/gg/essential/mod";
import { $SerialDescriptor } from "@package/kotlinx/serialization/descriptors";
import { $CosmeticAssets, $CosmeticTier, $CosmeticTier_, $CosmeticSlot } from "@package/gg/essential/mod/cosmetics";
import { $Side } from "@package/gg/essential/model";
import { $List, $Map_, $Map, $Set, $Set_, $List_ } from "@package/java/util";
import { $SerializationConstructorMarker } from "@package/kotlinx/serialization/internal";
import { $Instant } from "@package/java/time";
import { $KSerializer } from "@package/kotlinx/serialization";
import { $CosmeticProperty$Variants$Variant, $CosmeticProperty$InterruptsEmote$Data, $CosmeticSetting$Variant, $CosmeticSetting, $CosmeticProperty } from "@package/gg/essential/mod/cosmetics/settings";
import { $EnumEntries } from "@package/kotlin/enums";
import { $Enum, $Object } from "@package/java/lang";
import { $CompositeEncoder } from "@package/kotlinx/serialization/encoding";
import { $Pair, $Lazy } from "@package/kotlin";

declare module "@package/gg/essential/network/cosmetics" {
    export class $Cosmetic {
        getLocalPath(): string;
        static copy$default(arg0: $Cosmetic, arg1: $CosmeticBase, arg2: $CosmeticStoreInfo, arg3: $List_<any>, arg4: number, arg5: $Object): $Cosmetic;
        getProperties(): $List<$CosmeticProperty>;
        properties<T extends $CosmeticProperty>(): $List<T>;
        getId(): string;
        copy(arg0: $CosmeticBase, arg1: $CosmeticStoreInfo, arg2: $List_<$Cosmetic$Diagnostic>): $Cosmetic;
        getSlot(): $CosmeticSlot;
        property<T extends $CosmeticProperty>(): T;
        getDisplayName(): string;
        getDisplayName(arg0: string): string;
        getDisplayNames(): $Map<string, string>;
        getVariants(): $List<$CosmeticProperty$Variants$Variant>;
        getBase(): $CosmeticBase;
        requiresUnlockAction(): boolean;
        getPrice(): number;
        isLegacy(): boolean;
        assets(arg0: string): $CosmeticAssets;
        assets(arg0: $List_<$CosmeticSetting>): $CosmeticAssets;
        getEmoteInterruptionTriggers(): $CosmeticProperty$InterruptsEmote$Data;
        static getPartnerCreator$annotations(): void;
        static getPartnerEvent$annotations(): void;
        static getEmoteInterruptionTriggers$annotations(): void;
        getFiles(): $Map<string, $EssentialAsset>;
        getStoreInfo(): $CosmeticStoreInfo;
        getDiagnostics(): $List<$Cosmetic$Diagnostic>;
        getAllProperties(): $List<$CosmeticProperty>;
        getShowTimerAfter(): $Instant;
        getBaseAssets(): $CosmeticAssets;
        isPurchasable(): boolean;
        isCosmeticFree(): boolean;
        getDefaultSide(): $Side;
        getDefaultVariant(): $CosmeticProperty$Variants$Variant;
        getAvailableAfter(): $Instant;
        getPartnerCreator(): boolean;
        getPartnerMod(): string;
        getAssetVariants(): $Map<string, $CosmeticAssets>;
        getAvailableUntil(): $Instant;
        isPartnered(): boolean;
        getPartnerEvent(): string;
        getPartnerName(): string;
        getDefaultVariantName(): string;
        getTags(): $Set<string>;
        component2(): $CosmeticStoreInfo;
        component3(): $List<$Cosmetic$Diagnostic>;
        static getPartnerMod$annotations(): void;
        getDefaultSortWeight(): number;
        getMutuallyExclusiveWith(): $Set<$CosmeticSlot>;
        getDefaultVariantSetting(): $CosmeticSetting$Variant;
        static isPartnered$annotations(): void;
        getDisabledProperties(): $List<$CosmeticProperty>;
        static getPartnerName$annotations(): void;
        getTier(): $CosmeticTier;
        component1(): $CosmeticBase;
        getCategories(): $Map<string, number>;
        constructor(arg0: $CosmeticBase, arg1: $CosmeticStoreInfo, arg2: $List_<any>, arg3: number, arg4: $DefaultConstructorMarker);
        constructor(arg0: $CosmeticBase, arg1: $CosmeticStoreInfo, arg2: $List_<$Cosmetic$Diagnostic>);
        get localPath(): string;
        get id(): string;
        get slot(): $CosmeticSlot;
        get displayNames(): $Map<string, string>;
        get variants(): $List<$CosmeticProperty$Variants$Variant>;
        get base(): $CosmeticBase;
        get price(): number;
        get legacy(): boolean;
        get emoteInterruptionTriggers(): $CosmeticProperty$InterruptsEmote$Data;
        static get partnerCreator$annotations(): void;
        static get partnerEvent$annotations(): void;
        static get emoteInterruptionTriggers$annotations(): void;
        get files(): $Map<string, $EssentialAsset>;
        get storeInfo(): $CosmeticStoreInfo;
        get diagnostics(): $List<$Cosmetic$Diagnostic>;
        get allProperties(): $List<$CosmeticProperty>;
        get showTimerAfter(): $Instant;
        get baseAssets(): $CosmeticAssets;
        get purchasable(): boolean;
        get cosmeticFree(): boolean;
        get defaultSide(): $Side;
        get defaultVariant(): $CosmeticProperty$Variants$Variant;
        get availableAfter(): $Instant;
        get partnerCreator(): boolean;
        get partnerMod(): string;
        get assetVariants(): $Map<string, $CosmeticAssets>;
        get availableUntil(): $Instant;
        get partnered(): boolean;
        get partnerEvent(): string;
        get partnerName(): string;
        get defaultVariantName(): string;
        get tags(): $Set<string>;
        static get partnerMod$annotations(): void;
        get defaultSortWeight(): number;
        get mutuallyExclusiveWith(): $Set<$CosmeticSlot>;
        get defaultVariantSetting(): $CosmeticSetting$Variant;
        static get partnered$annotations(): void;
        get disabledProperties(): $List<$CosmeticProperty>;
        static get partnerName$annotations(): void;
        get tier(): $CosmeticTier;
        get categories(): $Map<string, number>;
    }
    export class $CosmeticStoreInfo {
        component7(): number;
        component6(): $Map<string, number>;
        static copy$default(arg0: $CosmeticStoreInfo, arg1: number, arg2: $Set_<any>, arg3: $Instant, arg4: $Instant, arg5: $Instant, arg6: $Map_<any, any>, arg7: number, arg8: number, arg9: $Object): $CosmeticStoreInfo;
        copy(arg0: number, arg1: $Set_<string>, arg2: $Instant, arg3: $Instant, arg4: $Instant, arg5: $Map_<string, number>, arg6: number): $CosmeticStoreInfo;
        getPrice(): number;
        getShowTimerAfter(): $Instant;
        getAvailableAfter(): $Instant;
        getAvailableUntil(): $Instant;
        getTags(): $Set<string>;
        component2(): $Set<string>;
        component3(): $Instant;
        component4(): $Instant;
        component5(): $Instant;
        getDefaultSortWeight(): number;
        component1(): number;
        getCategories(): $Map<string, number>;
        constructor(arg0: number, arg1: $Set_<string>, arg2: $Instant, arg3: $Instant, arg4: $Instant, arg5: $Map_<string, number>, arg6: number);
        get price(): number;
        get showTimerAfter(): $Instant;
        get availableAfter(): $Instant;
        get availableUntil(): $Instant;
        get tags(): $Set<string>;
        get defaultSortWeight(): number;
        get categories(): $Map<string, number>;
    }
    export class $Cosmetic$Diagnostic {
        component7(): $Model;
        component6(): string;
        static copy$default(arg0: $Cosmetic$Diagnostic, arg1: $Cosmetic$Diagnostic$Type_, arg2: string, arg3: string, arg4: string, arg5: $Pair<any, any>, arg6: string, arg7: $Model_, arg8: number, arg9: $Object): $Cosmetic$Diagnostic;
        getMessage(): string;
        getType(): $Cosmetic$Diagnostic$Type;
        copy(arg0: $Cosmetic$Diagnostic$Type_, arg1: string, arg2: string, arg3: string, arg4: $Pair<number, number>, arg5: string, arg6: $Model_): $Cosmetic$Diagnostic;
        getFile(): string;
        getVariant(): string;
        static access$get$childSerializers$cp(): $Lazy<any>[];
        getStacktrace(): string;
        component2(): string;
        component3(): string;
        component4(): string;
        component5(): $Pair<number, number>;
        getSkin(): $Model;
        static write$Self$cosmetics(arg0: $Cosmetic$Diagnostic, arg1: $CompositeEncoder, arg2: $SerialDescriptor): void;
        component1(): $Cosmetic$Diagnostic$Type;
        getLineColumn(): $Pair<number, number>;
        static Companion: $Cosmetic$Diagnostic$Companion;
        constructor(arg0: number, arg1: $Cosmetic$Diagnostic$Type_, arg2: string, arg3: string, arg4: string, arg5: $Pair<any, any>, arg6: string, arg7: $Model_, arg8: $SerializationConstructorMarker);
        constructor(arg0: $Cosmetic$Diagnostic$Type_, arg1: string, arg2: string, arg3: string, arg4: $Pair<number, number>, arg5: string, arg6: $Model_);
        constructor(arg0: $Cosmetic$Diagnostic$Type_, arg1: string, arg2: string, arg3: string, arg4: $Pair<any, any>, arg5: string, arg6: $Model_, arg7: number, arg8: $DefaultConstructorMarker);
        get message(): string;
        get type(): $Cosmetic$Diagnostic$Type;
        get file(): string;
        get variant(): string;
        get stacktrace(): string;
        get skin(): $Model;
        get lineColumn(): $Pair<number, number>;
    }
    export class $Cosmetic$Diagnostic$Companion {
        static error$default(arg0: $Cosmetic$Diagnostic$Companion, arg1: string, arg2: string, arg3: string, arg4: $Pair<any, any>, arg5: string, arg6: $Model_, arg7: number, arg8: $Object): $Cosmetic$Diagnostic;
        serializer(): $KSerializer<$Cosmetic$Diagnostic>;
        error(arg0: string, arg1: string, arg2: string, arg3: $Pair<number, number>, arg4: string, arg5: $Model_): $Cosmetic$Diagnostic;
        warning(arg0: string, arg1: string, arg2: string, arg3: $Pair<number, number>, arg4: string, arg5: $Model_): $Cosmetic$Diagnostic;
        fatal(arg0: string, arg1: string, arg2: string, arg3: $Pair<number, number>, arg4: string, arg5: $Model_): $Cosmetic$Diagnostic;
        static fatal$default(arg0: $Cosmetic$Diagnostic$Companion, arg1: string, arg2: string, arg3: string, arg4: $Pair<any, any>, arg5: string, arg6: $Model_, arg7: number, arg8: $Object): $Cosmetic$Diagnostic;
        static warning$default(arg0: $Cosmetic$Diagnostic$Companion, arg1: string, arg2: string, arg3: string, arg4: $Pair<any, any>, arg5: string, arg6: $Model_, arg7: number, arg8: $Object): $Cosmetic$Diagnostic;
        constructor(arg0: $DefaultConstructorMarker);
    }
    export class $Cosmetic$Diagnostic$Type$Companion {
        serializer(): $KSerializer<$Cosmetic$Diagnostic$Type>;
        constructor(arg0: $DefaultConstructorMarker);
    }
    export class $CosmeticBase {
        component6(): $List<$CosmeticProperty>;
        static copy$default(arg0: $CosmeticBase, arg1: string, arg2: $CosmeticSlot, arg3: $CosmeticTier_, arg4: $Map_<any, any>, arg5: $Map_<any, any>, arg6: $List_<any>, arg7: number, arg8: $Object): $CosmeticBase;
        getId(): string;
        copy(arg0: string, arg1: $CosmeticSlot, arg2: $CosmeticTier_, arg3: $Map_<string, string>, arg4: $Map_<string, $EssentialAsset>, arg5: $List_<$CosmeticProperty>): $CosmeticBase;
        getSlot(): $CosmeticSlot;
        getDisplayNames(): $Map<string, string>;
        getFiles(): $Map<string, $EssentialAsset>;
        getAllProperties(): $List<$CosmeticProperty>;
        component2(): $CosmeticSlot;
        component3(): $CosmeticTier;
        component4(): $Map<string, string>;
        component5(): $Map<string, $EssentialAsset>;
        getTier(): $CosmeticTier;
        component1(): string;
        constructor(arg0: string, arg1: $CosmeticSlot, arg2: $CosmeticTier_, arg3: $Map_<string, string>, arg4: $Map_<string, $EssentialAsset>, arg5: $List_<$CosmeticProperty>);
        get id(): string;
        get slot(): $CosmeticSlot;
        get displayNames(): $Map<string, string>;
        get files(): $Map<string, $EssentialAsset>;
        get allProperties(): $List<$CosmeticProperty>;
        get tier(): $CosmeticTier;
    }
    export class $Cosmetic$Diagnostic$Type extends $Enum<$Cosmetic$Diagnostic$Type> {
        static values(): $Cosmetic$Diagnostic$Type[];
        static valueOf(arg0: string): $Cosmetic$Diagnostic$Type;
        static getEntries(): $EnumEntries<$Cosmetic$Diagnostic$Type>;
        static access$get$cachedSerializer$delegate$cp(): $Lazy<any>;
        static Companion: $Cosmetic$Diagnostic$Type$Companion;
        static Warning: $Cosmetic$Diagnostic$Type;
        static Error: $Cosmetic$Diagnostic$Type;
        static Fatal: $Cosmetic$Diagnostic$Type;
        static get entries(): $EnumEntries<$Cosmetic$Diagnostic$Type>;
    }
    /**
     * Values that may be interpreted as {@link $Cosmetic$Diagnostic$Type}.
     */
    export type $Cosmetic$Diagnostic$Type_ = "fatal" | "error" | "warning";
}
