import { $Supplier_ } from "@package/java/util/function";
import { $Matrix4x3dc, $Matrix4x3fc, $Matrix4dc, $Vector2dc, $Matrix4fc, $Matrix2dc, $Vector4fc, $Vector3dc, $Matrix3dc, $Matrix2fc, $Vector4dc, $Matrix3fc, $Matrix3x2fc, $Vector3ic, $Vector4ic, $Vector2fc, $Vector3fc, $Matrix3x2dc, $Vector2ic } from "@package/org/joml";

declare module "@package/foundry/veil/api/client/render/shader/uniform" {
    export class $ShaderUniformAccess {
        static of(...arg0: $ShaderUniformAccess[]): $ShaderUniformAccess;
        static wrapped(arg0: $Supplier_<$ShaderUniformAccess>): $ShaderUniformAccess;
        static EMPTY: $ShaderUniformAccess;
    }
    export interface $ShaderUniformAccess {
        setInt(arg0: number): void;
        setLong(arg0: number): void;
        setFloat(arg0: number): void;
        setDouble(arg0: number): void;
        setHandle(arg0: number): void;
        isValid(): boolean;
        setFloats(...arg0: number[]): void;
        setVector(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setVector(arg0: number, arg1: number): void;
        setVector(arg0: number, arg1: number, arg2: number): void;
        setVector(arg0: $Vector3fc): void;
        setVector(arg0: $Vector4fc): void;
        setVector(arg0: number[]): void;
        setVector(arg0: $Vector2fc): void;
        setVector64(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setVector64(arg0: $Vector2dc): void;
        setVector64(arg0: $Vector3dc): void;
        setVector64(arg0: $Vector4dc): void;
        setVector64(arg0: number[]): void;
        setVector64(arg0: number, arg1: number, arg2: number): void;
        setVector64(arg0: number, arg1: number): void;
        set64Vectors(...arg0: $Vector2dc[]): void;
        set64Vectors(...arg0: $Vector4dc[]): void;
        set64Vectors(...arg0: $Vector3dc[]): void;
        setVectorI64(arg0: number[]): void;
        setVectorI64(arg0: number, arg1: number, arg2: number): void;
        setVectorI64(arg0: number, arg1: number): void;
        setVectorI64(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setMatrix2x3(arg0: $Matrix3x2fc): void;
        setMatrix2x3(arg0: $Matrix3x2fc, arg1: boolean): void;
        setMatrix2x3(arg0: $Matrix3x2dc): void;
        setMatrix2x3(arg0: $Matrix3x2dc, arg1: boolean): void;
        setMatrix3x2(arg0: $Matrix3x2fc): void;
        setMatrix3x2(arg0: $Matrix3x2dc, arg1: boolean): void;
        setMatrix3x2(arg0: $Matrix3x2dc): void;
        setMatrix3x2(arg0: $Matrix3x2fc, arg1: boolean): void;
        setMatrix4x3(arg0: $Matrix4x3fc, arg1: boolean): void;
        setMatrix4x3(arg0: $Matrix4x3dc): void;
        setMatrix4x3(arg0: $Matrix4x3fc): void;
        setMatrix4x3(arg0: $Matrix4x3dc, arg1: boolean): void;
        setIVectors(...arg0: $Vector3ic[]): void;
        setIVectors(...arg0: $Vector4ic[]): void;
        setIVectors(...arg0: $Vector2ic[]): void;
        setMatrix3x4(arg0: $Matrix4x3fc): void;
        setMatrix3x4(arg0: $Matrix4x3fc, arg1: boolean): void;
        setMatrix3x4(arg0: $Matrix4x3dc): void;
        setMatrix3x4(arg0: $Matrix4x3dc, arg1: boolean): void;
        setVectorI(arg0: number, arg1: number, arg2: number): void;
        setVectorI(arg0: $Vector4ic): void;
        setVectorI(arg0: number[]): void;
        setVectorI(arg0: number, arg1: number): void;
        setVectorI(arg0: $Vector3ic): void;
        setVectorI(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setVectorI(arg0: $Vector2ic): void;
        setInts(...arg0: number[]): void;
        setLongs(...arg0: number[]): void;
        setVectors(...arg0: $Vector2fc[]): void;
        setVectors(...arg0: $Vector4fc[]): void;
        setVectors(...arg0: $Vector3fc[]): void;
        setHandles(...arg0: number[]): void;
        setMatrix(arg0: $Matrix3dc, arg1: boolean): void;
        setMatrix(arg0: $Matrix4dc, arg1: boolean): void;
        setMatrix(arg0: $Matrix2dc, arg1: boolean): void;
        setMatrix(arg0: $Matrix3fc): void;
        setMatrix(arg0: $Matrix2fc): void;
        setMatrix(arg0: $Matrix4fc): void;
        setMatrix(arg0: $Matrix2dc): void;
        setMatrix(arg0: $Matrix3dc): void;
        setMatrix(arg0: $Matrix4dc): void;
        setMatrix(arg0: $Matrix2fc, arg1: boolean): void;
        setMatrix(arg0: $Matrix3fc, arg1: boolean): void;
        setMatrix(arg0: $Matrix4fc, arg1: boolean): void;
        setDoubles(...arg0: number[]): void;
        set int(value: number);
        set long(value: number);
        set float(value: number);
        set double(value: number);
        set handle(value: number);
        get valid(): boolean;
        set floats(value: number[]);
        set ints(value: number[]);
        set longs(value: number[]);
        set handles(value: number[]);
        set doubles(value: number[]);
    }
}
