import { $Supplier_ } from "@package/java/util/function";
import { $CharSequence, $Enum } from "@package/java/lang";
import { $ByteBuffer } from "@package/java/nio";
import { $Vector2i, $Matrix4x3dc, $Matrix4x3fc, $Vector4fc, $Vector2dc, $Vector3dc, $Vector4f, $Vector4dc, $Matrix3f, $Vector2f, $Matrix3x2fc, $Vector2fc, $Vector4i, $Vector3fc, $Vector2ic, $Matrix4x3f, $Matrix4dc, $Matrix4f, $Matrix4fc, $Matrix2dc, $Matrix3dc, $Matrix2f, $Matrix2fc, $Matrix3fc, $Vector3ic, $Vector3f, $Vector4ic, $Vector3i, $Matrix3x2f, $Matrix3x2dc } from "@package/org/joml";

declare module "@package/foundry/veil/api/client/render/shader/uniform" {
    export class $ShaderUniform {
    }
    export interface $ShaderUniform extends $ShaderUniformAccess {
        invalidateCache(): void;
        getName(): string;
        getInt(): number;
        getLong(): number;
        getFloat(): number;
        getDouble(): number;
        getLocation(): number;
        getType(): $ShaderUniform$Type;
        getVector(arg0: $CharSequence, ...arg1: $Vector2f[]): void;
        getVector(arg0: $CharSequence, ...arg1: $Vector3f[]): void;
        getVector(arg0: $CharSequence, ...arg1: $Vector4f[]): void;
        getFloats(arg0: number[], arg1: number, arg2: number): void;
        getFloats(arg0: number[]): void;
        getFloats(): number[];
        getInts(): number[];
        getInts(arg0: number[], arg1: number, arg2: number): void;
        getInts(arg0: number[]): void;
        getMatrix(arg0: $CharSequence, arg1: $Matrix2f): void;
        getMatrix(arg0: $CharSequence, arg1: $Matrix3x2f): void;
        getMatrix(arg0: $CharSequence, arg1: $Matrix3f): void;
        getMatrix(arg0: $CharSequence, arg1: $Matrix4f): void;
        getMatrix(arg0: $CharSequence, arg1: $Matrix4x3f): void;
        getArrayLength(): number;
        getLongs(arg0: number[], arg1: number, arg2: number): void;
        getLongs(arg0: number[]): void;
        getLongs(): number[];
        getDoubles(arg0: number[]): void;
        getDoubles(): number[];
        getDoubles(arg0: number[], arg1: number, arg2: number): void;
        getVectori(arg0: $CharSequence, ...arg1: $Vector4i[]): void;
        getVectori(arg0: $CharSequence, ...arg1: $Vector2i[]): void;
        getVectori(arg0: $CharSequence, ...arg1: $Vector3i[]): void;
        get name(): string;
        get int(): number;
        get long(): number;
        get float(): number;
        get double(): number;
        get location(): number;
        get type(): $ShaderUniform$Type;
        get arrayLength(): number;
    }
    export class $ShaderUniformAccess {
        static of(...arg0: $ShaderUniformAccess[]): $ShaderUniformAccess;
        static wrapped(arg0: $Supplier_<$ShaderUniformAccess>): $ShaderUniformAccess;
        static EMPTY: $ShaderUniformAccess;
    }
    export interface $ShaderUniformAccess {
        setInt(arg0: number): void;
        setLong(arg0: number): void;
        setFloat(arg0: number): void;
        setDouble(arg0: number): void;
        setHandle(arg0: number): void;
        isValid(): boolean;
        setFloats(...arg0: number[]): void;
        setLongs(...arg0: number[]): void;
        setHandles(...arg0: number[]): void;
        setMatrix(arg0: $Matrix2dc): void;
        setMatrix(arg0: $Matrix4dc, arg1: boolean): void;
        setMatrix(arg0: $Matrix3dc, arg1: boolean): void;
        setMatrix(arg0: $Matrix3fc, arg1: boolean): void;
        setMatrix(arg0: $Matrix4fc, arg1: boolean): void;
        setMatrix(arg0: $Matrix2dc, arg1: boolean): void;
        setMatrix(arg0: $Matrix2fc): void;
        setMatrix(arg0: $Matrix3fc): void;
        setMatrix(arg0: $Matrix4fc): void;
        setMatrix(arg0: $Matrix2fc, arg1: boolean): void;
        setMatrix(arg0: $Matrix3dc): void;
        setMatrix(arg0: $Matrix4dc): void;
        setInts(...arg0: number[]): void;
        setVector(arg0: $Vector3fc): void;
        setVector(arg0: $Vector2fc): void;
        setVector(arg0: $Vector4fc): void;
        setVector(arg0: number[]): void;
        setVector(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setVector(arg0: number, arg1: number, arg2: number): void;
        setVector(arg0: number, arg1: number): void;
        setDoubles(...arg0: number[]): void;
        setVectorI(arg0: $Vector3ic): void;
        setVectorI(arg0: $Vector4ic): void;
        setVectorI(arg0: number[]): void;
        setVectorI(arg0: number, arg1: number): void;
        setVectorI(arg0: $Vector2ic): void;
        setVectorI(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setVectorI(arg0: number, arg1: number, arg2: number): void;
        setVectors(...arg0: $Vector4fc[]): void;
        setVectors(...arg0: $Vector3fc[]): void;
        setVectors(...arg0: $Vector2fc[]): void;
        setMatrix4x3(arg0: $Matrix4x3dc, arg1: boolean): void;
        setMatrix4x3(arg0: $Matrix4x3fc): void;
        setMatrix4x3(arg0: $Matrix4x3fc, arg1: boolean): void;
        setMatrix4x3(arg0: $Matrix4x3dc): void;
        setMatrix3x4(arg0: $Matrix4x3dc, arg1: boolean): void;
        setMatrix3x4(arg0: $Matrix4x3fc): void;
        setMatrix3x4(arg0: $Matrix4x3fc, arg1: boolean): void;
        setMatrix3x4(arg0: $Matrix4x3dc): void;
        setMatrix2x3(arg0: $Matrix3x2fc, arg1: boolean): void;
        setMatrix2x3(arg0: $Matrix3x2dc): void;
        setMatrix2x3(arg0: $Matrix3x2fc): void;
        setMatrix2x3(arg0: $Matrix3x2dc, arg1: boolean): void;
        set64Vectors(...arg0: $Vector4dc[]): void;
        set64Vectors(...arg0: $Vector2dc[]): void;
        set64Vectors(...arg0: $Vector3dc[]): void;
        setVectorI64(arg0: number, arg1: number, arg2: number): void;
        setVectorI64(arg0: number[]): void;
        setVectorI64(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setVectorI64(arg0: number, arg1: number): void;
        setMatrix3x2(arg0: $Matrix3x2fc): void;
        setMatrix3x2(arg0: $Matrix3x2dc): void;
        setMatrix3x2(arg0: $Matrix3x2dc, arg1: boolean): void;
        setMatrix3x2(arg0: $Matrix3x2fc, arg1: boolean): void;
        setIVectors(...arg0: $Vector3ic[]): void;
        setIVectors(...arg0: $Vector4ic[]): void;
        setIVectors(...arg0: $Vector2ic[]): void;
        setVector64(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setVector64(arg0: $Vector2dc): void;
        setVector64(arg0: number, arg1: number, arg2: number): void;
        setVector64(arg0: number, arg1: number): void;
        setVector64(arg0: $Vector3dc): void;
        setVector64(arg0: $Vector4dc): void;
        setVector64(arg0: number[]): void;
        set int(value: number);
        set long(value: number);
        set float(value: number);
        set double(value: number);
        set handle(value: number);
        get valid(): boolean;
        set floats(value: number[]);
        set longs(value: number[]);
        set handles(value: number[]);
        set ints(value: number[]);
        set doubles(value: number[]);
    }
    export class $ShaderUniform$Type extends $Enum<$ShaderUniform$Type> {
        static values(): $ShaderUniform$Type[];
        static valueOf(arg0: string): $ShaderUniform$Type;
        getBytes(): number;
        upload(arg0: number, arg1: number, arg2: $ByteBuffer): void;
        static byId(arg0: number): $ShaderUniform$Type;
        uploadAsMatrix(arg0: number, arg1: number, arg2: boolean, arg3: $ByteBuffer): void;
        static FLOAT: $ShaderUniform$Type;
        static UNSIGNED_LONG: $ShaderUniform$Type;
        static DOUBLE_VEC4: $ShaderUniform$Type;
        static UNSIGNED_LONG_VEC4: $ShaderUniform$Type;
        static UNSIGNED_INT: $ShaderUniform$Type;
        static UNSIGNED_LONG_VEC3: $ShaderUniform$Type;
        static DOUBLE_VEC2: $ShaderUniform$Type;
        static DOUBLE_VEC3: $ShaderUniform$Type;
        static UNSIGNED_LONG_VEC2: $ShaderUniform$Type;
        static DOUBLE_MATRIX3x4: $ShaderUniform$Type;
        static DOUBLE_MATRIX4x3: $ShaderUniform$Type;
        static DOUBLE_MATRIX4x4: $ShaderUniform$Type;
        static INT: $ShaderUniform$Type;
        static SAMPLER: $ShaderUniform$Type;
        static DOUBLE: $ShaderUniform$Type;
        static LONG_VEC3: $ShaderUniform$Type;
        static LONG_VEC4: $ShaderUniform$Type;
        static LONG: $ShaderUniform$Type;
        static LONG_VEC2: $ShaderUniform$Type;
        static MATRIX2x2: $ShaderUniform$Type;
        static MATRIX2x3: $ShaderUniform$Type;
        static MATRIX3x2: $ShaderUniform$Type;
        static INT_VEC4: $ShaderUniform$Type;
        static MATRIX3x3: $ShaderUniform$Type;
        static MATRIX2x4: $ShaderUniform$Type;
        static MATRIX4x2: $ShaderUniform$Type;
        static MATRIX3x4: $ShaderUniform$Type;
        static MATRIX4x3: $ShaderUniform$Type;
        static MATRIX4x4: $ShaderUniform$Type;
        static UNSIGNED_INT_VEC4: $ShaderUniform$Type;
        static UNSIGNED_INT_VEC2: $ShaderUniform$Type;
        static UNSIGNED_INT_VEC3: $ShaderUniform$Type;
        static FLOAT_VEC2: $ShaderUniform$Type;
        static FLOAT_VEC4: $ShaderUniform$Type;
        static FLOAT_VEC3: $ShaderUniform$Type;
        static DOUBLE_MATRIX2x3: $ShaderUniform$Type;
        static DOUBLE_MATRIX3x2: $ShaderUniform$Type;
        static DOUBLE_MATRIX3x3: $ShaderUniform$Type;
        static DOUBLE_MATRIX2x4: $ShaderUniform$Type;
        static DOUBLE_MATRIX4x2: $ShaderUniform$Type;
        static DOUBLE_MATRIX2x2: $ShaderUniform$Type;
        static INT_VEC3: $ShaderUniform$Type;
        static INT_VEC2: $ShaderUniform$Type;
        get bytes(): number;
    }
    /**
     * Values that may be interpreted as {@link $ShaderUniform$Type}.
     */
    export type $ShaderUniform$Type_ = "sampler" | "float" | "float_vec2" | "float_vec3" | "float_vec4" | "int" | "int_vec2" | "int_vec3" | "int_vec4" | "unsigned_int" | "unsigned_int_vec2" | "unsigned_int_vec3" | "unsigned_int_vec4" | "matrix2x2" | "matrix3x3" | "matrix4x4" | "matrix2x3" | "matrix3x2" | "matrix2x4" | "matrix4x2" | "matrix3x4" | "matrix4x3" | "double" | "double_vec2" | "double_vec3" | "double_vec4" | "long" | "long_vec2" | "long_vec3" | "long_vec4" | "unsigned_long" | "unsigned_long_vec2" | "unsigned_long_vec3" | "unsigned_long_vec4" | "double_matrix2x2" | "double_matrix3x3" | "double_matrix4x4" | "double_matrix2x3" | "double_matrix3x2" | "double_matrix2x4" | "double_matrix4x2" | "double_matrix3x4" | "double_matrix4x3";
}
