import { $Consumer_, $UnaryOperator_, $Supplier_, $BiFunction_, $Supplier } from "@package/java/util/function";
import { $HolderLookup$Provider, $Holder_ } from "@package/net/minecraft/core";
import { $Codec } from "@package/com/mojang/serialization";
import { $Item$TooltipContext, $TooltipFlag } from "@package/net/minecraft/world/item";
import { $Tag_, $Tag } from "@package/net/minecraft/nbt";
import { $Fluid, $Fluid_ } from "@package/net/minecraft/world/level/material";
import { $Component } from "@package/net/minecraft/network/chat";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $TooltipProvider } from "@package/net/minecraft/world/item/component";
import { $DataComponentType, $DataComponentMap_, $DataComponentType_, $DataComponentPatch_, $PatchedDataComponentMap, $DataComponentPatch, $DataComponentHolder } from "@package/net/minecraft/core/component";
import { $StreamCodec } from "@package/net/minecraft/network/codec";

declare module "@package/dev/architectury/fluid" {
    export class $FluidStack implements $DataComponentHolder {
        getName(): $Component;
        remove<T>(type: $DataComponentType_<T>): T;
        update<T>(type: $DataComponentType_<T>, component: T, updater: $UnaryOperator_<T>): T;
        update<T, U>(type: $DataComponentType_<T>, component: T, updateContext: U, updater: $BiFunction_<T, U, T>): T;
        isEmpty(): boolean;
        static empty(): $FluidStack;
        set<T>(type: $DataComponentType_<T>, component: T): T;
        static init(): void;
        write(provider: $HolderLookup$Provider, tag: $Tag_): $Tag;
        write(buf: $RegistryFriendlyByteBuf): void;
        static read(provider: $HolderLookup$Provider, tag: $Tag_): ($FluidStack) | undefined;
        static read(buf: $RegistryFriendlyByteBuf): $FluidStack;
        copy(): $FluidStack;
        static create(stack: $FluidStack, amount: number): $FluidStack;
        static create(fluid: $Holder_<$Fluid>, amount: number): $FluidStack;
        static create(fluid: $Holder_<$Fluid>, amount: number, patch: $DataComponentPatch_): $FluidStack;
        static create(fluid: $Supplier_<$Fluid>, amount: number): $FluidStack;
        static create(fluid: $Supplier_<$Fluid>, amount: number, patch: $DataComponentPatch_): $FluidStack;
        static create(fluid: $Fluid_, amount: number): $FluidStack;
        static create(fluid: $Fluid_, amount: number, patch: $DataComponentPatch_): $FluidStack;
        grow(amount: number): void;
        getTranslationKey(): string;
        getPatch(): $DataComponentPatch;
        applyComponents(patch: $DataComponentPatch_): void;
        applyComponents(patch: $DataComponentMap_): void;
        getAmount(): number;
        getComponents(): $PatchedDataComponentMap;
        shrink(amount: number): void;
        getFluid(): $Fluid;
        setAmount(amount: number): void;
        copyWithAmount(amount: number): $FluidStack;
        isFluidEqual(other: $FluidStack): boolean;
        getRawFluidSupplier(): $Supplier<$Fluid>;
        static bucketAmount(): number;
        getRawFluid(): $Fluid;
        isFluidStackEqual(other: $FluidStack): boolean;
        isComponentEqual(other: $FluidStack): boolean;
        get<T>(arg0: $DataComponentType_<T>): T;
        getOrDefault<T>(arg0: $DataComponentType_<T>, arg1: T): T;
        has(arg0: $DataComponentType_<never>): boolean;
        get<T>(arg0: $Supplier_<$DataComponentType<T>>): T;
        getOrDefault<T>(arg0: $Supplier_<$DataComponentType<T>>, arg1: T): T;
        has(arg0: $Supplier_<$DataComponentType<never>>): boolean;
        addToTooltip<T extends $TooltipProvider>(arg0: $DataComponentType_<T>, arg1: $Item$TooltipContext, arg2: $Consumer_<$Component>, arg3: $TooltipFlag): void;
        addToTooltip<T extends $TooltipProvider>(arg0: $Supplier_<$DataComponentType<T>>, arg1: $Item$TooltipContext, arg2: $Consumer_<$Component>, arg3: $TooltipFlag): void;
        static CODEC: $Codec<$FluidStack>;
        static STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $FluidStack>;
        get name(): $Component;
        get translationKey(): string;
        get patch(): $DataComponentPatch;
        get components(): $PatchedDataComponentMap;
        get fluid(): $Fluid;
        get rawFluidSupplier(): $Supplier<$Fluid>;
        get rawFluid(): $Fluid;
    }
}
