import { $FabricEntitySelectorReader } from "@package/net/fabricmc/fabric/api/command/v2";
import { $Component } from "@package/net/minecraft/network/chat";
import { $CompletableFuture } from "@package/java/util/concurrent";
import { $StringReader } from "@package/com/mojang/brigadier";
import { $EntityType_, $Entity } from "@package/net/minecraft/world/entity";
import { $List, $UUID_, $List_ } from "@package/java/util";
import { $MinMaxBounds$Doubles, $WrappedMinMaxBounds_, $MinMaxBounds$Ints_, $MinMaxBounds$Doubles_, $WrappedMinMaxBounds, $MinMaxBounds$Ints } from "@package/net/minecraft/advancements/critereon";
import { $CommandSourceStack } from "@package/net/minecraft/commands";
import { $Predicate, $Consumer_, $BiConsumer, $Consumer, $BiConsumer_, $BiFunction, $Predicate_, $Function_, $BiFunction_ } from "@package/java/util/function";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $DynamicCommandExceptionType, $SimpleCommandExceptionType } from "@package/com/mojang/brigadier/exceptions";
import { $Suggestions, $SuggestionsBuilder } from "@package/com/mojang/brigadier/suggestion";
import { $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $AABB_, $Vec3 } from "@package/net/minecraft/world/phys";
export * as options from "@package/net/minecraft/commands/arguments/selector/options";

declare module "@package/net/minecraft/commands/arguments/selector" {
    export class $EntitySelectorParser implements $FabricEntitySelectorReader {
        isLimited(): boolean;
        parse(): $EntitySelector;
        getLevel(): $MinMaxBounds$Ints;
        setLevel(level: $MinMaxBounds$Ints_): void;
        getOrder(): $BiConsumer<$Vec3, $List<$Entity>>;
        getY(): number;
        parseSelector(): void;
        getReader(): $StringReader;
        static allowSelectors<S>(arg0: S): boolean;
        getSelector(): $EntitySelector;
        getZ(): number;
        getX(): number;
        isTag(): boolean;
        setOrder(order: $BiConsumer_<$Vec3, $List<$Entity>>): void;
        setX(deltaX: number): void;
        setZ(deltaX: number): void;
        setY(deltaX: number): void;
        setDistance(distance: $MinMaxBounds$Doubles_): void;
        getDistance(): $MinMaxBounds$Doubles;
        setIncludesEntities(hasAdvancements: boolean): void;
        isTypeLimitedInversely(): boolean;
        setTypeLimitedInversely(): void;
        setHasGamemodeNotEquals(hasAdvancements: boolean): void;
        hasGamemodeNotEquals(): boolean;
        setHasNameNotEquals(hasAdvancements: boolean): void;
        setHasTeamNotEquals(hasAdvancements: boolean): void;
        setHasGamemodeEquals(hasAdvancements: boolean): void;
        hasScores(): boolean;
        setSorted(hasAdvancements: boolean): void;
        setLimited(hasAdvancements: boolean): void;
        setRotY(rotX: $WrappedMinMaxBounds_): void;
        isSorted(): boolean;
        setRotX(rotX: $WrappedMinMaxBounds_): void;
        getDeltaZ(): number;
        setDeltaZ(deltaX: number): void;
        setDeltaY(deltaX: number): void;
        getDeltaY(): number;
        getRotY(): $WrappedMinMaxBounds;
        getDeltaX(): number;
        setDeltaX(deltaX: number): void;
        getRotX(): $WrappedMinMaxBounds;
        isTypeLimited(): boolean;
        shouldInvertValue(): boolean;
        setSuggestions(suggestionHandler: $BiFunction_<$SuggestionsBuilder, $Consumer<$SuggestionsBuilder>, $CompletableFuture<$Suggestions>>): void;
        addPredicate(predicate: $Predicate_<$Entity>): void;
        hasAdvancements(): boolean;
        setHasScores(hasAdvancements: boolean): void;
        setHasAdvancements(hasAdvancements: boolean): void;
        setMaxResults(maxResults: number): void;
        finalizePredicates(): void;
        hasTeamNotEquals(): boolean;
        parseOptions(): void;
        hasGamemodeEquals(): boolean;
        isCurrentEntity(): boolean;
        setHasTeamEquals(hasAdvancements: boolean): void;
        hasNameEquals(): boolean;
        hasNameNotEquals(): boolean;
        setHasNameEquals(hasAdvancements: boolean): void;
        limitToType(type: $EntityType_<never>): void;
        hasTeamEquals(): boolean;
        setWorldLimited(): void;
        fillSuggestions(builder: $SuggestionsBuilder, consumer: $Consumer_<$SuggestionsBuilder>): $CompletableFuture<$Suggestions>;
        getCustomFlag(arg0: $ResourceLocation_): boolean;
        setCustomFlag(arg0: $ResourceLocation_, arg1: boolean): void;
        parseNameOrUUID(): void;
        static ERROR_SELECTORS_NOT_ALLOWED: $SimpleCommandExceptionType;
        static SUGGEST_NOTHING: $BiFunction<$SuggestionsBuilder, $Consumer<$SuggestionsBuilder>, $CompletableFuture<$Suggestions>>;
        static SYNTAX_NOT: string;
        static ORDER_RANDOM: $BiConsumer<$Vec3, $List<$Entity>>;
        static ERROR_EXPECTED_END_OF_OPTIONS: $SimpleCommandExceptionType;
        static SYNTAX_TAG: string;
        static ERROR_EXPECTED_OPTION_VALUE: $DynamicCommandExceptionType;
        static ERROR_UNKNOWN_SELECTOR_TYPE: $DynamicCommandExceptionType;
        static SYNTAX_OPTIONS_KEY_VALUE_SEPARATOR: string;
        static SYNTAX_SELECTOR_START: string;
        static ERROR_MISSING_SELECTOR_TYPE: $SimpleCommandExceptionType;
        static ERROR_INVALID_NAME_OR_UUID: $SimpleCommandExceptionType;
        static ORDER_NEAREST: $BiConsumer<$Vec3, $List<$Entity>>;
        static ORDER_FURTHEST: $BiConsumer<$Vec3, $List<$Entity>>;
        constructor(reader: $StringReader, allowSelectors: boolean);
        get reader(): $StringReader;
        get selector(): $EntitySelector;
        get tag(): boolean;
        set includesEntities(value: boolean);
        get typeLimited(): boolean;
        set suggestions(value: $BiFunction_<$SuggestionsBuilder, $Consumer<$SuggestionsBuilder>, $CompletableFuture<$Suggestions>>);
        set maxResults(value: number);
        get currentEntity(): boolean;
    }
    export class $EntitySelector {
        includesEntities(): boolean;
        findEntities(source: $CommandSourceStack): $List<$Entity>;
        findPlayers(source: $CommandSourceStack): $List<$ServerPlayer>;
        findSinglePlayer(source: $CommandSourceStack): $ServerPlayer;
        getMaxResults(): number;
        findSingleEntity(source: $CommandSourceStack): $Entity;
        isSelfSelector(): boolean;
        usesSelector(): boolean;
        isWorldLimited(): boolean;
        static joinNames(names: $List_<$Entity>): $Component;
        static ORDER_ARBITRARY: $BiConsumer<$Vec3, $List<$Entity>>;
        contextFreePredicates: $List<$Predicate<$Entity>>;
        static INFINITE: number;
        constructor(maxResults: number, includesEntities: boolean, worldLimited: boolean, contextFreePredicates: $List_<$Predicate_<$Entity>>, range: $MinMaxBounds$Doubles_, position: $Function_<$Vec3, $Vec3>, aabb: $AABB_ | null, order: $BiConsumer_<$Vec3, $List<$Entity>>, currentEntity: boolean, playerName: string | null, entityUUID: $UUID_ | null, type: $EntityType_<never> | null, usesSelector: boolean);
        get maxResults(): number;
        get selfSelector(): boolean;
        get worldLimited(): boolean;
    }
}
