import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $SerializableDataTicket } from "@package/software/bernie/geckolib/constant/dataticket";
import { $EntityType_, $Entity$RemovalReason, $LivingEntity, $Pose, $PortalProcessor, $EntityType, $Entity } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $UUID, $List } from "@package/java/util";
import { $AnimatableManager$ControllerRegistrar_ } from "@package/software/bernie/geckolib/animation";
import { $RandomSource } from "@package/net/minecraft/util";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $BaseNonAnimatableEntityBuilder, $BaseEntityBuilder } from "@package/net/liopyu/entityjs/builders/nonliving";
import { $AnimatableInstanceCache } from "@package/software/bernie/geckolib/animatable/instance";
import { $Object } from "@package/java/lang";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";
import { $Level_ } from "@package/net/minecraft/world/level";
import { $IntOpenHashSet } from "@package/it/unimi/dsi/fastutil/ints";
import { $TagKey } from "@package/net/minecraft/tags";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $PartEntity } from "@package/net/neoforged/neoforge/entity";
import { $ThrowableItemProjectile, $ItemSupplier, $AbstractArrow, $AbstractArrow$Pickup } from "@package/net/minecraft/world/entity/projectile";
import { $GeoAnimatable, $GeoEntity } from "@package/software/bernie/geckolib/animatable";
import { $ArrowEntityJSBuilder, $PartBuilder, $ProjectileAnimatableJSBuilder, $ProjectileEntityJSBuilder, $BaseEntityJSBuilder } from "@package/net/liopyu/entityjs/builders/nonliving/entityjs";
import { $SynchedEntityData, $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $Vec3 } from "@package/net/minecraft/world/phys";

declare module "@package/net/liopyu/entityjs/entities/nonliving/entityjs" {
    export class $IArrowEntityJS {
    }
    export interface $IArrowEntityJS {
        setPickUpItem(arg0: $ItemStack_): void;
        getArrowBuilder(): $BaseNonAnimatableEntityBuilder<never>;
        set pickUpItem(value: $ItemStack_);
        get arrowBuilder(): $BaseNonAnimatableEntityBuilder<never>;
    }
    export class $ProjectileAnimatableJS extends $ThrowableItemProjectile implements $IAnimatableJSNL, $ItemSupplier {
        entityName(): string;
        getAnimatableInstanceCache(): $AnimatableInstanceCache;
        getBuilder(): $BaseEntityBuilder<never>;
        registerControllers(arg0: $AnimatableManager$ControllerRegistrar_): void;
        getTypeId(): string;
        getTick(arg0: $Object): number;
        animatableCacheOverride(): $AnimatableInstanceCache;
        getBoneResetTime(): number;
        shouldPlayAnimsWhileGamePaused(): boolean;
        triggerAnim(arg0: string, arg1: string): void;
        setAnimData<D>(arg0: $SerializableDataTicket<D>, arg1: D): void;
        stopTriggeredAnim(arg0: string, arg1: string): void;
        getAnimData<D>(arg0: $SerializableDataTicket<D>): D;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        leftOwner: boolean;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        sodiumdynamiclights$luminance: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        builder: $ProjectileAnimatableJSBuilder;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        ownerUUID: $UUID;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(arg0: $ProjectileAnimatableJSBuilder, arg1: $EntityType_<$ThrowableItemProjectile>, arg2: $Level_);
        constructor(arg0: $ProjectileAnimatableJSBuilder, arg1: $EntityType_<$ThrowableItemProjectile>, arg2: $LivingEntity, arg3: $Level_);
        get animatableInstanceCache(): $AnimatableInstanceCache;
        get typeId(): string;
        get boneResetTime(): number;
    }
    export class $PartEntityJS<T extends $LivingEntity> extends $PartEntity<T> {
        entityName(): string;
        movePart(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        serializeNBT(arg0: $HolderLookup$Provider): T;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        parentMob: T;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        sodiumdynamiclights$luminance: number;
        height: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        name: string;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        width: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(arg0: T, arg1: string, arg2: number, arg3: number, arg4: $PartBuilder<T>);
    }
    export class $IAnimatableJSNL {
    }
    export interface $IAnimatableJSNL extends $GeoAnimatable, $GeoEntity {
        getType(): $EntityType<never>;
        registerControllers(arg0: $AnimatableManager$ControllerRegistrar_): void;
        getAnimatableInstanceCache(): $AnimatableInstanceCache;
        getTypeId(): string;
        getTick(arg0: $Object): number;
        getBuilder(): $BaseEntityBuilder<never>;
        get type(): $EntityType<never>;
        get animatableInstanceCache(): $AnimatableInstanceCache;
        get typeId(): string;
        get builder(): $BaseEntityBuilder<never>;
    }
    export class $ArrowEntityJS extends $AbstractArrow implements $IArrowEntityJS {
        entityName(): string;
        /**
         * @deprecated
         */
        setPickUpItem(arg0: $ItemStack_): void;
        getKnockback(): number;
        isMoving(): boolean;
        setKnockback(arg0: number): void;
        setDamageFunction(): number;
        getArrowBuilder(): $BaseNonAnimatableEntityBuilder<never>;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        leftOwner: boolean;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        sodiumdynamiclights$luminance: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        shakeTime: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        piercingIgnoreEntityIds: $IntOpenHashSet;
        invulnerableTime: number;
        piercedAndKilledEntities: $List<$Entity>;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        inGroundTime: number;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        builder: $ArrowEntityJSBuilder;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        ownerUUID: $UUID;
        inGround: boolean;
        firedFromWeapon: $ItemStack;
        walkDistO: number;
        pickup: $AbstractArrow$Pickup;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(arg0: $Level_, arg1: $ArrowEntityJSBuilder);
        constructor(arg0: $ArrowEntityJSBuilder, arg1: $Level_, arg2: $LivingEntity, arg3: $ItemStack_, arg4: $ItemStack_ | null);
        constructor(arg0: $ArrowEntityJSBuilder, arg1: $EntityType_<$AbstractArrow>, arg2: $Level_);
        set pickUpItem(value: $ItemStack_);
        get moving(): boolean;
        get arrowBuilder(): $BaseNonAnimatableEntityBuilder<never>;
    }
    export class $ProjectileEntityJS extends $ThrowableItemProjectile implements $IProjectileEntityJS, $ItemSupplier {
        entityName(): string;
        getProjectileBuilder(): $BaseNonAnimatableEntityBuilder<never>;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        leftOwner: boolean;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        sodiumdynamiclights$luminance: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        builder: $ProjectileEntityJSBuilder;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        ownerUUID: $UUID;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(arg0: $ProjectileEntityJSBuilder, arg1: $EntityType_<$ThrowableItemProjectile>, arg2: $Level_);
        constructor(arg0: $ProjectileEntityJSBuilder, arg1: $EntityType_<$ThrowableItemProjectile>, arg2: $LivingEntity, arg3: $Level_);
        get projectileBuilder(): $BaseNonAnimatableEntityBuilder<never>;
    }
    export class $IProjectileEntityJS {
    }
    export interface $IProjectileEntityJS {
        getProjectileBuilder(): $BaseNonAnimatableEntityBuilder<never>;
        get projectileBuilder(): $BaseNonAnimatableEntityBuilder<never>;
    }
    /**
     * Values that may be interpreted as {@link $IProjectileEntityJS}.
     */
    export type $IProjectileEntityJS_ = (() => $BaseNonAnimatableEntityBuilder<never>);
    export class $BaseEntityJS extends $Entity implements $IAnimatableJSNL {
        entityName(): string;
        getAnimatableInstanceCache(): $AnimatableInstanceCache;
        getBuilder(): $BaseEntityBuilder<never>;
        registerControllers(arg0: $AnimatableManager$ControllerRegistrar_): void;
        getTypeId(): string;
        getTick(arg0: $Object): number;
        animatableCacheOverride(): $AnimatableInstanceCache;
        getBoneResetTime(): number;
        shouldPlayAnimsWhileGamePaused(): boolean;
        triggerAnim(arg0: string, arg1: string): void;
        setAnimData<D>(arg0: $SerializableDataTicket<D>, arg1: D): void;
        stopTriggeredAnim(arg0: string, arg1: string): void;
        getAnimData<D>(arg0: $SerializableDataTicket<D>): D;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        sodiumdynamiclights$luminance: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(arg0: $BaseEntityJSBuilder, arg1: $EntityType_<never>, arg2: $Level_);
        get animatableInstanceCache(): $AnimatableInstanceCache;
        get builder(): $BaseEntityBuilder<never>;
        get typeId(): string;
        get boneResetTime(): number;
    }
}
