import { $Long2ObjectMap } from "@package/it/unimi/dsi/fastutil/longs";
import { $SodiumWorldRendererExtension } from "@package/dev/ryanhcode/sable/mixinterface/sublevel_render/sodium";
import { $RenderBuffers, $RenderType } from "@package/net/minecraft/client/renderer";
import { $Entity } from "@package/net/minecraft/world/entity";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $SodiumWorldRendererAccessor } from "@package/foundry/veil/forge/mixin/compat/sodium";
import { $Minecraft, $Camera } from "@package/net/minecraft/client";
import { $ClientSubLevel } from "@package/dev/ryanhcode/sable/sublevel";
import { $SortedSet, $Map_, $Map, $Collection } from "@package/java/util";
import { $SodiumWorldRendererExtension as $SodiumWorldRendererExtension$1 } from "@package/foundry/veil/forge/ext";
import { $ClientLevel } from "@package/net/minecraft/client/multiplayer";
import { $Consumer_ } from "@package/java/util/function";
import { $BlockDestructionProgress } from "@package/net/minecraft/server/level";
import { $RenderSectionManager, $ChunkRenderMatrices_ } from "@package/net/caffeinemc/mods/sodium/client/render/chunk";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $SortedRenderLists } from "@package/net/caffeinemc/mods/sodium/client/render/chunk/lists";
import { $LocalBooleanRef } from "@package/com/llamalad7/mixinextras/sugar/ref";
import { $Viewport } from "@package/net/caffeinemc/mods/sodium/client/render/viewport";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $SubLevelRenderSectionManager } from "@package/dev/ryanhcode/sable/sublevel/render/sodium";
export * as chunk from "@package/net/caffeinemc/mods/sodium/client/render/chunk";
export * as viewport from "@package/net/caffeinemc/mods/sodium/client/render/viewport";
export * as texture from "@package/net/caffeinemc/mods/sodium/client/render/texture";
export * as vertex from "@package/net/caffeinemc/mods/sodium/client/render/vertex";

declare module "@package/net/caffeinemc/mods/sodium/client/render" {
    export class $SodiumWorldRenderer implements $SodiumWorldRendererExtension$1, $SodiumWorldRendererAccessor, $SodiumWorldRendererExtension {
        static instance(): $SodiumWorldRenderer;
        reload(): void;
        setLevel(arg0: $ClientLevel): void;
        setupTerrain(arg0: $Camera, arg1: $Viewport, arg2: boolean, arg3: boolean): void;
        drawChunkLayer(arg0: $RenderType, arg1: $ChunkRenderMatrices_, arg2: number, arg3: number, arg4: number): void;
        isSectionReady(arg0: number, arg1: number, arg2: number): boolean;
        scheduleTerrainUpdate(): void;
        getChunksDebugString(): string;
        isTerrainRenderComplete(): boolean;
        getVisibleChunkCount(): number;
        renderBlockEntities(arg0: $PoseStack, arg1: $RenderBuffers, arg2: $Long2ObjectMap<$SortedSet<$BlockDestructionProgress>>, arg3: $Camera, arg4: number, arg5: $LocalBooleanRef): void;
        sable$freeRenderSectionManager(arg0: $ClientSubLevel): void;
        handler$gje000$sable$setupTerrain(arg0: $Camera, arg1: $Viewport, arg2: boolean, arg3: boolean, arg4: $CallbackInfo): void;
        veil$setSortedRenderLists(arg0: $SortedRenderLists): void;
        veil$getSortedRenderLists(): $SortedRenderLists;
        veil$setTaskLists(arg0: $Map_<any, any>): void;
        veil$getTaskLists(): $Map<any, any>;
        static instanceNullable(): $SodiumWorldRenderer;
        scheduleRebuildForChunk(arg0: number, arg1: number, arg2: number, arg3: boolean): void;
        scheduleRebuildForChunks(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean): void;
        iterateVisibleBlockEntities(arg0: $Consumer_<$BlockEntity>): void;
        scheduleRebuildForBlockArea(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: boolean): void;
        getDebugStrings(): $Collection<string>;
        isBoxVisible(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        isEntityVisible(arg0: $Entity): boolean;
        handler$cmn000$aeronautics$setupLevititeShaders(arg0: $RenderType, arg1: $ChunkRenderMatrices_, arg2: number, arg3: number, arg4: number, arg5: $CallbackInfo): void;
        handler$cmn000$aeronautics$cleanupLevititeShaders(arg0: $RenderType, arg1: $ChunkRenderMatrices_, arg2: number, arg3: number, arg4: number, arg5: $CallbackInfo): void;
        handler$gje000$sable$scheduleRebuildForChunk(arg0: number, arg1: number, arg2: number, arg3: boolean, arg4: $CallbackInfo): void;
        handler$gje000$sable$isTerrainRenderComplete(arg0: $CallbackInfoReturnable<any>): void;
        handler$gje000$sable$markGraphDirty(arg0: $Camera, arg1: $Viewport, arg2: boolean, arg3: boolean, arg4: $CallbackInfo): void;
        sable$getSubLevelRenderSectionManager(arg0: $ClientSubLevel): $SubLevelRenderSectionManager;
        handler$gje000$sable$drawRenderSources(arg0: $RenderType, arg1: $ChunkRenderMatrices_, arg2: number, arg3: number, arg4: number, arg5: $CallbackInfo): void;
        getRenderSectionManager(): $RenderSectionManager;
        constructor(arg0: $Minecraft);
        set level(value: $ClientLevel);
        get chunksDebugString(): string;
        get terrainRenderComplete(): boolean;
        get visibleChunkCount(): number;
        get debugStrings(): $Collection<string>;
        get renderSectionManager(): $RenderSectionManager;
    }
}
