#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 28 23:45:13 WEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=
