version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
ends_delight = true
farmersdelight = true
createbigcannons = true
vista = true
sliceanddice = true
create = true
mynethersdelight = true
aeronautics = true
oceansdelight = true
numismatics = true
simulated = true
moonlight = true
analogaudio = true
create_radar = true
copycats = true
minecraft = true
exposure = true
