#The render distance for physics objects (SubLevels) in chunks.
# Default: 32
# Range: 1 ~ 1000000
physicsRenderDistance = 16
#The minimum render distance for physics objects (SubLevels) in chunks.
# Default: 16
# Range: 1 ~ 1000000
minPhysicsRenderDistance = 16
#The maximum render distance for physics objects (SubLevels) in chunks.
# Default: 4096
# Range: 1 ~ 1000000
maxPhysicsRenderDistance = 4096
