import { $Function4_, $Function0_, $Function1_, $Function2_, $Function3_, $Function2, $Function1, $Function0, $Function4, $Function3 } from "@package/kotlin/jvm/functions";
import { $DefaultConstructorMarker } from "@package/kotlin/jvm/internal";
import { $YConstraint, $ColorConstraint, $RadiusConstraint, $HeightConstraint, $WidthConstraint, $XConstraint } from "@package/gg/essential/elementa/constraints";
import { $ConcurrentLinkedDeque } from "@package/java/util/concurrent";
import { $ReferenceHolder } from "@package/gg/essential/elementa/state/v2";
import { $Effect } from "@package/gg/essential/elementa/effects";
import { $Window } from "@package/gg/essential/elementa/components";
import { $List, $List_, $Map, $Set, $Observable } from "@package/java/util";
import { $AnimatingConstraints, $AnimationStrategy_ } from "@package/gg/essential/elementa/constraints/animation";
import { $BiConsumer_, $Consumer_ } from "@package/java/util/function";
import { $ObservableList, $TriConsumer_ } from "@package/gg/essential/elementa/utils";
import { $UMatrixStack } from "@package/gg/essential/universal";
import { $UIScrollEvent, $UIClickEvent } from "@package/gg/essential/elementa/events";
import { $FontProvider } from "@package/gg/essential/elementa/font";
import { $Color } from "@package/java/awt";
import { $StackTraceElement, $Enum, $Class, $Runnable_, $Object } from "@package/java/lang";
import { $Unit, $Pair } from "@package/kotlin";
import { $KMutableProperty0 } from "@package/kotlin/reflect";
export * as font from "@package/gg/essential/elementa/font";
export * as constraints from "@package/gg/essential/elementa/constraints";
export * as state from "@package/gg/essential/elementa/state";
export * as components from "@package/gg/essential/elementa/components";
export * as effects from "@package/gg/essential/elementa/effects";
export * as events from "@package/gg/essential/elementa/events";
export * as utils from "@package/gg/essential/elementa/utils";

declare module "@package/gg/essential/elementa" {
    export class $ElementaVersion extends $Enum<$ElementaVersion> {
        static values(): $ElementaVersion[];
        static valueOf(arg0: string): $ElementaVersion;
        enableFor<T>(arg0: $Function0_<T>): T;
        static access$getActive$cp(): $ElementaVersion;
        static access$setActive$cp(arg0: $ElementaVersion_): void;
        static access$getV7$cp(): $ElementaVersion;
        static access$getV1$cp(): $ElementaVersion;
        static access$getV8$cp(): $ElementaVersion;
        static access$getV3$cp(): $ElementaVersion;
        static access$getV5$cp(): $ElementaVersion;
        static access$getV6$cp(): $ElementaVersion;
        static access$getV10$cp(): $ElementaVersion;
        static access$getV4$cp(): $ElementaVersion;
        static access$getV9$cp(): $ElementaVersion;
        static access$getV0$cp(): $ElementaVersion;
        static access$getV2$cp(): $ElementaVersion;
        static Companion: $ElementaVersion$Companion;
        static V6: $ElementaVersion;
        static V7: $ElementaVersion;
        static V8: $ElementaVersion;
        static V9: $ElementaVersion;
        static V10: $ElementaVersion;
        static V0: $ElementaVersion;
        static V1: $ElementaVersion;
        static V2: $ElementaVersion;
        static V3: $ElementaVersion;
        static V4: $ElementaVersion;
        static V5: $ElementaVersion;
    }
    /**
     * Values that may be interpreted as {@link $ElementaVersion}.
     */
    export type $ElementaVersion_ = "v0" | "v1" | "v2" | "v3" | "v4" | "v5" | "v6" | "v7" | "v8" | "v9" | "v10";
    export class $ElementaVersion$Companion {
        getV8$Elementa(): $ElementaVersion;
        getV0$Elementa(): $ElementaVersion;
        getV3$Elementa(): $ElementaVersion;
        getV4$Elementa(): $ElementaVersion;
        getV2$Elementa(): $ElementaVersion;
        setActive(arg0: $ElementaVersion_): void;
        getV7$Elementa(): $ElementaVersion;
        getAtLeastV10Active$Elementa(): boolean;
        getAtLeastV9Active$Elementa(): boolean;
        getActive(): $ElementaVersion;
        static getActive$annotations(): void;
        static getV0$Elementa$annotations(): void;
        static getV7$Elementa$annotations(): void;
        static getV3$Elementa$annotations(): void;
        static getV1$Elementa$annotations(): void;
        static getV2$Elementa$annotations(): void;
        static getV4$Elementa$annotations(): void;
        static getV5$Elementa$annotations(): void;
        static getV6$Elementa$annotations(): void;
        static getV8$Elementa$annotations(): void;
        static getV9$Elementa$annotations(): void;
        getV10$Elementa(): $ElementaVersion;
        getV5$Elementa(): $ElementaVersion;
        getV6$Elementa(): $ElementaVersion;
        getV9$Elementa(): $ElementaVersion;
        getV1$Elementa(): $ElementaVersion;
        constructor(arg0: $DefaultConstructorMarker);
        get v8$Elementa(): $ElementaVersion;
        get v0$Elementa(): $ElementaVersion;
        get v3$Elementa(): $ElementaVersion;
        get v4$Elementa(): $ElementaVersion;
        get v2$Elementa(): $ElementaVersion;
        get v7$Elementa(): $ElementaVersion;
        get atLeastV10Active$Elementa(): boolean;
        get atLeastV9Active$Elementa(): boolean;
        static get active$annotations(): void;
        static get v0$Elementa$annotations(): void;
        static get v7$Elementa$annotations(): void;
        static get v3$Elementa$annotations(): void;
        static get v1$Elementa$annotations(): void;
        static get v2$Elementa$annotations(): void;
        static get v4$Elementa$annotations(): void;
        static get v5$Elementa$annotations(): void;
        static get v6$Elementa$annotations(): void;
        static get v8$Elementa$annotations(): void;
        static get v9$Elementa$annotations(): void;
        get v10$Elementa(): $ElementaVersion;
        get v5$Elementa(): $ElementaVersion;
        get v6$Elementa(): $ElementaVersion;
        get v9$Elementa(): $ElementaVersion;
        get v1$Elementa(): $ElementaVersion;
    }
    export class $UIConstraints extends $Observable {
        copy(): $UIConstraints;
        finish(): $UIComponent;
        setColor(arg0: $ColorConstraint): void;
        getY(): $YConstraint;
        getFontProvider(): $FontProvider;
        getTextScale(): number;
        setTextScale(arg0: $HeightConstraint): void;
        setFontProvider(arg0: $FontProvider): void;
        withTextScale(arg0: $HeightConstraint): $UIConstraints;
        getWidth(): $WidthConstraint;
        withFontProvider(arg0: $FontProvider): void;
        getHeight(): number;
        getX(): number;
        animationFrame$Elementa(): void;
        setRadius(arg0: $RadiusConstraint): void;
        getRadius(): number;
        getColor(): $Color;
        setX(arg0: $XConstraint): void;
        setY(arg0: $YConstraint): void;
        setHeight(arg0: $HeightConstraint): void;
        setWidth(arg0: $WidthConstraint): void;
        withColor(arg0: $ColorConstraint): $UIConstraints;
        withWidth(arg0: $WidthConstraint): $UIConstraints;
        withY(arg0: $YConstraint): $UIConstraints;
        withHeight(arg0: $HeightConstraint): $UIConstraints;
        withRadius(arg0: $RadiusConstraint): $UIConstraints;
        withX(arg0: $XConstraint): $UIConstraints;
        constructor(arg0: $UIComponent);
    }
    export class $UIComponent extends $Observable implements $ReferenceHolder {
        getParent(): $UIComponent;
        depth(): number;
        delay(arg0: number, arg1: $Function0_<$Unit>): $Function0<$Unit>;
        keyType(arg0: string, arg1: number): void;
        isFloating(): boolean;
        setParent(arg0: $UIComponent): void;
        setColor(arg0: $ColorConstraint): $UIComponent;
        setColor(arg0: $Color): $UIComponent;
        getChildren(): $ObservableList<$UIComponent>;
        removeChild(arg0: $UIComponent): $UIComponent;
        removeEffect(arg0: $Effect): void;
        removeEffect<T>(): void;
        removeEffect<T extends $Effect>(arg0: $Class<T>): void;
        addChild(arg0: $UIComponent): $UIComponent;
        static timer$default(arg0: $UIComponent, arg1: number, arg2: number, arg3: $Function1_<any, any>, arg4: number, arg5: $Object): $Function0<any>;
        static animate$default(arg0: $UIComponent, arg1: $KMutableProperty0<any>, arg2: $AnimationStrategy_, arg3: number, arg4: number, arg5: number, arg6: number, arg7: $Object): void;
        static animate$default(arg0: $UIComponent, arg1: $KMutableProperty0<any>, arg2: $AnimationStrategy_, arg3: number, arg4: $Color, arg5: number, arg6: number, arg7: $Object): void;
        static animate$default(arg0: $UIComponent, arg1: $KMutableProperty0<any>, arg2: $AnimationStrategy_, arg3: number, arg4: number, arg5: number, arg6: number, arg7: $Object): void;
        static animate$default(arg0: $UIComponent, arg1: $KMutableProperty0<any>, arg2: $AnimationStrategy_, arg3: number, arg4: number, arg5: number, arg6: number, arg7: $Object): void;
        static animate$default(arg0: $UIComponent, arg1: $KMutableProperty0<any>, arg2: $AnimationStrategy_, arg3: number, arg4: number, arg5: number, arg6: number, arg7: $Object): void;
        static hide$default(arg0: $UIComponent, arg1: boolean, arg2: number, arg3: $Object): void;
        static startTimer$default(arg0: $UIComponent, arg1: number, arg2: number, arg3: $Function1_<any, any>, arg4: number, arg5: $Object): number;
        static unhide$default(arg0: $UIComponent, arg1: boolean, arg2: number, arg3: $Object): void;
        getComponentName(): string;
        setComponentName(arg0: string): void;
        childrenOfType<T>(): $List<T>;
        childrenOfType<T>(arg0: $Class<T>): $List<T>;
        insertChildAt(arg0: $UIComponent, arg1: number): $UIComponent;
        enableEffects(...arg0: $Effect[]): $UIComponent;
        addUpdateFunc(arg0: $Function2_<number, number, $Unit>): void;
        getFontProvider(): $FontProvider;
        getHasParent(): boolean;
        insertChildAfter(arg0: $UIComponent, arg1: $UIComponent): $UIComponent;
        alwaysDrawChildren(): boolean;
        getTextScale(): number;
        beforeChildrenDraw(arg0: $UMatrixStack): void;
        beforeChildrenDraw(): void;
        clearChildren(): $UIComponent;
        isPointInside(arg0: number, arg1: number): boolean;
        setIsFloating(arg0: boolean): void;
        getSource$Elementa(): $StackTraceElement[];
        animateBeforeHide(arg0: $Function1_<$AnimatingConstraints, $Unit>): $UIComponent;
        grabWindowFocus(): void;
        isPositionCenter(): boolean;
        makeAnimation(): $AnimatingConstraints;
        mouseRelease(): void;
        mouseScroll(arg0: number): void;
        beforeDrawCompat(arg0: $UMatrixStack): void;
        onKeyTypeConsumer(arg0: $BiConsumer_<string, number>): void;
        onMouseClick(arg0: $Function2_<$UIComponent, $UIClickEvent, $Unit>): $UIComponent;
        onFocusLost(arg0: $Function1_<$UIComponent, $Unit>): $UIComponent;
        onMouseDrag(arg0: $Function4_<$UIComponent, number, number, number, $Unit>): $UIComponent;
        afterDrawCompat(arg0: $UMatrixStack): void;
        animateAfterUnhide(arg0: $Function1_<$AnimatingConstraints, $Unit>): $UIComponent;
        animationFrame(): void;
        enableEffect(arg0: $Effect): $UIComponent;
        insertChildBefore(arg0: $UIComponent, arg1: $UIComponent): $UIComponent;
        onMouseScroll(arg0: $Function2_<$UIComponent, $UIScrollEvent, $Unit>): $UIComponent;
        onMouseLeave(arg0: $Function1_<$UIComponent, $Unit>): $UIComponent;
        setTextScale(arg0: $HeightConstraint): $UIComponent;
        releaseWindowFocus(): void;
        setFloating(arg0: boolean): void;
        onWindowResize(): void;
        setFontProvider(arg0: $FontProvider): $UIComponent;
        onMouseRelease(arg0: $Function1_<$UIComponent, $Unit>): $UIComponent;
        removeUpdateFunc(arg0: $Function2_<number, number, $Unit>): void;
        onMouseEnter(arg0: $Function1_<$UIComponent, $Unit>): $UIComponent;
        stopAnimating(arg0: $KMutableProperty0<never>): void;
        assertUpdateFuncInvariants$Elementa(): void;
        pixelCoordinatesToPixelCenter$Elementa(arg0: number, arg1: number): $Pair<number, number>;
        getLeft(): number;
        getRight(): number;
        addChildren(...arg0: $UIComponent[]): $UIComponent;
        timer(arg0: number, arg1: number, arg2: $Function1_<number, $Unit>): $Function0<$Unit>;
        getWidth(): number;
        getConstraints(): $UIConstraints;
        replaceChild(arg0: $UIComponent, arg1: $UIComponent): $UIComponent;
        getHeight(): number;
        setConstraints(arg0: $UIConstraints): void;
        setCachedWindow$Elementa(arg0: $Window): void;
        getFilteredSource$Elementa(): $List<$StackTraceElement>;
        getLastDraggedMouseX(): number;
        setLastDraggedMouseX(arg0: number): void;
        getKeyTypedListeners(): $List<$Function3<$UIComponent, string, number, $Unit>>;
        getCachedWindow$Elementa(): $Window;
        getLastDraggedMouseY(): number;
        setLastDraggedMouseY(arg0: number): void;
        getMouseClickListeners(): $List<$Function2<$UIComponent, $UIClickEvent, $Unit>>;
        getMouseDragListeners(): $List<$Function4<$UIComponent, number, number, number, $Unit>>;
        getMouseReleaseListeners(): $List<$Function1<$UIComponent, $Unit>>;
        onMouseEnterRunnable(arg0: $Runnable_): $UIComponent;
        beforeChildrenDrawCompat(arg0: $UMatrixStack): void;
        setMouseScrollListeners(arg0: $List_<$Function2_<$UIComponent, $UIScrollEvent, $Unit>>): void;
        removeUpdateFunc$Elementa(arg0: $Effect, arg1: number): void;
        getVersionOrV0$Elementa(): $ElementaVersion;
        getMouseLeaveListeners(): $List<$Function1<$UIComponent, $Unit>>;
        onMouseDragConsumer(arg0: $TriConsumer_<number, number, number>): $UIComponent;
        getMouseEnterListeners(): $List<$Function1<$UIComponent, $Unit>>;
        onMouseLeaveRunnable(arg0: $Runnable_): $UIComponent;
        addUpdateFunc$Elementa(arg0: $Effect, arg1: number, arg2: $Function2_<number, number, $Unit>): void;
        static access$getActiveTimers$p(arg0: $UIComponent): $Map<any, any>;
        static access$getStoppedTimers$p(arg0: $UIComponent): $Set<any>;
        onMouseReleaseRunnable(arg0: $Runnable_): $UIComponent;
        onMouseClickConsumer(arg0: $Consumer_<$UIClickEvent>): $UIComponent;
        getMouseScrollListeners(): $List<$Function2<$UIComponent, $UIScrollEvent, $Unit>>;
        getPrimarySource$Elementa(): $StackTraceElement;
        onMouseScrollConsumer(arg0: $Consumer_<$UIScrollEvent>): $UIComponent;
        afterInitialization(): void;
        static access$setIndexInParent$p(arg0: $UIComponent, arg1: number): void;
        static access$getHeldReferences$p(arg0: $UIComponent): $List<any>;
        draw(): void;
        draw(arg0: $UMatrixStack): void;
        setRadius(arg0: $RadiusConstraint): $UIComponent;
        getRadius(): number;
        getColor(): $Color;
        setX(arg0: $XConstraint): $UIComponent;
        setY(arg0: $YConstraint): $UIComponent;
        getEffects(): $List<$Effect>;
        focus(): void;
        setHeight(arg0: $HeightConstraint): $UIComponent;
        setWidth(arg0: $WidthConstraint): $UIComponent;
        mouseDrag(arg0: number, arg1: number, arg2: number): void;
        isChildOf(arg0: $UIComponent): boolean;
        onKeyType(arg0: $Function3_<$UIComponent, string, number, $Unit>): $UIComponent;
        unhide(arg0: boolean): void;
        beforeDraw(): void;
        beforeDraw(arg0: $UMatrixStack): void;
        mouseClick(arg0: number, arg1: number, arg2: number): void;
        stopDelay(arg0: number): boolean;
        holdOnto(arg0: $Object): $Function0<$Unit>;
        afterDraw(arg0: $UMatrixStack): void;
        afterDraw(): void;
        mouseMove(arg0: $Window): void;
        onFocus(arg0: $Function1_<$UIComponent, $Unit>): $UIComponent;
        animate(arg0: $KMutableProperty0<number>, arg1: $AnimationStrategy_, arg2: number, arg3: number, arg4: number): void;
        animate(arg0: $KMutableProperty0<number>, arg1: $AnimationStrategy_, arg2: number, arg3: number, arg4: number): void;
        animate(arg0: $KMutableProperty0<number>, arg1: $AnimationStrategy_, arg2: number, arg3: number, arg4: number): void;
        animate(arg0: $KMutableProperty0<number>, arg1: $AnimationStrategy_, arg2: number, arg3: number, arg4: number): void;
        animate(arg0: $KMutableProperty0<$Color>, arg1: $AnimationStrategy_, arg2: number, arg3: $Color, arg4: number): void;
        hasFocus(): boolean;
        getTop(): number;
        startTimer(arg0: number, arg1: number, arg2: $Function1_<number, $Unit>): number;
        startDelay(arg0: number, arg1: $Function0_<$Unit>): number;
        animateTo(arg0: $AnimatingConstraints): void;
        hitTest(arg0: number, arg1: number): $UIComponent;
        setChildOf(arg0: $UIComponent): $UIComponent;
        loseFocus(): void;
        drawCompat(arg0: $UMatrixStack): void;
        dragMouse(arg0: number, arg1: number, arg2: number): void;
        dragMouse(arg0: number, arg1: number, arg2: number): void;
        hide(arg0: boolean): void;
        hide(): void;
        stopTimer(arg0: number): boolean;
        isHovered(): boolean;
        "getCombinedFlags-gM4u_j4$Elementa"(): number;
        getFloatingComponents$Elementa(): $List<$UIComponent>;
        "setEffectFlags-GhGBI1o$Elementa"(arg0: number): void;
        setFloatingComponents$Elementa(arg0: $List_<$UIComponent>): void;
        "setCombinedFlags-GhGBI1o$Elementa"(arg0: number): void;
        "getEffectFlags-gM4u_j4$Elementa"(): number;
        static getLastDraggedMouseX$annotations(): void;
        static getLastDraggedMouseY$annotations(): void;
        "getOwnFlags-gM4u_j4$Elementa"(): number;
        "setOwnFlags-GhGBI1o$Elementa"(arg0: number): void;
        recomputeEffectFlags$Elementa(): void;
        static access$getDEBUG_OUTLINE_WIDTH$cp(): number;
        static access$getFieldAnimationQueue$p(arg0: $UIComponent): $ConcurrentLinkedDeque<any>;
        getBottom(): number;
        static Companion: $UIComponent$Companion;
        parent: $UIComponent;
        constructor();
        get children(): $ObservableList<$UIComponent>;
        get hasParent(): boolean;
        get source$Elementa(): $StackTraceElement[];
        get positionCenter(): boolean;
        get left(): number;
        get right(): number;
        get filteredSource$Elementa(): $List<$StackTraceElement>;
        get keyTypedListeners(): $List<$Function3<$UIComponent, string, number, $Unit>>;
        get mouseClickListeners(): $List<$Function2<$UIComponent, $UIClickEvent, $Unit>>;
        get mouseDragListeners(): $List<$Function4<$UIComponent, number, number, number, $Unit>>;
        get mouseReleaseListeners(): $List<$Function1<$UIComponent, $Unit>>;
        get versionOrV0$Elementa(): $ElementaVersion;
        get mouseLeaveListeners(): $List<$Function1<$UIComponent, $Unit>>;
        get mouseEnterListeners(): $List<$Function1<$UIComponent, $Unit>>;
        get primarySource$Elementa(): $StackTraceElement;
        set x(value: $XConstraint);
        set y(value: $YConstraint);
        get effects(): $List<$Effect>;
        get top(): number;
        get hovered(): boolean;
        get combinedFlags-gM4u_j4$Elementa(): number;
        set effectFlags-GhGBI1o$Elementa(value: number);
        set combinedFlags-GhGBI1o$Elementa(value: number);
        get effectFlags-gM4u_j4$Elementa(): number;
        static get lastDraggedMouseX$annotations(): void;
        static get lastDraggedMouseY$annotations(): void;
        get ownFlags-gM4u_j4$Elementa(): number;
        set ownFlags-GhGBI1o$Elementa(value: number);
        get bottom(): number;
    }
    export class $UIComponent$Companion {
        getDEBUG_OUTLINE_WIDTH(): number;
        drawDebugOutline$Elementa(arg0: $UMatrixStack, arg1: number, arg2: number, arg3: number, arg4: number, arg5: $UIComponent): void;
        getMouseX$Elementa(): number;
        getMouseY$Elementa(): number;
        guiHint(arg0: number, arg1: boolean): number;
        guiHint(arg0: number, arg1: boolean): number;
        constructor(arg0: $DefaultConstructorMarker);
        get DEBUG_OUTLINE_WIDTH(): number;
        get mouseX$Elementa(): number;
        get mouseY$Elementa(): number;
    }
}
