modLoader = "javafml"
# The loader version doesn't matter. Modify the NeoForge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/Creators-of-Create/Create/issues"
license = "Read attached LICENSE.md"

[[mods]]
modId = "create"
version = "6.0.10"
displayName = "Create"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/create"
updateJSONURL = "https://api.modrinth.com/updates/create/forge_updates.json?neoforge=only"
logoFile = "icon.png"
authors = "simibubi"
description = '''Technology that empowers the player.'''

[[mixins]]
config = "create.mixins.json"

[[dependencies."create"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.219,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."create"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies."create"]]
modId = "flywheel"
type = "required"
versionRange = "[1.0.0,2.0)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."create"]]
modId = "ponder"
type = "required"
versionRange = "[1.0.82,)"
ordering = "AFTER"
side = "BOTH"

# Versions before 0.6.9 do not have sprite util under the api package
[[dependencies."create"]]
modId = "sodium"
type = "optional"
reason = "Versions before 0.6.9 do not include the neccesary APIs Create needs to work properly with Sodium."
versionRange = "[0.6.9,)"
ordering = "NONE"
side = "CLIENT"

# Versions before 0.14.7 crash with level wrappers
[[dependencies."create"]]
modId = "lithium"
type = "optional"
reason = "Versions before 0.14.7 crash when paired with Create, Update Lithium."
versionRange = "[0.14.7,)"
ordering = "NONE"
side = "BOTH"

# Versions before 1.21.1-6.0.0-beta.46 do not contain the fullscreen render event we use
[[dependencies."create"]]
modId = "journeymap"
type = "optional"
reason = "Versions before 1.21.1-6.0.0-beta.46 do not contain the APIs Create requires to work with JourneyMap."
versionRange = "[1.21.1-6.0.0-beta.46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."create"]]
modId = "xaeroworldmap"
type = "optional"
reason = "Versions before 1.40.2 do not contain the classes Create requires to work with Xaero's World Map."
versionRange = "[1.40.2,)"
ordering = "NONE"
side = "CLIENT"

# Incompatible Mods

# Users should use lithium instead, it's up to date and does not crash with level wrappers (anymore)
[[dependencies."create"]]
modId = "radium"
type = "incompatible"
reason = "Radium is a unofficial port of Lithium, Lithium is now natively available for NeoForge and does not suffer from the same issues radium does, use Lithium instead."
ordering = "NONE"
side = "BOTH"

# Does not improve memory usage, results in connected textures not working as intended.
[[dependencies."create"]]
modId = "palladium"
type = "incompatible"
reason = "Palladium does not improve memory usage by anything meaningful, and results in broken visuals for Create's blocks with connected textures."
ordering = "NONE"
side = "BOTH"
