import { $Codec } from "@package/com/mojang/serialization";
import { $Vector4fc, $Vector3fc } from "@package/org/joml";

declare module "@package/foundry/veil/api/client/color" {
    export class $Color implements $Colorc {
        invert(): $Color;
        set(arg0: number, arg1: number, arg2: number): $Color;
        set(arg0: number, arg1: number, arg2: number, arg3: number): $Color;
        set(arg0: $Colorc): $Color;
        setInt(arg0: number, arg1: number, arg2: number): $Color;
        setInt(arg0: number, arg1: number, arg2: number, arg3: number): $Color;
        mix(arg0: $Colorc, arg1: number): $Color;
        red(): number;
        red(arg0: number): $Color;
        lerp(arg0: $Colorc, arg1: number): $Color;
        blue(arg0: number): $Color;
        blue(): number;
        green(arg0: number): $Color;
        green(): number;
        setSaturation(arg0: number): $Color;
        alpha(arg0: number): $Color;
        alpha(): number;
        blueInt(arg0: number): $Color;
        alphaInt(arg0: number): $Color;
        grayscale(): $Color;
        sepia(): $Color;
        lighten(arg0: number): $Color;
        redInt(arg0: number): $Color;
        darken(arg0: number): $Color;
        setHue(arg0: number): $Color;
        greenInt(arg0: number): $Color;
        setHSV(arg0: number, arg1: number, arg2: number): $Color;
        setARGB(arg0: number): $Color;
        setRGB(arg0: number): $Color;
        setLuminance(arg0: number): $Color;
        invert(arg0: $Color): $Color;
        saturation(): number;
        hue(): number;
        mix(arg0: $Colorc, arg1: number, arg2: $Color): $Color;
        lerp(arg0: $Colorc, arg1: number, arg2: $Color): $Color;
        rgb(): number;
        setSaturation(arg0: number, arg1: $Color): $Color;
        argb(): number;
        luminance(): number;
        maxComponent(): number;
        minComponent(): number;
        blueInt(): number;
        alphaInt(): number;
        grayscale(arg0: $Color): $Color;
        sepia(arg0: $Color): $Color;
        lighten(arg0: number, arg1: $Color): $Color;
        redInt(): number;
        darken(arg0: number, arg1: $Color): $Color;
        setHue(arg0: number, arg1: $Color): $Color;
        greenInt(): number;
        setHSV(arg0: number, arg1: number, arg2: number, arg3: $Color): $Color;
        setLuminance(arg0: number, arg1: $Color): $Color;
        static WHITE: $Colorc;
        static RGB_INT_CODEC: $Codec<number>;
        static BLUE: $Colorc;
        static VANILLA_TOOLTIP_BACKGROUND: $Colorc;
        static VANILLA_TOOLTIP_BORDER_TOP: $Colorc;
        static GREEN: $Colorc;
        static VANILLA_TOOLTIP_BORDER_BOTTOM: $Colorc;
        static RGB_CODEC: $Codec<$Colorc>;
        static RED: $Colorc;
        static ARGB_CODEC: $Codec<$Colorc>;
        static ARGB_INT_CODEC: $Codec<number>;
        static BLACK: $Colorc;
        static TRANSPARENT: $Colorc;
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: $Colorc);
        constructor(arg0: $Vector3fc);
        constructor(arg0: $Vector4fc);
        constructor();
        constructor(arg0: number);
        constructor(arg0: number, arg1: boolean);
        constructor(arg0: number, arg1: number, arg2: number);
        set ARGB(value: number);
        set RGB(value: number);
    }
    export class $Colorc {
    }
    export interface $Colorc {
        invert(arg0: $Color): $Color;
        saturation(): number;
        hue(): number;
        mix(arg0: $Colorc, arg1: number, arg2: $Color): $Color;
        red(): number;
        lerp(arg0: $Colorc, arg1: number, arg2: $Color): $Color;
        rgb(): number;
        blue(): number;
        green(): number;
        setSaturation(arg0: number, arg1: $Color): $Color;
        alpha(): number;
        argb(): number;
        luminance(): number;
        maxComponent(): number;
        minComponent(): number;
        blueInt(): number;
        alphaInt(): number;
        grayscale(arg0: $Color): $Color;
        sepia(arg0: $Color): $Color;
        lighten(arg0: number, arg1: $Color): $Color;
        redInt(): number;
        darken(arg0: number, arg1: $Color): $Color;
        setHue(arg0: number, arg1: $Color): $Color;
        greenInt(): number;
        setHSV(arg0: number, arg1: number, arg2: number, arg3: $Color): $Color;
        setLuminance(arg0: number, arg1: $Color): $Color;
    }
}
