import { $BlockGetter, $LevelAccessor } from "@package/net/minecraft/world/level";
import { $InstanceType, $InstanceHandle } from "@package/dev/engine_room/flywheel/api/instance";
import { $MapCodec } from "@package/com/mojang/serialization";
import { $Item, $ItemStack } from "@package/net/minecraft/world/item";
import { $FluidState, $Fluid_ } from "@package/net/minecraft/world/level/material";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $AbstractInstance } from "@package/dev/engine_room/flywheel/lib/instance";
import { $InteractionResult } from "@package/net/minecraft/world";
import { $SoundEvent } from "@package/net/minecraft/sounds";
import { $Object2ByteLinkedOpenHashMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $DirectionProperty } from "@package/net/minecraft/world/level/block/state/properties";
import { $BlockPos_, $Direction_, $Direction, $IdMapper } from "@package/net/minecraft/core";
import { $IWrenchable } from "@package/com/simibubi/create/content/equipment/wrench";
import { $BlockPlaceContext, $UseOnContext } from "@package/net/minecraft/world/item/context";
import { $StateDefinition, $BlockState_, $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $ResourceKey } from "@package/net/minecraft/resources";
import { $ProperWaterloggedBlock } from "@package/com/simibubi/create/foundation/block";
import { $HorizontalDirectionalBlock, $Block$BlockStatePairKey, $SoundType, $Block } from "@package/net/minecraft/world/level/block";
import { $ThreadLocal } from "@package/java/lang";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $Quaternionf, $Vector3f, $Quaternionfc } from "@package/org/joml";
export * as psi from "@package/com/simibubi/create/content/contraptions/actors/psi";
export * as roller from "@package/com/simibubi/create/content/contraptions/actors/roller";
export * as plough from "@package/com/simibubi/create/content/contraptions/actors/plough";
export * as contraptionControls from "@package/com/simibubi/create/content/contraptions/actors/contraptionControls";
export * as harvester from "@package/com/simibubi/create/content/contraptions/actors/harvester";
export * as trainControls from "@package/com/simibubi/create/content/contraptions/actors/trainControls";
export * as seat from "@package/com/simibubi/create/content/contraptions/actors/seat";

declare module "@package/com/simibubi/create/content/contraptions/actors" {
    export class $ActorInstance extends $AbstractInstance {
        setRotationAxis(arg0: $Vector3f): $ActorInstance;
        setRotationAxis(arg0: number, arg1: number, arg2: number): $ActorInstance;
        setSkyLight(arg0: number): $ActorInstance;
        setBlockLight(arg0: number): $ActorInstance;
        setRotationOffset(arg0: number): $ActorInstance;
        setSpeed(arg0: number): $ActorInstance;
        setPosition(arg0: $BlockPos_): $ActorInstance;
        setRotationCenter(arg0: number, arg1: number, arg2: number): $ActorInstance;
        setRotationCenter(arg0: $Vector3f): $ActorInstance;
        setLocalRotation(arg0: $Quaternionfc): $ActorInstance;
        rotation: $Quaternionf;
        skyLight: number;
        rotationOffset: number;
        speed: number;
        blockLight: number;
        x: number;
        y: number;
        z: number;
        rotationAxisZ: number;
        rotationCenterZ: number;
        rotationAxisY: number;
        rotationCenterY: number;
        rotationAxisX: number;
        rotationCenterX: number;
        constructor(arg0: $InstanceType<never>, arg1: $InstanceHandle);
        set position(value: $BlockPos_);
        set localRotation(value: $Quaternionfc);
    }
    export class $AttachedActorBlock extends $HorizontalDirectionalBlock implements $IWrenchable, $ProperWaterloggedBlock {
        onWrenched(arg0: $BlockState_, arg1: $UseOnContext): $InteractionResult;
        updateAfterWrenched(arg0: $BlockState_, arg1: $UseOnContext): $BlockState;
        getRotatedBlockState(arg0: $BlockState_, arg1: $Direction_): $BlockState;
        onSneakWrenched(arg0: $BlockState_, arg1: $UseOnContext): $InteractionResult;
        withWater(arg0: $BlockState_, arg1: $BlockPlaceContext): $BlockState;
        fluidState(arg0: $BlockState_): $FluidState;
        updateWater(arg0: $LevelAccessor, arg1: $BlockState_, arg2: $BlockPos_): void;
        canPlaceLiquid(arg0: $Player | null, arg1: $BlockGetter, arg2: $BlockPos_, arg3: $BlockState_, arg4: $Fluid_): boolean;
        placeLiquid(arg0: $LevelAccessor, arg1: $BlockPos_, arg2: $BlockState_, arg3: $FluidState): boolean;
        pickupBlock(arg0: $Player | null, arg1: $LevelAccessor, arg2: $BlockPos_, arg3: $BlockState_): $ItemStack;
        getPickupSound(): ($SoundEvent) | undefined;
        getPickupSound(arg0: $BlockState_): ($SoundEvent) | undefined;
        explosionResistance: number;
        static UPDATE_SHAPE_ORDER: $Direction[];
        static OCCLUSION_CACHE: $ThreadLocal<$Object2ByteLinkedOpenHashMap<$Block$BlockStatePairKey>>;
        static UPDATE_NONE: number;
        static UPDATE_INVISIBLE: number;
        stateDefinition: $StateDefinition<$Block, $BlockState>;
        static UPDATE_MOVE_BY_PISTON: number;
        static UPDATE_LIMIT: number;
        static UPDATE_ALL: number;
        drops: $ResourceKey<$LootTable>;
        static UPDATE_KNOWN_SHAPE: number;
        static UPDATE_SUPPRESS_DROPS: number;
        dynamicShape: boolean;
        soundType: $SoundType;
        jumpFactor: number;
        static UPDATE_IMMEDIATE: number;
        item: $Item;
        static CODEC: $MapCodec<$Block>;
        static UPDATE_NEIGHBORS: number;
        static INDESTRUCTIBLE: number;
        speedFactor: number;
        friction: number;
        static BLOCK_STATE_REGISTRY: $IdMapper<$BlockState>;
        static UPDATE_ALL_IMMEDIATE: number;
        static INSTANT: number;
        static UPDATE_CLIENTS: number;
        static FACING: $DirectionProperty;
        hasCollision: boolean;
    }
}
