import { $JsonElement_ } from "@package/com/google/gson";
import { $MinecraftServer } from "@package/net/minecraft/server";
import { $KubeIconTypeRegistry_ } from "@package/dev/latvian/mods/kubejs/client/icon";
import { $CustomRecipeSchemaFunctionRegistry_, $RecipeSchemaFunctionRegistry_ } from "@package/dev/latvian/mods/kubejs/recipe/schema/function";
import { $HashMap, $Map_ } from "@package/java/util";
import { $EventGroupRegistry_ } from "@package/dev/latvian/mods/kubejs/event";
import { $RecipeComponentTypeRegistry_ } from "@package/dev/latvian/mods/kubejs/recipe/component";
import { $Consumer_ } from "@package/java/util/function";
import { $AttachedData, $NameProvider$Registry_ } from "@package/dev/latvian/mods/kubejs/util";
import { $RecipePostProcessorTypeRegistry_ } from "@package/dev/latvian/mods/kubejs/recipe/schema/postprocessing";
import { $KubeJSPlugin, $ClassFilter } from "@package/dev/latvian/mods/kubejs/plugin";
import { $RecipeFactoryRegistry, $RecipeMappingRegistry, $RecipeSchemaRegistry } from "@package/dev/latvian/mods/kubejs/recipe/schema";
import { $Object } from "@package/java/lang";
import { $DataComponentTypeInfoRegistry_, $BindingRegistry_, $TypeDescriptionRegistry, $RecordDefaultsRegistry_, $TypeWrapperRegistry, $ScriptManager } from "@package/dev/latvian/mods/kubejs/script";
import { $BlockEntityAttachmentRegistry_ } from "@package/dev/latvian/mods/kubejs/block/entity";
import { $Level_ } from "@package/net/minecraft/world/level";
import { $IngredientActionTypeRegistry_ } from "@package/dev/latvian/mods/kubejs/recipe/ingredientaction";
import { $LangKubeEvent_ } from "@package/dev/latvian/mods/kubejs/client";
import { $Item, $ItemStack } from "@package/net/minecraft/world/item";
import { $KubeAssetGenerator, $KubeDataGenerator } from "@package/dev/latvian/mods/kubejs/generator";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $DataExport } from "@package/dev/latvian/mods/kubejs/server";
import { $RecipesKubeEvent } from "@package/dev/latvian/mods/kubejs/recipe";
import { $RecipeViewerEntryType } from "@package/dev/latvian/mods/kubejs/recipe/viewer";
import { $ServerRegistryRegistry_, $BuilderTypeRegistry_ } from "@package/dev/latvian/mods/kubejs/registry";
import { $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $RecipeManagerKJS } from "@package/dev/latvian/mods/kubejs/core";
import { $LocalWebServer_, $LocalWebServerAPIRegistry_, $LocalWebServerRegistry } from "@package/dev/latvian/mods/kubejs/web";
export * as wrapper from "@package/dev/latvian/mods/kubejs/plugin/builtin/wrapper";
export * as event from "@package/dev/latvian/mods/kubejs/plugin/builtin/event";

declare module "@package/dev/latvian/mods/kubejs/plugin/builtin" {
    export class $BuiltinKubeJSPlugin implements $KubeJSPlugin {
        clearCaches(): void;
        registerRecipePostProcessors(registry: $RecipePostProcessorTypeRegistry_): void;
        registerBlockEntityAttachments(registry: $BlockEntityAttachmentRegistry_): void;
        registerTypeWrappers(registry: $TypeWrapperRegistry): void;
        registerRecordDefaults(registry: $RecordDefaultsRegistry_): void;
        registerEvents(registry: $EventGroupRegistry_): void;
        registerIngredientActionTypes(registry: $IngredientActionTypeRegistry_): void;
        registerServerRegistries(registry: $ServerRegistryRegistry_): void;
        registerTypeDescriptions(registry: $TypeDescriptionRegistry): void;
        registerRecipeFactories(registry: $RecipeFactoryRegistry): void;
        registerBuilderTypes(registry: $BuilderTypeRegistry_): void;
        registerRecipeComponents(registry: $RecipeComponentTypeRegistry_): void;
        registerItemNameProviders(registry: $NameProvider$Registry_<$Item, $ItemStack>): void;
        localWebServerStarted(server: $LocalWebServer_): void;
        registerLocalWebServer(registry: $LocalWebServerRegistry): void;
        registerRecipeSchemaFunctionTypes(registry: $RecipeSchemaFunctionRegistry_): void;
        registerDataComponentTypeDescriptions(registry: $DataComponentTypeInfoRegistry_): void;
        registerBindings(bindings: $BindingRegistry_): void;
        registerIconTypes(registry: $KubeIconTypeRegistry_): void;
        generateData(generator: $KubeDataGenerator): void;
        registerLocalWebServerWithAuth(registry: $LocalWebServerRegistry): void;
        init(): void;
        beforeScriptsLoaded(manager: $ScriptManager): void;
        attachLevelData(event: $AttachedData<$Level_>): void;
        attachPlayerData(event: $AttachedData<$Player>): void;
        afterInit(): void;
        attachServerData(event: $AttachedData<$MinecraftServer>): void;
        afterScriptsLoaded(manager: $ScriptManager): void;
        initStartup(): void;
        registerRecipeMappings(registry: $RecipeMappingRegistry): void;
        registerRecipeSchemas(registry: $RecipeSchemaRegistry): void;
        registerLocalWebServerAPIs(registry: $LocalWebServerAPIRegistry_): void;
        beforeRecipeLoading(event: $RecipesKubeEvent, manager: $RecipeManagerKJS, recipeJsons: $Map_<$ResourceLocation_, $JsonElement_>): void;
        breakpoint(args: $Object[]): void;
        registerCustomRecipeSchemaFunctions(registry: $CustomRecipeSchemaFunctionRegistry_): void;
        generateAssets(generator: $KubeAssetGenerator): void;
        generateLang(event: $LangKubeEvent_): void;
        exportServerData(arg0: $DataExport): void;
        registerClasses(filter: $ClassFilter): void;
        registerRecipeViewerEntryTypes(registry: $Consumer_<$RecipeViewerEntryType>): void;
        static GLOBAL: $HashMap<string, $Object>;
        constructor();
    }
    export class $BuiltinKubeJSClientPlugin implements $KubeJSPlugin {
        registerEvents(registry: $EventGroupRegistry_): void;
        afterScriptsLoaded(manager: $ScriptManager): void;
        registerLocalWebServerAPIs(registry: $LocalWebServerAPIRegistry_): void;
        registerLocalWebServer(registry: $LocalWebServerRegistry): void;
        registerBindings(bindings: $BindingRegistry_): void;
        generateLang(event: $LangKubeEvent_): void;
        registerLocalWebServerWithAuth(registry: $LocalWebServerRegistry): void;
        /**
         * @deprecated
         */
        clearCaches(): void;
        registerRecipePostProcessors(registry: $RecipePostProcessorTypeRegistry_): void;
        registerBlockEntityAttachments(registry: $BlockEntityAttachmentRegistry_): void;
        init(): void;
        beforeScriptsLoaded(manager: $ScriptManager): void;
        registerTypeWrappers(registry: $TypeWrapperRegistry): void;
        registerRecordDefaults(registry: $RecordDefaultsRegistry_): void;
        attachLevelData(event: $AttachedData<$Level_>): void;
        registerIngredientActionTypes(registry: $IngredientActionTypeRegistry_): void;
        attachPlayerData(event: $AttachedData<$Player>): void;
        afterInit(): void;
        attachServerData(event: $AttachedData<$MinecraftServer>): void;
        initStartup(): void;
        registerServerRegistries(registry: $ServerRegistryRegistry_): void;
        registerTypeDescriptions(registry: $TypeDescriptionRegistry): void;
        registerRecipeFactories(registry: $RecipeFactoryRegistry): void;
        registerRecipeMappings(registry: $RecipeMappingRegistry): void;
        registerBuilderTypes(registry: $BuilderTypeRegistry_): void;
        registerRecipeSchemas(registry: $RecipeSchemaRegistry): void;
        registerRecipeComponents(registry: $RecipeComponentTypeRegistry_): void;
        registerItemNameProviders(registry: $NameProvider$Registry_<$Item, $ItemStack>): void;
        localWebServerStarted(server: $LocalWebServer_): void;
        beforeRecipeLoading(event: $RecipesKubeEvent, manager: $RecipeManagerKJS, recipeJsons: $Map_<$ResourceLocation_, $JsonElement_>): void;
        breakpoint(args: $Object[]): void;
        registerRecipeSchemaFunctionTypes(registry: $RecipeSchemaFunctionRegistry_): void;
        registerDataComponentTypeDescriptions(registry: $DataComponentTypeInfoRegistry_): void;
        registerCustomRecipeSchemaFunctions(registry: $CustomRecipeSchemaFunctionRegistry_): void;
        registerIconTypes(registry: $KubeIconTypeRegistry_): void;
        generateData(generator: $KubeDataGenerator): void;
        generateAssets(generator: $KubeAssetGenerator): void;
        exportServerData(arg0: $DataExport): void;
        registerClasses(filter: $ClassFilter): void;
        registerRecipeViewerEntryTypes(registry: $Consumer_<$RecipeViewerEntryType>): void;
        constructor();
    }
}
