import { $Codec } from "@package/com/mojang/serialization";
import { $RenderTarget } from "@package/com/mojang/blaze3d/pipeline";
import { $TextureFilter, $TextureFilter_, $TextureFilter$Wrap_, $TextureFilter$CompareFunction_ } from "@package/foundry/veil/api/client/render/texture";
import { $AbstractTexture } from "@package/net/minecraft/client/renderer/texture";
import { $Cloneable, $Enum } from "@package/java/lang";
import { $NativeResource } from "@package/org/lwjgl/system";

declare module "@package/foundry/veil/api/client/render/framebuffer" {
    export class $FramebufferAttachmentDefinition$Format extends $Enum<$FramebufferAttachmentDefinition$Format> {
        static values(): $FramebufferAttachmentDefinition$Format[];
        static valueOf(arg0: string): $FramebufferAttachmentDefinition$Format;
        getFormat(): number;
        getInternalFormat(): number;
        static RGB16F: $FramebufferAttachmentDefinition$Format;
        static RGB4: $FramebufferAttachmentDefinition$Format;
        static R11F_G11F_B10F: $FramebufferAttachmentDefinition$Format;
        static RGB16I: $FramebufferAttachmentDefinition$Format;
        static RG32UI: $FramebufferAttachmentDefinition$Format;
        static RGB16UI: $FramebufferAttachmentDefinition$Format;
        static RGBA16_SNORM: $FramebufferAttachmentDefinition$Format;
        static R16F: $FramebufferAttachmentDefinition$Format;
        static RGB32I: $FramebufferAttachmentDefinition$Format;
        static RGB8UI: $FramebufferAttachmentDefinition$Format;
        static RGB8: $FramebufferAttachmentDefinition$Format;
        static RGB5: $FramebufferAttachmentDefinition$Format;
        static RGB32F: $FramebufferAttachmentDefinition$Format;
        static RGBA: $FramebufferAttachmentDefinition$Format;
        static RGB565: $FramebufferAttachmentDefinition$Format;
        static R32F: $FramebufferAttachmentDefinition$Format;
        static R16I: $FramebufferAttachmentDefinition$Format;
        static R8UI: $FramebufferAttachmentDefinition$Format;
        static DEPTH_COMPONENT32F: $FramebufferAttachmentDefinition$Format;
        static R32I: $FramebufferAttachmentDefinition$Format;
        static R32UI: $FramebufferAttachmentDefinition$Format;
        static RGBA8: $FramebufferAttachmentDefinition$Format;
        static RG8I: $FramebufferAttachmentDefinition$Format;
        static RGBA12: $FramebufferAttachmentDefinition$Format;
        static RGBA32UI: $FramebufferAttachmentDefinition$Format;
        static DEPTH24_STENCIL8: $FramebufferAttachmentDefinition$Format;
        static RG8: $FramebufferAttachmentDefinition$Format;
        static CODEC: $Codec<$FramebufferAttachmentDefinition$Format>;
        static RGBA4: $FramebufferAttachmentDefinition$Format;
        static RGB5_A1: $FramebufferAttachmentDefinition$Format;
        static R8: $FramebufferAttachmentDefinition$Format;
        static RGB9_E5: $FramebufferAttachmentDefinition$Format;
        static RGB10: $FramebufferAttachmentDefinition$Format;
        static RGB12: $FramebufferAttachmentDefinition$Format;
        static RGBA16F: $FramebufferAttachmentDefinition$Format;
        static BGRA: $FramebufferAttachmentDefinition$Format;
        static RGB: $FramebufferAttachmentDefinition$Format;
        static BGR: $FramebufferAttachmentDefinition$Format;
        static RGBA16: $FramebufferAttachmentDefinition$Format;
        static R16_SNORM: $FramebufferAttachmentDefinition$Format;
        static RGBA8I: $FramebufferAttachmentDefinition$Format;
        static RGBA32I: $FramebufferAttachmentDefinition$Format;
        static RGBA8_SNORM: $FramebufferAttachmentDefinition$Format;
        static RGBA32F: $FramebufferAttachmentDefinition$Format;
        static RG: $FramebufferAttachmentDefinition$Format;
        static RGB16: $FramebufferAttachmentDefinition$Format;
        static RGBA16I: $FramebufferAttachmentDefinition$Format;
        static DEPTH_COMPONENT16: $FramebufferAttachmentDefinition$Format;
        static RG16: $FramebufferAttachmentDefinition$Format;
        static RGBA8UI: $FramebufferAttachmentDefinition$Format;
        static RGB10_A2: $FramebufferAttachmentDefinition$Format;
        static RGB32UI: $FramebufferAttachmentDefinition$Format;
        static RG16UI: $FramebufferAttachmentDefinition$Format;
        static RGB8_SNORM: $FramebufferAttachmentDefinition$Format;
        static DEPTH_COMPONENT: $FramebufferAttachmentDefinition$Format;
        static RG16F: $FramebufferAttachmentDefinition$Format;
        static SRGB8: $FramebufferAttachmentDefinition$Format;
        static RG16I: $FramebufferAttachmentDefinition$Format;
        static R16UI: $FramebufferAttachmentDefinition$Format;
        static RG32I: $FramebufferAttachmentDefinition$Format;
        static RG8UI: $FramebufferAttachmentDefinition$Format;
        static SRGB8_ALPHA8: $FramebufferAttachmentDefinition$Format;
        static RG32F: $FramebufferAttachmentDefinition$Format;
        static RG16_SNORM: $FramebufferAttachmentDefinition$Format;
        static DEPTH32F_STENCIL8: $FramebufferAttachmentDefinition$Format;
        static RGB10_A2UI: $FramebufferAttachmentDefinition$Format;
        static RGBA2: $FramebufferAttachmentDefinition$Format;
        static RGB8I: $FramebufferAttachmentDefinition$Format;
        static VALUES: $FramebufferAttachmentDefinition$Format[];
        static SRGB: $FramebufferAttachmentDefinition$Format;
        static DEPTH_COMPONENT24: $FramebufferAttachmentDefinition$Format;
        static RGB16_SNORM: $FramebufferAttachmentDefinition$Format;
        static R8I: $FramebufferAttachmentDefinition$Format;
        static COMPRESSED_SRGB_ALPHA: $FramebufferAttachmentDefinition$Format;
        static SRGB_ALPHA: $FramebufferAttachmentDefinition$Format;
        static RGBA16UI: $FramebufferAttachmentDefinition$Format;
        static RED: $FramebufferAttachmentDefinition$Format;
        static R16: $FramebufferAttachmentDefinition$Format;
        static R8_SNORM: $FramebufferAttachmentDefinition$Format;
        static COMPRESSED_SRGB: $FramebufferAttachmentDefinition$Format;
        static DEPTH_STENCIL: $FramebufferAttachmentDefinition$Format;
        static DEPTH_COMPONENT32: $FramebufferAttachmentDefinition$Format;
        static RG8_SNORM: $FramebufferAttachmentDefinition$Format;
        static R3_G3_B2: $FramebufferAttachmentDefinition$Format;
        get format(): number;
        get internalFormat(): number;
    }
    /**
     * Values that may be interpreted as {@link $FramebufferAttachmentDefinition$Format}.
     */
    export type $FramebufferAttachmentDefinition$Format_ = "red" | "rg" | "rgb" | "bgr" | "rgba" | "bgra" | "depth_component" | "depth_stencil" | "r8" | "r8_snorm" | "r16" | "r16_snorm" | "rg8" | "rg8_snorm" | "rg16" | "rg16_snorm" | "r3_g3_b2" | "rgb4" | "rgb5" | "rgb565" | "rgb8" | "rgb8_snorm" | "rgb10" | "rgb12" | "rgb16" | "rgb16_snorm" | "rgba2" | "rgba4" | "rgb5_a1" | "rgba8" | "rgba8_snorm" | "rgb10_a2" | "rgb10_a2ui" | "rgba12" | "rgba16" | "rgba16_snorm" | "srgb" | "srgb8" | "srgb_alpha" | "srgb8_alpha8" | "compressed_srgb" | "compressed_srgb_alpha" | "r16f" | "rg16f" | "rgb16f" | "rgba16f" | "r32f" | "rg32f" | "rgb32f" | "rgb9_e5" | "rgba32f" | "r11f_g11f_b10f" | "r8i" | "r8ui" | "r16i" | "r16ui" | "r32i" | "r32ui" | "rg8i" | "rg8ui" | "rg16i" | "rg16ui" | "rg32i" | "rg32ui" | "rgb8i" | "rgb8ui" | "rgb16i" | "rgb16ui" | "rgb32i" | "rgb32ui" | "rgba8i" | "rgba8ui" | "rgba16i" | "rgba16ui" | "rgba32i" | "rgba32ui" | "depth_component16" | "depth_component24" | "depth_component32" | "depth_component32f" | "depth24_stencil8" | "depth32f_stencil8";
    export class $AdvancedFbo$Builder {
        setName(arg0: string): $AdvancedFbo$Builder;
        build(arg0: boolean): $AdvancedFbo;
        setFormat(arg0: number, arg1: number): $AdvancedFbo$Builder;
        setFormat(arg0: $FramebufferAttachmentDefinition$Format_): $AdvancedFbo$Builder;
        setFilter(arg0: $TextureFilter_): $AdvancedFbo$Builder;
        setFilter(arg0: boolean, arg1: boolean): $AdvancedFbo$Builder;
        setWrap(arg0: number, arg1: number): $AdvancedFbo$Builder;
        setWrap(arg0: $TextureFilter$Wrap_, arg1: $TextureFilter$Wrap_): $AdvancedFbo$Builder;
        addAttachments(arg0: $AdvancedFbo): $AdvancedFbo$Builder;
        addAttachments(arg0: $RenderTarget): $AdvancedFbo$Builder;
        addColorTextureBuffer(arg0: number, arg1: number): $AdvancedFbo$Builder;
        addColorTextureBuffer(): $AdvancedFbo$Builder;
        setDepthTextureWrapper(arg0: number, arg1: number): $AdvancedFbo$Builder;
        setDepthTextureWrapper(arg0: number): $AdvancedFbo$Builder;
        setDebugLabel(arg0: string): $AdvancedFbo$Builder;
        setLevels(arg0: number): $AdvancedFbo$Builder;
        setDepthTextureBuffer(arg0: number, arg1: number): $AdvancedFbo$Builder;
        setDepthTextureBuffer(): $AdvancedFbo$Builder;
        addColorTextureWrapper(arg0: number, arg1: number): $AdvancedFbo$Builder;
        addColorTextureWrapper(arg0: number): $AdvancedFbo$Builder;
        setBorderColor(arg0: number): $AdvancedFbo$Builder;
        setAnisotropy(arg0: number): $AdvancedFbo$Builder;
        setDepthBuffer(arg0: $AdvancedFboAttachment): $AdvancedFbo$Builder;
        addColorRenderBuffer(arg0: number, arg1: number): $AdvancedFbo$Builder;
        addColorRenderBuffer(): $AdvancedFbo$Builder;
        setDepthRenderBuffer(): $AdvancedFbo$Builder;
        setDepthRenderBuffer(arg0: number, arg1: number): $AdvancedFbo$Builder;
        addColorBuffer(arg0: $AdvancedFboAttachment): $AdvancedFbo$Builder;
        setCompareFunction(arg0: $TextureFilter$CompareFunction_): $AdvancedFbo$Builder;
        setWrapS(arg0: number): $AdvancedFbo$Builder;
        setWrapS(arg0: $TextureFilter$Wrap_): $AdvancedFbo$Builder;
        setWrapT(arg0: number): $AdvancedFbo$Builder;
        setWrapT(arg0: $TextureFilter$Wrap_): $AdvancedFbo$Builder;
        constructor(arg0: number, arg1: number);
        set name(value: string);
        set debugLabel(value: string);
        set levels(value: number);
        set borderColor(value: number);
        set anisotropy(value: number);
        set depthBuffer(value: $AdvancedFboAttachment);
        set compareFunction(value: $TextureFilter$CompareFunction_);
    }
    export class $AdvancedFbo {
        static copy(arg0: $RenderTarget): $AdvancedFbo$Builder;
        static copy(arg0: $AdvancedFbo): $AdvancedFbo$Builder;
        static unbind(): void;
        static getMainFramebuffer(): $AdvancedFbo;
        static withSize(arg0: number, arg1: number): $AdvancedFbo$Builder;
        static unbindRead(): void;
        static unbindDraw(): void;
        static get mainFramebuffer(): $AdvancedFbo;
    }
    export interface $AdvancedFbo extends $NativeResource {
        getHeight(): number;
        clear(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        clear(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, ...arg6: number[]): void;
        clear(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        clear(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, ...arg5: number[]): void;
        clear(): void;
        clear(arg0: number): void;
        clear(arg0: number, ...arg1: number[]): void;
        getId(): number;
        create(): void;
        bind(arg0: boolean): void;
        getWidth(): number;
        drawBuffers(...arg0: number[]): void;
        isMutableColorTextureAttachment(arg0: number): boolean;
        isDepthMutableTextureAttachment(): boolean;
        getDepthAttachment(): $AdvancedFboAttachment;
        hasDepthAttachment(): boolean;
        resolveToFbo(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        getClearMask(): number;
        getDebugLabel(): string;
        resolveToScreen(arg0: number, arg1: number): void;
        resolveToScreen(): void;
        hasColorAttachment(arg0: number): boolean;
        getDrawBuffers(): number[];
        resetDrawBuffers(): void;
        toRenderTarget(): $RenderTarget;
        getColorAttachment(arg0: number): $AdvancedFboAttachment;
        resolveToRenderTarget(arg0: $RenderTarget): void;
        resolveToRenderTarget(arg0: $RenderTarget, arg1: number, arg2: number): void;
        isColorTextureAttachment(arg0: number): boolean;
        setColorAttachmentTexture(arg0: number, arg1: number, arg2: number): void;
        setColorAttachmentTexture(arg0: number, arg1: number): void;
        setDepthAttachmentTexture(arg0: number): void;
        setDepthAttachmentTexture(arg0: number, arg1: number): void;
        getColorTextureAttachment(arg0: number): $AdvancedFboTextureAttachment;
        isColorRenderAttachment(arg0: number): boolean;
        resolveToAdvancedFbo(arg0: $AdvancedFbo): void;
        resolveToAdvancedFbo(arg0: $AdvancedFbo, arg1: number, arg2: number): void;
        isDepthTextureAttachment(): boolean;
        isDepthRenderAttachment(): boolean;
        getColorAttachments(): number;
        hasStencilAttachment(): boolean;
        getDepthTextureAttachment(): $AdvancedFboTextureAttachment;
        getDepthRenderAttachment(): $AdvancedFboRenderAttachment;
        getColorRenderAttachment(arg0: number): $AdvancedFboRenderAttachment;
        bindRead(): void;
        bindDraw(arg0: boolean): void;
        get height(): number;
        get id(): number;
        get width(): number;
        get depthMutableTextureAttachment(): boolean;
        get depthAttachment(): $AdvancedFboAttachment;
        get clearMask(): number;
        get debugLabel(): string;
        get colorAttachments(): number;
    }
    export class $AdvancedFboRenderAttachment implements $AdvancedFboAttachment {
        getName(): string;
        clone(): $AdvancedFboAttachment;
        getId(): number;
        create(): void;
        attach(arg0: $AdvancedFbo, arg1: number): void;
        free(): void;
        getFormat(): number;
        getLevels(): number;
        getAttachmentType(): number;
        bindAttachment(): void;
        unbindAttachment(): void;
        canSample(): boolean;
        close(): void;
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number);
        get name(): string;
        get id(): number;
        get format(): number;
        get levels(): number;
        get attachmentType(): number;
    }
    export class $AdvancedFboAttachment {
    }
    export interface $AdvancedFboAttachment extends $NativeResource, $Cloneable {
        getName(): string;
        clone(): $AdvancedFboAttachment;
        create(): void;
        attach(arg0: $AdvancedFbo, arg1: number): void;
        getFormat(): number;
        getLevels(): number;
        getAttachmentType(): number;
        bindAttachment(): void;
        unbindAttachment(): void;
        canSample(): boolean;
        get name(): string;
        get format(): number;
        get levels(): number;
        get attachmentType(): number;
    }
    export class $AdvancedFboTextureAttachment extends $AbstractTexture implements $AdvancedFboAttachment {
        getHeight(): number;
        getName(): string;
        create(): void;
        attach(arg0: $AdvancedFbo, arg1: number): void;
        free(): void;
        getFilter(): $TextureFilter;
        getFormat(): number;
        getWidth(): number;
        getLevels(): number;
        getAttachmentType(): number;
        bindAttachment(): void;
        unbindAttachment(): void;
        canSample(): boolean;
        clone(): $AdvancedFboAttachment;
        static NOT_ASSIGNED: number;
        mipmap: boolean;
        blur: boolean;
        id: number;
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: $TextureFilter_, arg7: string);
        get height(): number;
        get name(): string;
        get filter(): $TextureFilter;
        get format(): number;
        get width(): number;
        get levels(): number;
        get attachmentType(): number;
    }
}
